/**
 * デザインライブラリー（design-library.jp）を参考にした高品質バナープロンプト
 * 
 * 各ジャンル × 5パターン = 合計60種類の厳選プロンプト
 * 
 * プロンプト構造:
 * - 構図 / レイアウト
 * - 被写体 / ビジュアル要素
 * - 色味 / カラーパレット
 * - デザイン要素 / 装飾
 * - テキスト構成 / タイポグラフィ
 * 
 * 参照: https://design-library.jp/taste/simple/page/2
 */

export interface BannerPromptV2 {
  id: string
  genre: string // ジャンル名（日本語）
  category: string // カテゴリコード（it, recruit, ec, beauty, etc.）
  name: string // プロンプト名
  displayTitle: string // 表示用の短い日本語タイトル
  prompt: {
    composition: string // 構図
    subject: string // 被写体
    colorPalette: string // 色味
    designElements: string // デザイン要素
    typography: string // テキスト構成
  }
  fullPrompt: string // 生成用の完全なプロンプト
  tags: string[] // タグ
}

/**
 * ジャンル定義
 */
export const GENRES = [
  { id: 'fashion', name: 'ファッション・アパレル', category: 'ec' },
  { id: 'beauty', name: '美容・コスメ', category: 'beauty' },
  { id: 'food', name: '飲料・食品', category: 'ec' },
  { id: 'it', name: 'IT・テクノロジー', category: 'it' },
  { id: 'business', name: 'ビジネス・SaaS', category: 'it' },
  { id: 'recruit', name: '転職・採用・人材', category: 'recruit' },
  { id: 'education', name: '教育・学習・セミナー', category: 'it' },
  { id: 'travel', name: '旅行・観光', category: 'ec' },
  { id: 'realestate', name: '住宅・不動産', category: 'ec' },
  { id: 'event', name: 'イベント・メディア', category: 'ec' },
  { id: 'luxury', name: '高級・ラグジュアリー', category: 'beauty' },
  { id: 'natural', name: 'ナチュラル・オーガニック', category: 'beauty' },
] as const

/**
 * 高品質バナープロンプト（各ジャンル5パターン）
 */
export const BANNER_PROMPTS_V2: BannerPromptV2[] = [
  // ============================================
  // ファッション・アパレル（5パターン）
  // ============================================
  {
    id: 'fashion-001',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'ミニマルモノトーン',
    displayTitle: '洗練モノトーン',
    prompt: {
      composition: '左右非対称の分割レイアウト、左1/3にテキスト、右2/3に商品',
      subject: 'ハイエンドファッションアイテム、シンプルな背景に浮かぶ商品',
      colorPalette: 'モノトーン（白#FFFFFF、黒#000000、グレー#808080）',
      designElements: '細い線のフレーム、余白を活かしたミニマルデザイン',
      typography: 'セリフ体の大きなタイトル、サンセリフの小さなサブテキスト',
    },
    fullPrompt: 'A minimalist fashion banner with asymmetric layout, high-end fashion item floating on clean white background, monochrome color scheme (white, black, gray), thin line frame accents, elegant serif typography for headline with sans-serif subtext, generous white space, professional and sophisticated mood, 1200x628 pixels',
    tags: ['シンプル', 'モノトーン', 'ミニマル', '高級感'],
  },
  {
    id: 'fashion-002',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'カジュアルポップ',
    displayTitle: 'ポップカジュアル',
    prompt: {
      composition: '中央配置、商品を囲むように装飾要素',
      subject: 'カジュアルウェア、動きのあるポーズの人物シルエット',
      colorPalette: 'ビビッドカラー（イエロー#FFD700、オレンジ#FF6B35、ホワイト）',
      designElements: '手書き風のアクセント、ステッカー風の装飾',
      typography: '太めのゴシック体、斜めに配置されたテキスト',
    },
    fullPrompt: 'A casual pop fashion banner with centered layout, casual wear items surrounded by playful decorations, vibrant color scheme (yellow, orange, white), hand-drawn style accents and sticker-like elements, bold gothic typography placed at dynamic angles, energetic and youthful mood, 1200x628 pixels',
    tags: ['カジュアル', 'ポップ', 'にぎやか', 'カラフル'],
  },
  {
    id: 'fashion-003',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'エレガントベージュ',
    displayTitle: '上品ベージュ',
    prompt: {
      composition: '上下分割、上部に写真、下部にテキストエリア',
      subject: 'エレガントなドレスやコート、柔らかい光の中の商品',
      colorPalette: 'ベージュ系（#F5F5DC、#D2B48C、#8B7355）',
      designElements: '繊細なゴールドのライン、オーガニックな曲線',
      typography: '細身のセリフ体、レタースペーシング広め',
    },
    fullPrompt: 'An elegant fashion banner with horizontal split layout, elegant dress or coat in soft lighting on top, text area below, beige color palette (cream, tan, brown), delicate gold line accents with organic curves, thin serif typography with wide letter spacing, refined and sophisticated mood, 1200x628 pixels',
    tags: ['エレガント', 'ベージュ', '上品', 'きれいめ'],
  },
  {
    id: 'fashion-004',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'ストリートダーク',
    displayTitle: 'ストリート',
    prompt: {
      composition: '斜めの分割線、ダイナミックな構図',
      subject: 'ストリートファッション、都市の背景、グラフィティ要素',
      colorPalette: 'ダークトーン（#1A1A1A、#FF0000、#FFFFFF）',
      designElements: 'グリッチエフェクト、ノイズテクスチャ',
      typography: '極太のサンセリフ、グリッチ加工されたテキスト',
    },
    fullPrompt: 'A street fashion banner with diagonal split composition, street fashion items with urban background and graffiti elements, dark color scheme (black, red accent, white), glitch effects and noise texture, extra bold sans-serif typography with glitch processing, edgy and urban mood, 1200x628 pixels',
    tags: ['ストリート', 'ダーク', 'かっこいい', 'アーバン'],
  },
  {
    id: 'fashion-005',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'シーズナルパステル',
    displayTitle: '季節パステル',
    prompt: {
      composition: 'グリッドレイアウト、複数商品の配置',
      subject: '季節のファッションアイテム、花や植物のアクセント',
      colorPalette: 'パステルカラー（#FFB6C1、#87CEEB、#98FB98）',
      designElements: '水彩風のテクスチャ、花のイラスト',
      typography: '丸みのあるゴシック体、柔らかい印象',
    },
    fullPrompt: 'A seasonal fashion banner with grid layout showcasing multiple items, seasonal fashion pieces with flower and plant accents, pastel color palette (pink, sky blue, mint green), watercolor texture effects with floral illustrations, rounded gothic typography with soft impression, fresh and feminine mood, 1200x628 pixels',
    tags: ['季節感', 'パステル', 'かわいい', 'フェミニン'],
  },

  // ============================================
  // 美容・コスメ（5パターン）
  // ============================================
  {
    id: 'beauty-001',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'ラグジュアリーゴールド',
    displayTitle: '高級ゴールド',
    prompt: {
      composition: '中央に商品、周囲にゴールドの装飾',
      subject: '高級コスメボトル、光沢のある質感',
      colorPalette: 'ブラック×ゴールド（#000000、#D4AF37、#FFFFFF）',
      designElements: 'ゴールドのパーティクル、光の反射',
      typography: 'エレガントなセリフ体、ゴールドカラー',
    },
    fullPrompt: 'A luxury beauty banner with centered product layout, high-end cosmetic bottle with glossy texture, black and gold color scheme with white accents, gold particle effects and light reflections, elegant serif typography in gold, luxurious and premium mood, 1200x628 pixels',
    tags: ['高級感', 'ゴールド', 'ラグジュアリー', 'コスメ'],
  },
  {
    id: 'beauty-002',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'ナチュラルオーガニック',
    displayTitle: 'ナチュラル',
    prompt: {
      composition: '左右対称、商品を中心に植物で囲む',
      subject: 'オーガニックコスメ、ハーブや植物の素材',
      colorPalette: 'アースカラー（#8FBC8F、#F5DEB3、#DEB887）',
      designElements: '植物のイラスト、自然な質感のテクスチャ',
      typography: '細身のサンセリフ、ナチュラルな印象',
    },
    fullPrompt: 'A natural beauty banner with symmetrical layout, organic cosmetic product surrounded by herbs and botanical elements, earth tone color palette (sage green, wheat, burlywood), botanical illustrations with natural textures, thin sans-serif typography with natural feel, organic and clean mood, 1200x628 pixels',
    tags: ['ナチュラル', 'オーガニック', '植物', 'クリーン'],
  },
  {
    id: 'beauty-003',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'ピンクグラデーション',
    displayTitle: 'ピンクグラデ',
    prompt: {
      composition: '斜めのグラデーション背景、商品を浮かせて配置',
      subject: 'リップやチーク、ピンク系コスメ',
      colorPalette: 'ピンクグラデーション（#FFB6C1→#FF69B4→#FF1493）',
      designElements: 'ソフトなグロー効果、キラキラのパーティクル',
      typography: '丸みのあるフォント、ホワイトカラー',
    },
    fullPrompt: 'A pink beauty banner with diagonal gradient background, lip and cheek products floating elegantly, pink gradient color scheme (light pink to hot pink to deep pink), soft glow effects with sparkle particles, rounded typography in white, feminine and romantic mood, 1200x628 pixels',
    tags: ['ピンク', 'グラデーション', 'かわいい', 'ロマンチック'],
  },
  {
    id: 'beauty-004',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'クリニカルホワイト',
    displayTitle: 'クリニカル',
    prompt: {
      composition: 'クリーンな白背景、商品を整然と配置',
      subject: 'スキンケア製品、清潔感のあるパッケージ',
      colorPalette: 'ホワイト×ブルー（#FFFFFF、#E0FFFF、#4169E1）',
      designElements: '水滴、泡、クリーンなライン',
      typography: 'モダンなサンセリフ、ブルーアクセント',
    },
    fullPrompt: 'A clinical beauty banner with clean white background, skincare products arranged neatly, white and blue color scheme (white, light cyan, royal blue), water droplet and bubble elements with clean lines, modern sans-serif typography with blue accent, clinical and trustworthy mood, 1200x628 pixels',
    tags: ['クリニカル', 'ホワイト', '清潔感', 'スキンケア'],
  },
  {
    id: 'beauty-005',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'アートメイク',
    displayTitle: 'アートメイク',
    prompt: {
      composition: '大胆な色面分割、アーティスティックな構図',
      subject: 'カラフルなメイクアップ製品、アイシャドウパレット',
      colorPalette: 'マルチカラー（#FF6B6B、#4ECDC4、#FFE66D、#95E1D3）',
      designElements: '絵の具のテクスチャ、ブラシストローク',
      typography: '手書き風フォント、アーティスティック',
    },
    fullPrompt: 'An artistic beauty banner with bold color block composition, colorful makeup products and eyeshadow palettes, multi-color palette (coral, teal, yellow, mint), paint texture and brush stroke elements, handwritten style typography with artistic flair, creative and expressive mood, 1200x628 pixels',
    tags: ['アート', 'カラフル', 'クリエイティブ', 'メイク'],
  },

  // ============================================
  // 飲料・食品（5パターン）
  // ============================================
  {
    id: 'food-001',
    genre: '飲料・食品',
    category: 'ec',
    name: 'シズル感フード',
    displayTitle: 'シズル感',
    prompt: {
      composition: '商品を大きく中央に、湯気や水滴の演出',
      subject: '美味しそうな料理、新鮮な食材',
      colorPalette: '暖色系（#FF6347、#FFA500、#8B4513）',
      designElements: '湯気、水滴、光の反射',
      typography: '太めの丸ゴシック、食欲をそそる配色',
    },
    fullPrompt: 'A food banner with large centered product, steam and water droplet effects, delicious looking dish with fresh ingredients, warm color palette (tomato red, orange, saddle brown), steam effects and water droplets with light reflections, bold rounded gothic typography in appetizing colors, mouth-watering and fresh mood, 1200x628 pixels',
    tags: ['シズル感', '食品', '美味しそう', '暖色'],
  },
  {
    id: 'food-002',
    genre: '飲料・食品',
    category: 'ec',
    name: 'カフェスタイル',
    displayTitle: 'カフェ風',
    prompt: {
      composition: '俯瞰アングル、テーブルセッティング風',
      subject: 'コーヒーやスイーツ、カフェの雰囲気',
      colorPalette: 'ブラウン系（#8B4513、#D2691E、#F5DEB3）',
      designElements: '木目テクスチャ、手書き風イラスト',
      typography: '手書き風フォント、チョークボード風',
    },
    fullPrompt: 'A cafe style food banner with overhead angle table setting, coffee and sweets with cafe atmosphere, brown color palette (saddle brown, chocolate, wheat), wood grain texture with hand-drawn illustrations, handwritten style typography like chalkboard, cozy and warm mood, 1200x628 pixels',
    tags: ['カフェ', 'ブラウン', 'ナチュラル', 'コーヒー'],
  },
  {
    id: 'food-003',
    genre: '飲料・食品',
    category: 'ec',
    name: 'フレッシュグリーン',
    displayTitle: 'フレッシュ',
    prompt: {
      composition: '斜めの構図、野菜や果物を散りばめる',
      subject: '新鮮な野菜、フルーツ、ヘルシーフード',
      colorPalette: 'グリーン系（#228B22、#90EE90、#ADFF2F）',
      designElements: '水滴、葉っぱ、自然光',
      typography: 'クリーンなサンセリフ、グリーンアクセント',
    },
    fullPrompt: 'A fresh food banner with diagonal composition, fresh vegetables and fruits scattered artfully, green color palette (forest green, light green, green yellow), water droplet effects with leaves and natural lighting, clean sans-serif typography with green accent, healthy and fresh mood, 1200x628 pixels',
    tags: ['フレッシュ', 'グリーン', 'ヘルシー', '野菜'],
  },
  {
    id: 'food-004',
    genre: '飲料・食品',
    category: 'ec',
    name: '和食モダン',
    displayTitle: '和モダン',
    prompt: {
      composition: '余白を活かした和の構図、非対称バランス',
      subject: '和食、日本料理、器の美しさ',
      colorPalette: '和カラー（#2F4F4F、#8B0000、#F5F5DC）',
      designElements: '和紙テクスチャ、墨のアクセント',
      typography: '明朝体、縦書きも可',
    },
    fullPrompt: 'A modern Japanese food banner with asymmetric composition using white space, Japanese cuisine with beautiful tableware, Japanese color palette (dark slate gray, dark red, beige), washi paper texture with ink brush accents, Mincho typography with possible vertical text, elegant and refined mood, 1200x628 pixels',
    tags: ['和食', 'モダン', '上品', '日本'],
  },
  {
    id: 'food-005',
    genre: '飲料・食品',
    category: 'ec',
    name: 'ポップスイーツ',
    displayTitle: 'スイーツ',
    prompt: {
      composition: 'カラフルな背景、スイーツを浮かせて配置',
      subject: 'カラフルなスイーツ、キャンディ、アイスクリーム',
      colorPalette: 'パステルポップ（#FFB6C1、#87CEEB、#DDA0DD、#F0E68C）',
      designElements: 'コンフェッティ、星、ハート',
      typography: 'ポップな丸文字、カラフル',
    },
    fullPrompt: 'A pop sweets banner with colorful background, sweets floating playfully, candy and ice cream, pastel pop color palette (light pink, sky blue, plum, khaki), confetti stars and hearts decorations, pop rounded typography in colorful style, fun and playful mood, 1200x628 pixels',
    tags: ['スイーツ', 'ポップ', 'カラフル', 'かわいい'],
  },

  // ============================================
  // IT・テクノロジー（5パターン）
  // ============================================
  {
    id: 'it-001',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'サイバーネオン',
    displayTitle: 'サイバー',
    prompt: {
      composition: 'ダーク背景にネオンラインが走る構図',
      subject: 'デジタルインターフェース、回路パターン',
      colorPalette: 'サイバー（#0D0D0D、#00FFFF、#FF00FF、#39FF14）',
      designElements: 'ネオングロー、グリッドライン、パーティクル',
      typography: 'フューチャリスティックなサンセリフ、ネオンエフェクト',
    },
    fullPrompt: 'A cyber tech banner with dark background and neon lines, digital interface with circuit patterns, cyber color palette (black, cyan, magenta, neon green), neon glow effects with grid lines and particles, futuristic sans-serif typography with neon effect, high-tech and futuristic mood, 1200x628 pixels',
    tags: ['サイバー', 'ネオン', 'テクノロジー', '未来的'],
  },
  {
    id: 'it-002',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'クリーンテック',
    displayTitle: 'クリーン',
    prompt: {
      composition: '白背景にクリーンなUI要素を配置',
      subject: 'モダンなUIコンポーネント、デバイスモックアップ',
      colorPalette: 'クリーン（#FFFFFF、#F8F9FA、#007BFF、#6C757D）',
      designElements: 'シャドウ、カード、アイコン',
      typography: 'モダンなサンセリフ、ブルーアクセント',
    },
    fullPrompt: 'A clean tech banner with white background and UI elements, modern UI components with device mockups, clean color palette (white, light gray, blue, gray), subtle shadows with card and icon elements, modern sans-serif typography with blue accent, professional and trustworthy mood, 1200x628 pixels',
    tags: ['クリーン', 'UI', 'モダン', 'プロフェッショナル'],
  },
  {
    id: 'it-003',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'グラデーションテック',
    displayTitle: 'グラデ',
    prompt: {
      composition: '大胆なグラデーション背景、中央にメッセージ',
      subject: '抽象的な3D形状、浮遊するオブジェクト',
      colorPalette: 'グラデーション（#667eea→#764ba2、#f093fb→#f5576c）',
      designElements: '3Dオブジェクト、グラデーションメッシュ',
      typography: '太めのサンセリフ、ホワイト',
    },
    fullPrompt: 'A gradient tech banner with bold gradient background, abstract 3D shapes and floating objects, gradient color palette (purple to pink, blue to violet), 3D objects with gradient mesh effects, bold sans-serif typography in white, modern and dynamic mood, 1200x628 pixels',
    tags: ['グラデーション', '3D', 'モダン', 'ダイナミック'],
  },
  {
    id: 'it-004',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'データビジュアル',
    displayTitle: 'データ',
    prompt: {
      composition: 'ダッシュボード風のレイアウト、グラフやチャート',
      subject: 'データビジュアライゼーション、分析画面',
      colorPalette: 'ダークモード（#1E1E1E、#2D2D2D、#00D4FF、#00FF88）',
      designElements: 'グラフ、チャート、数値表示',
      typography: 'モノスペース風、データ表示',
    },
    fullPrompt: 'A data visualization banner with dashboard-style layout, graphs and charts, data analytics screen, dark mode color palette (dark gray, charcoal, cyan, green), graph and chart elements with numerical displays, monospace-style typography for data display, analytical and professional mood, 1200x628 pixels',
    tags: ['データ', 'ダッシュボード', 'アナリティクス', 'ダークモード'],
  },
  {
    id: 'it-005',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'AIイノベーション',
    displayTitle: 'AI',
    prompt: {
      composition: '中央にAI/ロボットのビジュアル、周囲にデータフロー',
      subject: 'AI、機械学習、ニューラルネットワーク',
      colorPalette: 'AIカラー（#0A192F、#64FFDA、#8892B0、#CCD6F6）',
      designElements: 'ニューラルネットワーク図、データフロー',
      typography: 'テクニカルなサンセリフ、ミントアクセント',
    },
    fullPrompt: 'An AI innovation banner with centered AI visual, data flow surrounding, AI and machine learning neural network imagery, AI color palette (dark blue, mint, slate, light blue), neural network diagrams with data flow elements, technical sans-serif typography with mint accent, innovative and intelligent mood, 1200x628 pixels',
    tags: ['AI', 'イノベーション', 'ニューラル', 'インテリジェント'],
  },

  // ============================================
  // ビジネス・SaaS（5パターン）
  // ============================================
  {
    id: 'business-001',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'コーポレートブルー',
    displayTitle: 'コーポレート',
    prompt: {
      composition: '左側にテキスト、右側にビジュアル',
      subject: 'ビジネスパーソン、オフィス環境',
      colorPalette: 'コーポレート（#003366、#0066CC、#FFFFFF、#F5F5F5）',
      designElements: 'クリーンなライン、プロフェッショナルな写真',
      typography: 'ビジネス向けサンセリフ、ネイビー',
    },
    fullPrompt: 'A corporate business banner with text on left and visual on right, business person in office environment, corporate blue color palette (navy, blue, white, light gray), clean lines with professional photography, business-oriented sans-serif typography in navy, professional and trustworthy mood, 1200x628 pixels',
    tags: ['コーポレート', 'ブルー', 'ビジネス', 'プロフェッショナル'],
  },
  {
    id: 'business-002',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'スタートアップモダン',
    displayTitle: 'スタートアップ',
    prompt: {
      composition: '大胆なタイポグラフィ中心、ミニマルな背景',
      subject: 'プロダクトUI、チームワーク',
      colorPalette: 'スタートアップ（#6C63FF、#FF6584、#FFFFFF、#2D3436）',
      designElements: 'イラスト、アイコン、フラットデザイン',
      typography: '太めのサンセリフ、パープルアクセント',
    },
    fullPrompt: 'A startup modern banner with bold typography focus, minimal background, product UI and teamwork imagery, startup color palette (purple, coral, white, dark gray), illustration and icon elements in flat design, bold sans-serif typography with purple accent, innovative and energetic mood, 1200x628 pixels',
    tags: ['スタートアップ', 'モダン', 'イノベーション', 'フラット'],
  },
  {
    id: 'business-003',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'エンタープライズ',
    displayTitle: 'エンプラ',
    prompt: {
      composition: '整然としたグリッドレイアウト、情報の階層化',
      subject: 'エンタープライズソリューション、セキュリティ',
      colorPalette: 'エンタープライズ（#1A1A2E、#16213E、#0F3460、#E94560）',
      designElements: 'シールド、ロック、グラフ',
      typography: 'フォーマルなサンセリフ、ホワイト',
    },
    fullPrompt: 'An enterprise business banner with organized grid layout, information hierarchy, enterprise solution and security imagery, enterprise color palette (dark navy, deep blue, navy, red accent), shield lock and graph elements, formal sans-serif typography in white, secure and reliable mood, 1200x628 pixels',
    tags: ['エンタープライズ', 'セキュリティ', '信頼', 'フォーマル'],
  },
  {
    id: 'business-004',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'グロースハック',
    displayTitle: 'グロース',
    prompt: {
      composition: '上昇するグラフやチャートを背景に',
      subject: '成長、スケール、データ分析',
      colorPalette: 'グロース（#00C853、#69F0AE、#FFFFFF、#212121）',
      designElements: '上昇矢印、グラフ、パーセンテージ',
      typography: 'インパクトのあるサンセリフ、グリーン',
    },
    fullPrompt: 'A growth hacking banner with rising graphs and charts in background, growth scale and data analysis imagery, growth color palette (green, light green, white, dark gray), rising arrows graphs and percentage elements, impactful sans-serif typography in green, ambitious and dynamic mood, 1200x628 pixels',
    tags: ['グロース', 'データ', '成長', 'ダイナミック'],
  },
  {
    id: 'business-005',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'コラボレーション',
    displayTitle: 'コラボ',
    prompt: {
      composition: '複数の人物やアイコンが繋がるビジュアル',
      subject: 'チームワーク、コミュニケーション、リモートワーク',
      colorPalette: 'コラボ（#4A90D9、#7B68EE、#FFB347、#FFFFFF）',
      designElements: '接続線、アバター、チャットバブル',
      typography: 'フレンドリーなサンセリフ、ブルー',
    },
    fullPrompt: 'A collaboration banner with connected people and icons visual, teamwork communication and remote work imagery, collaboration color palette (blue, purple, orange, white), connection lines avatars and chat bubble elements, friendly sans-serif typography in blue, connected and collaborative mood, 1200x628 pixels',
    tags: ['コラボレーション', 'チーム', 'コミュニケーション', 'リモート'],
  },

  // ============================================
  // 転職・採用・人材（5パターン）
  // ============================================
  {
    id: 'recruit-001',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'キャリアアップ',
    displayTitle: 'キャリア',
    prompt: {
      composition: '上昇するビジュアル、ステップアップのイメージ',
      subject: 'ビジネスパーソン、階段、成長',
      colorPalette: 'キャリア（#2C3E50、#3498DB、#ECF0F1、#E74C3C）',
      designElements: '階段、矢印、チェックマーク',
      typography: '力強いサンセリフ、ネイビー',
    },
    fullPrompt: 'A career up recruitment banner with ascending visual and step-up imagery, business person with stairs and growth symbols, career color palette (dark blue, blue, light gray, red accent), stair arrow and checkmark elements, powerful sans-serif typography in navy, ambitious and motivating mood, 1200x628 pixels',
    tags: ['キャリア', '成長', '転職', 'モチベーション'],
  },
  {
    id: 'recruit-002',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'ダイバーシティ',
    displayTitle: '多様性',
    prompt: {
      composition: '多様な人物のシルエットやイラスト',
      subject: '多様性、インクルージョン、チーム',
      colorPalette: 'ダイバーシティ（#FF6B6B、#4ECDC4、#FFE66D、#95E1D3、#6C5CE7）',
      designElements: '人物シルエット、カラフルな図形',
      typography: 'インクルーシブなサンセリフ、マルチカラー',
    },
    fullPrompt: 'A diversity recruitment banner with diverse people silhouettes and illustrations, diversity inclusion and team imagery, diversity color palette (coral, teal, yellow, mint, purple), people silhouettes with colorful shapes, inclusive sans-serif typography in multi-color, welcoming and diverse mood, 1200x628 pixels',
    tags: ['ダイバーシティ', 'インクルージョン', 'チーム', 'カラフル'],
  },
  {
    id: 'recruit-003',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'テックリクルート',
    displayTitle: 'テック採用',
    prompt: {
      composition: 'コードやテクノロジー要素を背景に',
      subject: 'エンジニア、開発環境、コード',
      colorPalette: 'テック（#1E1E1E、#569CD6、#4EC9B0、#CE9178）',
      designElements: 'コードスニペット、ターミナル、IDE',
      typography: 'モノスペース、テック感',
    },
    fullPrompt: 'A tech recruitment banner with code and technology elements in background, engineer development environment and code imagery, tech color palette (dark, blue, teal, orange - VS Code inspired), code snippet terminal and IDE elements, monospace typography with tech feel, developer-friendly and innovative mood, 1200x628 pixels',
    tags: ['テック', 'エンジニア', '開発', 'コード'],
  },
  {
    id: 'recruit-004',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'ワークライフバランス',
    displayTitle: 'WLB',
    prompt: {
      composition: '仕事とプライベートの両方を表現',
      subject: 'リモートワーク、家族、趣味',
      colorPalette: 'バランス（#48C9B0、#F39C12、#FFFFFF、#34495E）',
      designElements: 'ノートPC、家、植物、太陽',
      typography: '親しみやすいサンセリフ、ティール',
    },
    fullPrompt: 'A work-life balance recruitment banner expressing both work and private life, remote work family and hobby imagery, balance color palette (teal, orange, white, dark gray), laptop home plant and sun elements, friendly sans-serif typography in teal, balanced and healthy mood, 1200x628 pixels',
    tags: ['ワークライフ', 'バランス', 'リモート', '健康'],
  },
  {
    id: 'recruit-005',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'ミッションドリブン',
    displayTitle: 'ミッション',
    prompt: {
      composition: '大きなビジョンステートメント、背景に活動写真',
      subject: '社会貢献、ミッション、パーパス',
      colorPalette: 'ミッション（#2C3E50、#1ABC9C、#FFFFFF、#E67E22）',
      designElements: '地球、ハンドシェイク、ハート',
      typography: 'インスピレーショナルなセリフ、ダークブルー',
    },
    fullPrompt: 'A mission-driven recruitment banner with large vision statement, activity photos in background, social contribution mission and purpose imagery, mission color palette (dark blue, teal, white, orange), globe handshake and heart elements, inspirational serif typography in dark blue, purposeful and inspiring mood, 1200x628 pixels',
    tags: ['ミッション', 'パーパス', '社会貢献', 'インスピレーション'],
  },

  // ============================================
  // 教育・学習・セミナー（5パターン）
  // ============================================
  {
    id: 'education-001',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'オンラインラーニング',
    displayTitle: 'オンライン',
    prompt: {
      composition: 'デバイスと学習コンテンツを組み合わせ',
      subject: 'オンライン学習、動画、インタラクティブ',
      colorPalette: 'ラーニング（#4A90D9、#50C878、#FFFFFF、#333333）',
      designElements: 'プレイボタン、プログレスバー、チェックマーク',
      typography: 'クリアなサンセリフ、ブルー',
    },
    fullPrompt: 'An online learning education banner combining devices and learning content, online learning video and interactive imagery, learning color palette (blue, emerald, white, dark gray), play button progress bar and checkmark elements, clear sans-serif typography in blue, educational and accessible mood, 1200x628 pixels',
    tags: ['オンライン', 'ラーニング', 'eラーニング', 'アクセシブル'],
  },
  {
    id: 'education-002',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'アカデミック',
    displayTitle: '学術',
    prompt: {
      composition: '本や学術的なモチーフを配置',
      subject: '書籍、卒業帽、証明書',
      colorPalette: 'アカデミック（#1E3A5F、#C9A227、#FFFFFF、#F5F5F5）',
      designElements: '本、卒業帽、メダル、証明書',
      typography: 'クラシックなセリフ、ネイビー',
    },
    fullPrompt: 'An academic education banner with books and scholarly motifs, books graduation cap and certificate imagery, academic color palette (navy, gold, white, light gray), book graduation cap medal and certificate elements, classic serif typography in navy, prestigious and scholarly mood, 1200x628 pixels',
    tags: ['アカデミック', '学術', '卒業', 'プレステージ'],
  },
  {
    id: 'education-003',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'スキルアップ',
    displayTitle: 'スキル',
    prompt: {
      composition: 'スキルバーやレベルアップのビジュアル',
      subject: 'スキル習得、成長、達成',
      colorPalette: 'スキル（#6C63FF、#FF6584、#FFFFFF、#2D3436）',
      designElements: 'スキルバー、バッジ、レベル表示',
      typography: 'モダンなサンセリフ、パープル',
    },
    fullPrompt: 'A skill-up education banner with skill bars and level-up visuals, skill acquisition growth and achievement imagery, skill color palette (purple, coral, white, dark gray), skill bar badge and level display elements, modern sans-serif typography in purple, motivating and progressive mood, 1200x628 pixels',
    tags: ['スキルアップ', '成長', '達成', 'モチベーション'],
  },
  {
    id: 'education-004',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'ウェビナー',
    displayTitle: 'ウェビナー',
    prompt: {
      composition: 'スピーカーと参加者のビジュアル',
      subject: 'ウェビナー、オンラインセミナー、ライブ配信',
      colorPalette: 'ウェビナー（#FF5722、#FFFFFF、#212121、#FFC107）',
      designElements: 'カメラ、マイク、ライブバッジ',
      typography: 'インパクトのあるサンセリフ、オレンジ',
    },
    fullPrompt: 'A webinar education banner with speaker and participant visuals, webinar online seminar and live streaming imagery, webinar color palette (orange, white, dark gray, yellow), camera microphone and live badge elements, impactful sans-serif typography in orange, engaging and live mood, 1200x628 pixels',
    tags: ['ウェビナー', 'ライブ', 'セミナー', 'エンゲージング'],
  },
  {
    id: 'education-005',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'キッズラーニング',
    displayTitle: 'キッズ',
    prompt: {
      composition: 'カラフルで楽しい構図、イラスト中心',
      subject: '子供向け学習、遊びながら学ぶ',
      colorPalette: 'キッズ（#FF6B6B、#4ECDC4、#FFE66D、#95E1D3）',
      designElements: 'かわいいイラスト、星、虹',
      typography: '丸みのあるポップなフォント、カラフル',
    },
    fullPrompt: 'A kids learning education banner with colorful fun composition, illustration-focused, kids learning and play-based education imagery, kids color palette (coral, teal, yellow, mint), cute illustrations stars and rainbow elements, rounded pop typography in colorful style, fun and educational mood, 1200x628 pixels',
    tags: ['キッズ', '楽しい', 'イラスト', 'ポップ'],
  },

  // ============================================
  // 旅行・観光（5パターン）
  // ============================================
  {
    id: 'travel-001',
    genre: '旅行・観光',
    category: 'ec',
    name: 'リゾートパラダイス',
    displayTitle: 'リゾート',
    prompt: {
      composition: '美しい風景写真を全面に、テキストオーバーレイ',
      subject: 'ビーチ、海、リゾート',
      colorPalette: 'リゾート（#00CED1、#FFD700、#FFFFFF、#87CEEB）',
      designElements: 'ヤシの木、波、太陽',
      typography: '軽やかなサンセリフ、ホワイト',
    },
    fullPrompt: 'A resort paradise travel banner with beautiful landscape photo full-bleed, text overlay, beach ocean and resort imagery, resort color palette (turquoise, gold, white, sky blue), palm tree wave and sun elements, light sans-serif typography in white, relaxing and dreamy mood, 1200x628 pixels',
    tags: ['リゾート', 'ビーチ', '海', 'リラックス'],
  },
  {
    id: 'travel-002',
    genre: '旅行・観光',
    category: 'ec',
    name: 'アドベンチャー',
    displayTitle: '冒険',
    prompt: {
      composition: 'ダイナミックな構図、アクションショット',
      subject: '冒険、アウトドア、自然',
      colorPalette: 'アドベンチャー（#2E7D32、#FF6F00、#FFFFFF、#37474F）',
      designElements: '山、コンパス、バックパック',
      typography: '力強いサンセリフ、オレンジ',
    },
    fullPrompt: 'An adventure travel banner with dynamic composition and action shots, adventure outdoor and nature imagery, adventure color palette (green, orange, white, dark gray), mountain compass and backpack elements, powerful sans-serif typography in orange, exciting and adventurous mood, 1200x628 pixels',
    tags: ['アドベンチャー', 'アウトドア', '冒険', 'エキサイティング'],
  },
  {
    id: 'travel-003',
    genre: '旅行・観光',
    category: 'ec',
    name: 'シティトリップ',
    displayTitle: 'シティ',
    prompt: {
      composition: '都市のスカイライン、ランドマーク',
      subject: '都市観光、建築、ナイトビュー',
      colorPalette: 'シティ（#1A237E、#FFD54F、#FFFFFF、#424242）',
      designElements: 'ビル、飛行機、地図ピン',
      typography: 'モダンなサンセリフ、ゴールド',
    },
    fullPrompt: 'A city trip travel banner with urban skyline and landmarks, city tourism architecture and night view imagery, city color palette (indigo, gold, white, gray), building airplane and map pin elements, modern sans-serif typography in gold, urban and sophisticated mood, 1200x628 pixels',
    tags: ['シティ', '都市', '観光', 'ソフィスティケート'],
  },
  {
    id: 'travel-004',
    genre: '旅行・観光',
    category: 'ec',
    name: '日本旅行',
    displayTitle: '日本旅行',
    prompt: {
      composition: '和のモチーフ、伝統と現代の融合',
      subject: '日本観光、神社、桜',
      colorPalette: '和（#C41E3A、#FFFFFF、#000000、#FFB7C5）',
      designElements: '鳥居、桜、富士山',
      typography: '明朝体、和のテイスト',
    },
    fullPrompt: 'A Japan travel banner with Japanese motifs, tradition and modernity fusion, Japan tourism shrine and cherry blossom imagery, Japanese color palette (crimson, white, black, cherry blossom pink), torii gate cherry blossom and Mt. Fuji elements, Mincho typography with Japanese taste, cultural and elegant mood, 1200x628 pixels',
    tags: ['日本', '和風', '桜', '文化'],
  },
  {
    id: 'travel-005',
    genre: '旅行・観光',
    category: 'ec',
    name: 'ラグジュアリートラベル',
    displayTitle: '高級旅行',
    prompt: {
      composition: '高級感のある構図、余白を活かす',
      subject: '高級ホテル、ファーストクラス、VIP',
      colorPalette: 'ラグジュアリー（#1C1C1C、#D4AF37、#FFFFFF、#8B7355）',
      designElements: 'ゴールドのアクセント、高級感のあるテクスチャ',
      typography: 'エレガントなセリフ、ゴールド',
    },
    fullPrompt: 'A luxury travel banner with premium composition using white space, luxury hotel first class and VIP imagery, luxury color palette (black, gold, white, bronze), gold accent with premium texture elements, elegant serif typography in gold, exclusive and sophisticated mood, 1200x628 pixels',
    tags: ['ラグジュアリー', '高級', 'VIP', 'エクスクルーシブ'],
  },

  // ============================================
  // 高級・ラグジュアリー（5パターン）
  // ============================================
  {
    id: 'luxury-001',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'ブラックゴールド',
    displayTitle: '黒金',
    prompt: {
      composition: 'ダーク背景にゴールドのアクセント',
      subject: '高級品、ジュエリー、時計',
      colorPalette: 'ブラックゴールド（#0D0D0D、#D4AF37、#FFFFFF）',
      designElements: 'ゴールドのライン、光沢、反射',
      typography: 'エレガントなセリフ、ゴールド',
    },
    fullPrompt: 'A black gold luxury banner with dark background and gold accents, luxury items jewelry and watches, black gold color palette (black, gold, white), gold line gloss and reflection elements, elegant serif typography in gold, opulent and prestigious mood, 1200x628 pixels',
    tags: ['ブラック', 'ゴールド', '高級', 'プレステージ'],
  },
  {
    id: 'luxury-002',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'ホワイトエレガンス',
    displayTitle: '白エレガンス',
    prompt: {
      composition: '白を基調とした上品な構図',
      subject: '白い花、パール、シルク',
      colorPalette: 'ホワイト（#FFFFFF、#F5F5F5、#C0C0C0、#E8E8E8）',
      designElements: '繊細なライン、花びら、光',
      typography: '細身のセリフ、シルバー',
    },
    fullPrompt: 'A white elegance luxury banner with white-based refined composition, white flowers pearls and silk, white color palette (white, off-white, silver, light gray), delicate lines petals and light elements, thin serif typography in silver, pure and elegant mood, 1200x628 pixels',
    tags: ['ホワイト', 'エレガンス', '上品', 'ピュア'],
  },
  {
    id: 'luxury-003',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'ディープネイビー',
    displayTitle: 'ネイビー',
    prompt: {
      composition: '深いネイビーを基調、シルバーアクセント',
      subject: '高級車、ヨット、邸宅',
      colorPalette: 'ネイビー（#0A1628、#1E3A5F、#C0C0C0、#FFFFFF）',
      designElements: 'シルバーのライン、星、月',
      typography: 'クラシックなセリフ、シルバー',
    },
    fullPrompt: 'A deep navy luxury banner with deep navy base and silver accents, luxury car yacht and mansion, navy color palette (dark navy, navy, silver, white), silver line star and moon elements, classic serif typography in silver, prestigious and timeless mood, 1200x628 pixels',
    tags: ['ネイビー', 'シルバー', 'クラシック', 'タイムレス'],
  },
  {
    id: 'luxury-004',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'ローズゴールド',
    displayTitle: 'ローズ',
    prompt: {
      composition: 'ピンクゴールドのグラデーション',
      subject: 'ジュエリー、香水、コスメ',
      colorPalette: 'ローズゴールド（#B76E79、#E8C4C4、#FFFFFF、#2D2D2D）',
      designElements: 'ローズゴールドの光沢、花びら',
      typography: 'フェミニンなセリフ、ローズゴールド',
    },
    fullPrompt: 'A rose gold luxury banner with pink gold gradient, jewelry perfume and cosmetics, rose gold color palette (rose gold, blush, white, dark gray), rose gold gloss and petal elements, feminine serif typography in rose gold, romantic and luxurious mood, 1200x628 pixels',
    tags: ['ローズゴールド', 'フェミニン', 'ロマンチック', 'ジュエリー'],
  },
  {
    id: 'luxury-005',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'マーブルテクスチャ',
    displayTitle: 'マーブル',
    prompt: {
      composition: '大理石のテクスチャを背景に',
      subject: '高級インテリア、アート、彫刻',
      colorPalette: 'マーブル（#FFFFFF、#C0C0C0、#808080、#D4AF37）',
      designElements: '大理石パターン、ゴールドの縁取り',
      typography: 'モダンなセリフ、ダークグレー',
    },
    fullPrompt: 'A marble texture luxury banner with marble texture background, luxury interior art and sculpture, marble color palette (white, silver, gray, gold), marble pattern with gold trim elements, modern serif typography in dark gray, artistic and refined mood, 1200x628 pixels',
    tags: ['マーブル', 'テクスチャ', 'アート', 'リファインド'],
  },

  // ============================================
  // ナチュラル・オーガニック（5パターン）
  // ============================================
  {
    id: 'natural-001',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'ボタニカル',
    displayTitle: 'ボタニカル',
    prompt: {
      composition: '植物で囲むフレーム構図',
      subject: '植物、ハーブ、自然素材',
      colorPalette: 'ボタニカル（#228B22、#8FBC8F、#F5F5DC、#8B4513）',
      designElements: '葉っぱ、花、蔓',
      typography: '細身のサンセリフ、グリーン',
    },
    fullPrompt: 'A botanical natural banner with plant frame composition, plants herbs and natural materials, botanical color palette (forest green, dark sea green, beige, saddle brown), leaf flower and vine elements, thin sans-serif typography in green, organic and fresh mood, 1200x628 pixels',
    tags: ['ボタニカル', '植物', 'オーガニック', 'フレッシュ'],
  },
  {
    id: 'natural-002',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'アースカラー',
    displayTitle: 'アース',
    prompt: {
      composition: '自然な質感のテクスチャ背景',
      subject: '土、木、石などの自然素材',
      colorPalette: 'アース（#8B7355、#D2B48C、#F5DEB3、#556B2F）',
      designElements: '木目、石のテクスチャ、自然光',
      typography: '温かみのあるセリフ、ブラウン',
    },
    fullPrompt: 'An earth color natural banner with natural texture background, soil wood and stone natural materials, earth color palette (brown, tan, wheat, olive), wood grain stone texture and natural light elements, warm serif typography in brown, grounded and authentic mood, 1200x628 pixels',
    tags: ['アースカラー', '自然', 'テクスチャ', 'オーセンティック'],
  },
  {
    id: 'natural-003',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'クリーンミニマル',
    displayTitle: 'ミニマル',
    prompt: {
      composition: '余白を活かしたミニマルな構図',
      subject: 'シンプルな自然素材、一輪の花',
      colorPalette: 'クリーン（#FFFFFF、#F5F5F5、#90EE90、#D3D3D3）',
      designElements: 'シンプルなライン、余白',
      typography: 'ミニマルなサンセリフ、グレー',
    },
    fullPrompt: 'A clean minimal natural banner with white space focused composition, simple natural materials and single flower, clean color palette (white, off-white, light green, light gray), simple line and white space elements, minimal sans-serif typography in gray, pure and serene mood, 1200x628 pixels',
    tags: ['クリーン', 'ミニマル', 'シンプル', 'セレーン'],
  },
  {
    id: 'natural-004',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'サステナブル',
    displayTitle: 'サステナ',
    prompt: {
      composition: 'リサイクルや環境をテーマにした構図',
      subject: 'エコ素材、リサイクル、地球',
      colorPalette: 'サステナブル（#228B22、#87CEEB、#F5F5DC、#8B4513）',
      designElements: 'リサイクルマーク、葉っぱ、地球',
      typography: 'フレンドリーなサンセリフ、グリーン',
    },
    fullPrompt: 'A sustainable natural banner with recycling and environment theme, eco materials recycling and earth, sustainable color palette (green, sky blue, beige, brown), recycle mark leaf and earth elements, friendly sans-serif typography in green, eco-conscious and hopeful mood, 1200x628 pixels',
    tags: ['サステナブル', 'エコ', '環境', 'ホープフル'],
  },
  {
    id: 'natural-005',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'ハーバルグリーン',
    displayTitle: 'ハーバル',
    prompt: {
      composition: 'ハーブや薬草を散りばめた構図',
      subject: 'ハーブ、薬草、アロマ',
      colorPalette: 'ハーバル（#6B8E23、#9ACD32、#F0FFF0、#8B4513）',
      designElements: 'ハーブのイラスト、水滴、自然光',
      typography: '手書き風フォント、オリーブ',
    },
    fullPrompt: 'A herbal green natural banner with herbs scattered composition, herbs medicinal plants and aroma, herbal color palette (olive drab, yellow green, honeydew, saddle brown), herb illustration water droplet and natural light elements, handwritten style typography in olive, healing and aromatic mood, 1200x628 pixels',
    tags: ['ハーバル', 'グリーン', 'アロマ', 'ヒーリング'],
  },

  // ============================================
  // 追加パターン（各ジャンル +5 = 合計10パターン）
  // ============================================

  // ファッション・アパレル 追加5パターン
  {
    id: 'fashion-006',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'ヴィンテージレトロ',
    displayTitle: 'ヴィンテージ',
    prompt: {
      composition: 'レトロな雰囲気のコラージュ風構図',
      subject: 'ヴィンテージ衣類、古いカメラ、レコード',
      colorPalette: 'レトロ（#D2691E、#F4A460、#FAEBD7、#8B4513）',
      designElements: 'フィルムグレイン、セピア調、古い写真風',
      typography: 'レトロセリフ、ブラウン',
    },
    fullPrompt: 'A vintage retro fashion banner with collage style composition, vintage clothing old camera and records, retro color palette (chocolate, sandy brown, antique white, saddle brown), film grain sepia tone and old photo style elements, retro serif typography in brown, nostalgic and timeless mood, 1200x628 pixels',
    tags: ['ヴィンテージ', 'レトロ', 'ノスタルジック', 'タイムレス'],
  },
  {
    id: 'fashion-007',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'ネオンナイト',
    displayTitle: 'ネオン',
    prompt: {
      composition: '夜の街をバックにしたダイナミックな構図',
      subject: 'ストリートファッション、ネオンサイン',
      colorPalette: 'ネオン（#FF00FF、#00FFFF、#000000、#FF1493）',
      designElements: 'ネオングロー、反射、都市の夜景',
      typography: 'ボールドサンセリフ、ネオンカラー',
    },
    fullPrompt: 'A neon night fashion banner with dynamic city night composition, street fashion and neon signs, neon color palette (magenta, cyan, black, deep pink), neon glow reflection and city night elements, bold sans-serif typography in neon colors, edgy and urban mood, 1200x628 pixels',
    tags: ['ネオン', 'ナイト', 'アーバン', 'エッジー'],
  },
  {
    id: 'fashion-008',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'ボヘミアンフリー',
    displayTitle: 'ボヘミアン',
    prompt: {
      composition: '自然光と植物を取り入れた自由な構図',
      subject: 'ボヘミアンドレス、アクセサリー、植物',
      colorPalette: 'ボヘミアン（#CD853F、#DEB887、#F5DEB3、#8B4513）',
      designElements: 'マクラメ、ドライフラワー、自然素材',
      typography: '手書き風フォント、アースカラー',
    },
    fullPrompt: 'A bohemian free fashion banner with natural light and plants composition, bohemian dress accessories and plants, bohemian color palette (peru, burlywood, wheat, saddle brown), macrame dried flowers and natural materials elements, handwritten typography in earth colors, free-spirited and natural mood, 1200x628 pixels',
    tags: ['ボヘミアン', 'フリースピリット', 'ナチュラル', 'アーシー'],
  },
  {
    id: 'fashion-009',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'スポーツアクティブ',
    displayTitle: 'スポーツ',
    prompt: {
      composition: 'ダイナミックな動きを捉えた構図',
      subject: 'スポーツウェア、ランニング、フィットネス',
      colorPalette: 'アクティブ（#FF4500、#32CD32、#000000、#FFFFFF）',
      designElements: 'モーションブラー、エネルギーライン',
      typography: 'アスレチックフォント、ボールド',
    },
    fullPrompt: 'A sports active fashion banner with dynamic motion composition, sportswear running and fitness, active color palette (orange red, lime green, black, white), motion blur and energy line elements, athletic bold typography, energetic and powerful mood, 1200x628 pixels',
    tags: ['スポーツ', 'アクティブ', 'エナジェティック', 'パワフル'],
  },
  {
    id: 'fashion-010',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'サマーブリーズ',
    displayTitle: 'サマー',
    prompt: {
      composition: 'ビーチや海を背景にした爽やかな構図',
      subject: 'サマードレス、サングラス、ビーチ',
      colorPalette: 'サマー（#87CEEB、#FFD700、#FFFFFF、#FF6347）',
      designElements: '波、太陽光、砂浜',
      typography: 'カジュアルサンセリフ、ブルー',
    },
    fullPrompt: 'A summer breeze fashion banner with beach and ocean background composition, summer dress sunglasses and beach, summer color palette (sky blue, gold, white, tomato), wave sunlight and sandy beach elements, casual sans-serif typography in blue, refreshing and breezy mood, 1200x628 pixels',
    tags: ['サマー', 'ビーチ', 'リフレッシング', 'ブリージー'],
  },

  // 美容・コスメ 追加5パターン
  {
    id: 'beauty-006',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'ホログラフィック',
    displayTitle: 'ホログラム',
    prompt: {
      composition: '虹色の光沢を活かした未来的構図',
      subject: 'ホログラフィックコスメ、グリッター',
      colorPalette: 'ホログラフィック（#E6E6FA、#DDA0DD、#87CEEB、#FFB6C1）',
      designElements: '虹色グラデーション、光の反射、プリズム',
      typography: 'モダンサンセリフ、シルバー',
    },
    fullPrompt: 'A holographic beauty banner with rainbow iridescent futuristic composition, holographic cosmetics and glitter, holographic color palette (lavender, plum, sky blue, light pink), rainbow gradient light reflection and prism elements, modern sans-serif typography in silver, futuristic and dreamy mood, 1200x628 pixels',
    tags: ['ホログラフィック', 'フューチャリスティック', 'ドリーミー', 'グリッター'],
  },
  {
    id: 'beauty-007',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'ジャパニーズビューティー',
    displayTitle: '和コスメ',
    prompt: {
      composition: '和の要素を取り入れた上品な構図',
      subject: '和コスメ、椿、和紙',
      colorPalette: '和風（#DC143C、#FFFFFF、#000000、#FFD700）',
      designElements: '和柄、墨絵風、金箔',
      typography: '明朝体、黒または金',
    },
    fullPrompt: 'A Japanese beauty banner with elegant Japanese elements composition, Japanese cosmetics camellia and washi paper, Japanese color palette (crimson, white, black, gold), Japanese patterns sumi-e style and gold leaf elements, Mincho typography in black or gold, elegant and traditional mood, 1200x628 pixels',
    tags: ['和風', 'ジャパニーズ', 'エレガント', 'トラディショナル'],
  },
  {
    id: 'beauty-008',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'グラムロック',
    displayTitle: 'グラム',
    prompt: {
      composition: 'ドラマチックな照明のグラマラスな構図',
      subject: 'ボールドメイク、グリッター、ジュエリー',
      colorPalette: 'グラム（#8B0000、#000000、#FFD700、#C0C0C0）',
      designElements: 'スポットライト、キラキラ、ドラマチック',
      typography: 'ボールドセリフ、ゴールド',
    },
    fullPrompt: 'A glam rock beauty banner with dramatic lighting glamorous composition, bold makeup glitter and jewelry, glam color palette (dark red, black, gold, silver), spotlight sparkle and dramatic elements, bold serif typography in gold, glamorous and bold mood, 1200x628 pixels',
    tags: ['グラム', 'ロック', 'ボールド', 'ドラマチック'],
  },
  {
    id: 'beauty-009',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'フレッシュモーニング',
    displayTitle: 'フレッシュ',
    prompt: {
      composition: '朝の光を感じる爽やかな構図',
      subject: 'スキンケア、水滴、朝日',
      colorPalette: 'フレッシュ（#ADD8E6、#FFFFFF、#98FB98、#FFE4B5）',
      designElements: '水滴、朝露、柔らかい光',
      typography: 'ライトサンセリフ、ライトブルー',
    },
    fullPrompt: 'A fresh morning beauty banner with morning light refreshing composition, skincare water droplets and sunrise, fresh color palette (light blue, white, pale green, moccasin), water droplets morning dew and soft light elements, light sans-serif typography in light blue, fresh and awakening mood, 1200x628 pixels',
    tags: ['フレッシュ', 'モーニング', 'アウェイクニング', 'クリーン'],
  },
  {
    id: 'beauty-010',
    genre: '美容・コスメ',
    category: 'beauty',
    name: 'ミッドナイトブルー',
    displayTitle: 'ミッドナイト',
    prompt: {
      composition: '深夜の神秘的な雰囲気の構図',
      subject: 'ナイトケア、月、星',
      colorPalette: 'ミッドナイト（#191970、#000080、#C0C0C0、#FFD700）',
      designElements: '星空、月光、グリッター',
      typography: 'エレガントセリフ、シルバー',
    },
    fullPrompt: 'A midnight blue beauty banner with mysterious night atmosphere composition, night care moon and stars, midnight color palette (midnight blue, navy, silver, gold), starry sky moonlight and glitter elements, elegant serif typography in silver, mysterious and luxurious mood, 1200x628 pixels',
    tags: ['ミッドナイト', 'ミステリアス', 'ラグジュアリー', 'ナイト'],
  },

  // 飲料・食品 追加5パターン
  {
    id: 'food-006',
    genre: '飲料・食品',
    category: 'ec',
    name: 'クラフトビール',
    displayTitle: 'クラフト',
    prompt: {
      composition: 'ビールの泡と琥珀色を活かした構図',
      subject: 'クラフトビール、ホップ、木樽',
      colorPalette: 'クラフト（#DAA520、#8B4513、#F5DEB3、#228B22）',
      designElements: 'ビールの泡、木目、ホップ',
      typography: 'ヴィンテージセリフ、ブラウン',
    },
    fullPrompt: 'A craft beer food banner with beer foam and amber color composition, craft beer hops and wooden barrel, craft color palette (goldenrod, saddle brown, wheat, forest green), beer foam wood grain and hops elements, vintage serif typography in brown, artisanal and authentic mood, 1200x628 pixels',
    tags: ['クラフト', 'ビール', 'アーティザナル', 'オーセンティック'],
  },
  {
    id: 'food-007',
    genre: '飲料・食品',
    category: 'ec',
    name: 'トロピカルフルーツ',
    displayTitle: 'トロピカル',
    prompt: {
      composition: 'カラフルなフルーツを散りばめた構図',
      subject: 'トロピカルフルーツ、パイナップル、マンゴー',
      colorPalette: 'トロピカル（#FF6347、#FFD700、#32CD32、#FF69B4）',
      designElements: 'フルーツカット、水しぶき、葉っぱ',
      typography: 'ファンサンセリフ、オレンジ',
    },
    fullPrompt: 'A tropical fruit food banner with colorful fruits scattered composition, tropical fruits pineapple and mango, tropical color palette (tomato, gold, lime green, hot pink), fruit cuts water splash and leaves elements, fun sans-serif typography in orange, vibrant and refreshing mood, 1200x628 pixels',
    tags: ['トロピカル', 'フルーツ', 'バイブラント', 'リフレッシング'],
  },
  {
    id: 'food-008',
    genre: '飲料・食品',
    category: 'ec',
    name: 'イタリアンキッチン',
    displayTitle: 'イタリアン',
    prompt: {
      composition: 'イタリア料理の食材を並べた構図',
      subject: 'パスタ、トマト、バジル、オリーブオイル',
      colorPalette: 'イタリアン（#DC143C、#228B22、#F5DEB3、#FFD700）',
      designElements: '木のまな板、チェック柄、ハーブ',
      typography: 'イタリックセリフ、レッド',
    },
    fullPrompt: 'An Italian kitchen food banner with Italian ingredients arranged composition, pasta tomato basil and olive oil, Italian color palette (crimson, forest green, wheat, gold), wooden cutting board checkered pattern and herbs elements, italic serif typography in red, warm and homemade mood, 1200x628 pixels',
    tags: ['イタリアン', 'パスタ', 'ウォーム', 'ホームメイド'],
  },
  {
    id: 'food-009',
    genre: '飲料・食品',
    category: 'ec',
    name: 'ヘルシースムージー',
    displayTitle: 'スムージー',
    prompt: {
      composition: 'グリーンスムージーと野菜の構図',
      subject: 'スムージー、ケール、アボカド、ベリー',
      colorPalette: 'ヘルシー（#32CD32、#9ACD32、#FF69B4、#FFFFFF）',
      designElements: 'ブレンダー、フルーツカット、グリーン',
      typography: 'モダンサンセリフ、グリーン',
    },
    fullPrompt: 'A healthy smoothie food banner with green smoothie and vegetables composition, smoothie kale avocado and berries, healthy color palette (lime green, yellow green, hot pink, white), blender fruit cuts and green elements, modern sans-serif typography in green, healthy and energetic mood, 1200x628 pixels',
    tags: ['ヘルシー', 'スムージー', 'エナジェティック', 'グリーン'],
  },
  {
    id: 'food-010',
    genre: '飲料・食品',
    category: 'ec',
    name: 'ベーカリーモーニング',
    displayTitle: 'ベーカリー',
    prompt: {
      composition: '焼きたてパンと朝食の構図',
      subject: 'クロワッサン、バゲット、コーヒー',
      colorPalette: 'ベーカリー（#D2691E、#F5DEB3、#8B4513、#FFFAF0）',
      designElements: '小麦、湯気、リネン',
      typography: 'ハンドレタリング、ブラウン',
    },
    fullPrompt: 'A bakery morning food banner with fresh baked bread and breakfast composition, croissant baguette and coffee, bakery color palette (chocolate, wheat, saddle brown, floral white), wheat steam and linen elements, hand lettering typography in brown, warm and cozy mood, 1200x628 pixels',
    tags: ['ベーカリー', 'モーニング', 'ウォーム', 'コージー'],
  },

  // IT・テクノロジー 追加5パターン
  {
    id: 'it-006',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'クラウドコンピューティング',
    displayTitle: 'クラウド',
    prompt: {
      composition: 'クラウドとネットワークの構図',
      subject: 'クラウドアイコン、サーバー、接続線',
      colorPalette: 'クラウド（#87CEEB、#FFFFFF、#4169E1、#E6E6FA）',
      designElements: 'クラウド形状、ネットワーク線、アイコン',
      typography: 'クリーンサンセリフ、ブルー',
    },
    fullPrompt: 'A cloud computing IT banner with cloud and network composition, cloud icons servers and connection lines, cloud color palette (sky blue, white, royal blue, lavender), cloud shapes network lines and icons elements, clean sans-serif typography in blue, modern and connected mood, 1200x628 pixels',
    tags: ['クラウド', 'ネットワーク', 'モダン', 'コネクテッド'],
  },
  {
    id: 'it-007',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'サイバーセキュリティ',
    displayTitle: 'セキュリティ',
    prompt: {
      composition: 'シールドと暗号化をテーマにした構図',
      subject: 'シールド、ロック、バイナリコード',
      colorPalette: 'セキュリティ（#006400、#000000、#00FF00、#FFFFFF）',
      designElements: 'シールド、鍵、マトリックス風',
      typography: 'テックフォント、グリーン',
    },
    fullPrompt: 'A cybersecurity IT banner with shield and encryption theme composition, shield lock and binary code, security color palette (dark green, black, lime, white), shield key and matrix style elements, tech font typography in green, secure and protected mood, 1200x628 pixels',
    tags: ['セキュリティ', 'サイバー', 'プロテクト', 'テック'],
  },
  {
    id: 'it-008',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'モバイルアプリ',
    displayTitle: 'モバイル',
    prompt: {
      composition: 'スマートフォンとアプリUIの構図',
      subject: 'スマートフォン、アプリアイコン、UI画面',
      colorPalette: 'モバイル（#FF6B6B、#4ECDC4、#FFFFFF、#2C3E50）',
      designElements: 'アプリアイコン、通知、フローティング',
      typography: 'モダンサンセリフ、カラフル',
    },
    fullPrompt: 'A mobile app IT banner with smartphone and app UI composition, smartphone app icons and UI screens, mobile color palette (coral, turquoise, white, dark slate), app icons notifications and floating elements, modern sans-serif typography in colorful, friendly and innovative mood, 1200x628 pixels',
    tags: ['モバイル', 'アプリ', 'フレンドリー', 'イノベーティブ'],
  },
  {
    id: 'it-009',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'ブロックチェーン',
    displayTitle: 'ブロックチェーン',
    prompt: {
      composition: 'ブロックとチェーンの連結構図',
      subject: 'ブロック、チェーン、暗号通貨',
      colorPalette: 'ブロックチェーン（#F7931A、#627EEA、#000000、#FFFFFF）',
      designElements: 'ブロック形状、チェーン、ノード',
      typography: 'ジオメトリックサンセリフ、オレンジ',
    },
    fullPrompt: 'A blockchain IT banner with blocks and chain connection composition, blocks chain and cryptocurrency, blockchain color palette (bitcoin orange, ethereum blue, black, white), block shapes chain and node elements, geometric sans-serif typography in orange, decentralized and innovative mood, 1200x628 pixels',
    tags: ['ブロックチェーン', 'クリプト', 'ディセントラライズド', 'イノベーティブ'],
  },
  {
    id: 'it-010',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'スマートホーム',
    displayTitle: 'スマートホーム',
    prompt: {
      composition: 'スマートデバイスと家の構図',
      subject: 'スマートスピーカー、照明、サーモスタット',
      colorPalette: 'スマートホーム（#4A90D9、#FFFFFF、#2ECC71、#34495E）',
      designElements: 'デバイスアイコン、接続線、家のシルエット',
      typography: 'フレンドリーサンセリフ、ブルー',
    },
    fullPrompt: 'A smart home IT banner with smart devices and home composition, smart speaker lighting and thermostat, smart home color palette (steel blue, white, emerald, wet asphalt), device icons connection lines and home silhouette elements, friendly sans-serif typography in blue, convenient and modern mood, 1200x628 pixels',
    tags: ['スマートホーム', 'IoT', 'コンビニエント', 'モダン'],
  },

  // ビジネス・SaaS 追加5パターン
  {
    id: 'business-006',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'リモートワーク',
    displayTitle: 'リモート',
    prompt: {
      composition: 'ホームオフィスとビデオ会議の構図',
      subject: 'ノートPC、ビデオ通話、コーヒー',
      colorPalette: 'リモート（#5B9BD5、#FFFFFF、#70AD47、#FFC000）',
      designElements: 'ビデオ画面、チャットバブル、植物',
      typography: 'フレンドリーサンセリフ、ブルー',
    },
    fullPrompt: 'A remote work business banner with home office and video conference composition, laptop video call and coffee, remote color palette (cornflower blue, white, olive drab, gold), video screen chat bubbles and plants elements, friendly sans-serif typography in blue, flexible and connected mood, 1200x628 pixels',
    tags: ['リモート', 'ワーク', 'フレキシブル', 'コネクテッド'],
  },
  {
    id: 'business-007',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'プロジェクト管理',
    displayTitle: 'プロジェクト',
    prompt: {
      composition: 'カンバンボードとタスクの構図',
      subject: 'カンバンボード、タスクカード、進捗バー',
      colorPalette: 'プロジェクト（#6C5CE7、#00CEC9、#FDCB6E、#FFFFFF）',
      designElements: 'カード、チェックマーク、タイムライン',
      typography: 'モダンサンセリフ、パープル',
    },
    fullPrompt: 'A project management business banner with kanban board and tasks composition, kanban board task cards and progress bars, project color palette (purple, teal, yellow, white), cards checkmarks and timeline elements, modern sans-serif typography in purple, organized and productive mood, 1200x628 pixels',
    tags: ['プロジェクト', 'マネジメント', 'オーガナイズド', 'プロダクティブ'],
  },
  {
    id: 'business-008',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'カスタマーサクセス',
    displayTitle: 'CS',
    prompt: {
      composition: '顧客満足度とサポートの構図',
      subject: 'スマイル、チャット、星評価',
      colorPalette: 'カスタマー（#00B894、#FFFFFF、#FDCB6E、#E17055）',
      designElements: '星、ハート、チャットバブル',
      typography: 'フレンドリーサンセリフ、グリーン',
    },
    fullPrompt: 'A customer success business banner with customer satisfaction and support composition, smile chat and star ratings, customer color palette (mint, white, yellow, coral), stars hearts and chat bubbles elements, friendly sans-serif typography in green, supportive and positive mood, 1200x628 pixels',
    tags: ['カスタマー', 'サクセス', 'サポーティブ', 'ポジティブ'],
  },
  {
    id: 'business-009',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'マーケティングオートメーション',
    displayTitle: 'MA',
    prompt: {
      composition: 'ファネルとオートメーションの構図',
      subject: 'ファネル、メール、ロボット',
      colorPalette: 'マーケティング（#E84393、#00CEC9、#FFFFFF、#2D3436）',
      designElements: 'ファネル形状、矢印、自動化アイコン',
      typography: 'ボールドサンセリフ、ピンク',
    },
    fullPrompt: 'A marketing automation business banner with funnel and automation composition, funnel email and robot, marketing color palette (pink, teal, white, charcoal), funnel shapes arrows and automation icons elements, bold sans-serif typography in pink, efficient and smart mood, 1200x628 pixels',
    tags: ['マーケティング', 'オートメーション', 'エフィシェント', 'スマート'],
  },
  {
    id: 'business-010',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'ファイナンスダッシュボード',
    displayTitle: 'ファイナンス',
    prompt: {
      composition: '財務グラフとダッシュボードの構図',
      subject: '円グラフ、棒グラフ、数字',
      colorPalette: 'ファイナンス（#2E86AB、#A23B72、#F18F01、#FFFFFF）',
      designElements: 'グラフ、チャート、KPI',
      typography: 'プロフェッショナルサンセリフ、ダークブルー',
    },
    fullPrompt: 'A finance dashboard business banner with financial graphs and dashboard composition, pie chart bar graph and numbers, finance color palette (cerulean, mulberry, orange, white), graphs charts and KPI elements, professional sans-serif typography in dark blue, analytical and trustworthy mood, 1200x628 pixels',
    tags: ['ファイナンス', 'ダッシュボード', 'アナリティカル', 'トラストワーシー'],
  },

  // 転職・採用・人材 追加5パターン
  {
    id: 'recruit-006',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'フレッシュスタート',
    displayTitle: 'フレッシュ',
    prompt: {
      composition: '新しい始まりを感じる明るい構図',
      subject: '若手社員、オフィス、笑顔',
      colorPalette: 'フレッシュ（#00D2D3、#FFFFFF、#FF9F43、#54A0FF）',
      designElements: '光、上昇矢印、スター',
      typography: 'エネルギッシュサンセリフ、ティール',
    },
    fullPrompt: 'A fresh start recruit banner with bright new beginning composition, young employees office and smiles, fresh color palette (cyan, white, orange, blue), light upward arrows and star elements, energetic sans-serif typography in teal, hopeful and exciting mood, 1200x628 pixels',
    tags: ['フレッシュ', 'スタート', 'ホープフル', 'エキサイティング'],
  },
  {
    id: 'recruit-007',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'エグゼクティブ',
    displayTitle: 'エグゼクティブ',
    prompt: {
      composition: 'ハイクラスな雰囲気の構図',
      subject: 'エグゼクティブ、高層ビル、スーツ',
      colorPalette: 'エグゼクティブ（#2C3E50、#BDC3C7、#E74C3C、#FFFFFF）',
      designElements: 'シャープなライン、都市景観、ゴールドアクセント',
      typography: 'エレガントセリフ、ダークグレー',
    },
    fullPrompt: 'An executive recruit banner with high-class atmosphere composition, executive skyscraper and suit, executive color palette (wet asphalt, silver, alizarin, white), sharp lines cityscape and gold accent elements, elegant serif typography in dark gray, prestigious and ambitious mood, 1200x628 pixels',
    tags: ['エグゼクティブ', 'ハイクラス', 'プレステージ', 'アンビシャス'],
  },
  {
    id: 'recruit-008',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'クリエイティブジョブ',
    displayTitle: 'クリエイティブ',
    prompt: {
      composition: 'クリエイティブな職場環境の構図',
      subject: 'デザイナー、アート、カラフルなオフィス',
      colorPalette: 'クリエイティブ（#9B59B6、#F39C12、#1ABC9C、#FFFFFF）',
      designElements: 'ペイントスプラッシュ、アートツール、カラフル',
      typography: 'プレイフルサンセリフ、パープル',
    },
    fullPrompt: 'A creative job recruit banner with creative workplace composition, designer art and colorful office, creative color palette (amethyst, orange, turquoise, white), paint splash art tools and colorful elements, playful sans-serif typography in purple, inspiring and artistic mood, 1200x628 pixels',
    tags: ['クリエイティブ', 'アート', 'インスパイアリング', 'アーティスティック'],
  },
  {
    id: 'recruit-009',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'グローバルキャリア',
    displayTitle: 'グローバル',
    prompt: {
      composition: '世界地図と国際的な雰囲気の構図',
      subject: '地球、飛行機、多国籍チーム',
      colorPalette: 'グローバル（#3498DB、#2ECC71、#FFFFFF、#34495E）',
      designElements: '世界地図、飛行機、国旗',
      typography: 'インターナショナルサンセリフ、ブルー',
    },
    fullPrompt: 'A global career recruit banner with world map and international atmosphere composition, earth airplane and multinational team, global color palette (peter river, emerald, white, wet asphalt), world map airplane and flags elements, international sans-serif typography in blue, worldly and ambitious mood, 1200x628 pixels',
    tags: ['グローバル', 'インターナショナル', 'ワールドリー', 'アンビシャス'],
  },
  {
    id: 'recruit-010',
    genre: '転職・採用・人材',
    category: 'recruit',
    name: 'ベンチャースピリット',
    displayTitle: 'ベンチャー',
    prompt: {
      composition: 'スタートアップの活気ある構図',
      subject: '若いチーム、ホワイトボード、ブレスト',
      colorPalette: 'ベンチャー（#E74C3C、#F39C12、#FFFFFF、#2C3E50）',
      designElements: 'ロケット、電球、付箋',
      typography: 'ボールドサンセリフ、レッド',
    },
    fullPrompt: 'A venture spirit recruit banner with startup energetic composition, young team whiteboard and brainstorming, venture color palette (alizarin, orange, white, wet asphalt), rocket lightbulb and sticky notes elements, bold sans-serif typography in red, passionate and innovative mood, 1200x628 pixels',
    tags: ['ベンチャー', 'スタートアップ', 'パッショネート', 'イノベーティブ'],
  },

  // 教育・学習・セミナー 追加5パターン
  {
    id: 'education-006',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'プログラミング教室',
    displayTitle: 'プログラミング',
    prompt: {
      composition: 'コードとプログラミングの構図',
      subject: 'コードエディタ、キーボード、モニター',
      colorPalette: 'プログラミング（#282C34、#61DAFB、#98C379、#E06C75）',
      designElements: 'コードスニペット、ブラケット、ターミナル',
      typography: 'モノスペースフォント、シアン',
    },
    fullPrompt: 'A programming education banner with code and programming composition, code editor keyboard and monitor, programming color palette (dark gray, react blue, green, red), code snippets brackets and terminal elements, monospace typography in cyan, technical and modern mood, 1200x628 pixels',
    tags: ['プログラミング', 'コード', 'テクニカル', 'モダン'],
  },
  {
    id: 'education-007',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: '語学学習',
    displayTitle: '語学',
    prompt: {
      composition: '多言語と会話の構図',
      subject: '吹き出し、国旗、本',
      colorPalette: '語学（#3498DB、#E74C3C、#F1C40F、#FFFFFF）',
      designElements: '吹き出し、国旗アイコン、ABC',
      typography: 'フレンドリーサンセリフ、マルチカラー',
    },
    fullPrompt: 'A language learning education banner with multilingual and conversation composition, speech bubbles flags and books, language color palette (blue, red, yellow, white), speech bubbles flag icons and ABC elements, friendly sans-serif typography in multicolor, communicative and global mood, 1200x628 pixels',
    tags: ['語学', 'ランゲージ', 'コミュニカティブ', 'グローバル'],
  },
  {
    id: 'education-008',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'ビジネススクール',
    displayTitle: 'ビジネス',
    prompt: {
      composition: 'MBAとビジネス教育の構図',
      subject: 'ケーススタディ、グラフ、プレゼン',
      colorPalette: 'ビジネス（#2C3E50、#3498DB、#F39C12、#FFFFFF）',
      designElements: 'グラフ、ブリーフケース、卒業帽',
      typography: 'プロフェッショナルセリフ、ネイビー',
    },
    fullPrompt: 'A business school education banner with MBA and business education composition, case study graphs and presentation, business color palette (wet asphalt, peter river, orange, white), graphs briefcase and graduation cap elements, professional serif typography in navy, prestigious and ambitious mood, 1200x628 pixels',
    tags: ['ビジネス', 'MBA', 'プレステージ', 'アンビシャス'],
  },
  {
    id: 'education-009',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'アート＆デザイン',
    displayTitle: 'アート',
    prompt: {
      composition: 'クリエイティブなアート教育の構図',
      subject: 'パレット、筆、キャンバス',
      colorPalette: 'アート（#9B59B6、#E74C3C、#F1C40F、#FFFFFF）',
      designElements: 'ペイントスプラッシュ、筆跡、カラフル',
      typography: 'アーティスティックフォント、パープル',
    },
    fullPrompt: 'An art and design education banner with creative art education composition, palette brush and canvas, art color palette (amethyst, alizarin, sunflower, white), paint splash brush strokes and colorful elements, artistic typography in purple, creative and expressive mood, 1200x628 pixels',
    tags: ['アート', 'デザイン', 'クリエイティブ', 'エクスプレッシブ'],
  },
  {
    id: 'education-010',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: 'サイエンスラボ',
    displayTitle: 'サイエンス',
    prompt: {
      composition: '科学実験と研究の構図',
      subject: 'フラスコ、顕微鏡、分子モデル',
      colorPalette: 'サイエンス（#1ABC9C、#3498DB、#FFFFFF、#2C3E50）',
      designElements: '化学式、分子構造、実験器具',
      typography: 'クリーンサンセリフ、ティール',
    },
    fullPrompt: 'A science lab education banner with science experiment and research composition, flask microscope and molecular model, science color palette (turquoise, peter river, white, wet asphalt), chemical formulas molecular structures and lab equipment elements, clean sans-serif typography in teal, curious and innovative mood, 1200x628 pixels',
    tags: ['サイエンス', 'ラボ', 'キュリアス', 'イノベーティブ'],
  },

  // 旅行・観光 追加5パターン
  {
    id: 'travel-006',
    genre: '旅行・観光',
    category: 'ec',
    name: 'バックパッカー',
    displayTitle: 'バックパック',
    prompt: {
      composition: '冒険と自由旅行の構図',
      subject: 'バックパック、地図、コンパス',
      colorPalette: 'バックパッカー（#27AE60、#F39C12、#8B4513、#FFFFFF）',
      designElements: '地図、足跡、テント',
      typography: 'アドベンチャーフォント、グリーン',
    },
    fullPrompt: 'A backpacker travel banner with adventure and free travel composition, backpack map and compass, backpacker color palette (nephritis, orange, saddle brown, white), map footprints and tent elements, adventure typography in green, free-spirited and adventurous mood, 1200x628 pixels',
    tags: ['バックパッカー', 'アドベンチャー', 'フリースピリット', 'アドベンチャラス'],
  },
  {
    id: 'travel-007',
    genre: '旅行・観光',
    category: 'ec',
    name: 'クルーズ船',
    displayTitle: 'クルーズ',
    prompt: {
      composition: '豪華客船と海の構図',
      subject: 'クルーズ船、海、夕日',
      colorPalette: 'クルーズ（#1E3A5F、#FFFFFF、#FFD700、#87CEEB）',
      designElements: '波、船のシルエット、夕焼け',
      typography: 'エレガントセリフ、ネイビー',
    },
    fullPrompt: 'A cruise ship travel banner with luxury liner and ocean composition, cruise ship sea and sunset, cruise color palette (navy, white, gold, sky blue), waves ship silhouette and sunset elements, elegant serif typography in navy, luxurious and relaxing mood, 1200x628 pixels',
    tags: ['クルーズ', 'ラグジュアリー', 'リラクシング', 'オーシャン'],
  },
  {
    id: 'travel-008',
    genre: '旅行・観光',
    category: 'ec',
    name: 'ウィンターリゾート',
    displayTitle: 'ウィンター',
    prompt: {
      composition: '雪山とスキーリゾートの構図',
      subject: 'スキー、雪山、ロッジ',
      colorPalette: 'ウィンター（#FFFFFF、#87CEEB、#2C3E50、#E74C3C）',
      designElements: '雪の結晶、スキー板、山のシルエット',
      typography: 'ボールドサンセリフ、ホワイト',
    },
    fullPrompt: 'A winter resort travel banner with snowy mountain and ski resort composition, skiing snow mountain and lodge, winter color palette (white, sky blue, wet asphalt, alizarin), snowflakes skis and mountain silhouette elements, bold sans-serif typography in white, exciting and refreshing mood, 1200x628 pixels',
    tags: ['ウィンター', 'スキー', 'エキサイティング', 'リフレッシング'],
  },
  {
    id: 'travel-009',
    genre: '旅行・観光',
    category: 'ec',
    name: 'グランピング',
    displayTitle: 'グランピング',
    prompt: {
      composition: '自然の中の贅沢キャンプの構図',
      subject: 'グランピングテント、焚き火、星空',
      colorPalette: 'グランピング（#2C3E50、#F39C12、#27AE60、#FFFFFF）',
      designElements: 'テント、焚き火、星',
      typography: 'ナチュラルサンセリフ、オレンジ',
    },
    fullPrompt: 'A glamping travel banner with luxury camping in nature composition, glamping tent bonfire and starry sky, glamping color palette (wet asphalt, orange, nephritis, white), tent bonfire and stars elements, natural sans-serif typography in orange, cozy and adventurous mood, 1200x628 pixels',
    tags: ['グランピング', 'キャンプ', 'コージー', 'アドベンチャラス'],
  },
  {
    id: 'travel-010',
    genre: '旅行・観光',
    category: 'ec',
    name: 'ヨーロッパ周遊',
    displayTitle: 'ヨーロッパ',
    prompt: {
      composition: 'ヨーロッパの名所を巡る構図',
      subject: 'エッフェル塔、コロッセオ、ビッグベン',
      colorPalette: 'ヨーロッパ（#3498DB、#E74C3C、#F1C40F、#FFFFFF）',
      designElements: 'ランドマーク、パスポート、スタンプ',
      typography: 'クラシックセリフ、ブルー',
    },
    fullPrompt: 'A Europe tour travel banner with European landmarks composition, Eiffel Tower Colosseum and Big Ben, Europe color palette (peter river, alizarin, sunflower, white), landmarks passport and stamps elements, classic serif typography in blue, cultural and romantic mood, 1200x628 pixels',
    tags: ['ヨーロッパ', 'ツアー', 'カルチュラル', 'ロマンティック'],
  },

  // 高級・ラグジュアリー 追加5パターン
  {
    id: 'luxury-006',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'シャンパンゴールド',
    displayTitle: 'シャンパン',
    prompt: {
      composition: 'シャンパンと祝福の構図',
      subject: 'シャンパングラス、泡、ゴールド',
      colorPalette: 'シャンパン（#F7E7CE、#FFD700、#000000、#FFFFFF）',
      designElements: '泡、グラス、ゴールドスパークル',
      typography: 'エレガントスクリプト、ゴールド',
    },
    fullPrompt: 'A champagne gold luxury banner with champagne and celebration composition, champagne glass bubbles and gold, champagne color palette (champagne, gold, black, white), bubbles glass and gold sparkle elements, elegant script typography in gold, celebratory and luxurious mood, 1200x628 pixels',
    tags: ['シャンパン', 'ゴールド', 'セレブラトリー', 'ラグジュアリー'],
  },
  {
    id: 'luxury-007',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'ベルベットレッド',
    displayTitle: 'ベルベット',
    prompt: {
      composition: 'ベルベット素材と深紅の構図',
      subject: 'ベルベット、バラ、ジュエリー',
      colorPalette: 'ベルベット（#8B0000、#000000、#FFD700、#FFFFFF）',
      designElements: 'ベルベットテクスチャ、バラの花びら、光沢',
      typography: 'ドラマチックセリフ、ゴールド',
    },
    fullPrompt: 'A velvet red luxury banner with velvet material and deep red composition, velvet roses and jewelry, velvet color palette (dark red, black, gold, white), velvet texture rose petals and shine elements, dramatic serif typography in gold, passionate and luxurious mood, 1200x628 pixels',
    tags: ['ベルベット', 'レッド', 'パッショネート', 'ラグジュアリー'],
  },
  {
    id: 'luxury-008',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'プラチナシルバー',
    displayTitle: 'プラチナ',
    prompt: {
      composition: 'プラチナの輝きを活かした構図',
      subject: 'プラチナジュエリー、ダイヤモンド、光',
      colorPalette: 'プラチナ（#E5E4E2、#C0C0C0、#000000、#FFFFFF）',
      designElements: '光の反射、ダイヤモンドカット、メタリック',
      typography: 'モダンサンセリフ、シルバー',
    },
    fullPrompt: 'A platinum silver luxury banner with platinum shine composition, platinum jewelry diamond and light, platinum color palette (platinum, silver, black, white), light reflection diamond cut and metallic elements, modern sans-serif typography in silver, sophisticated and premium mood, 1200x628 pixels',
    tags: ['プラチナ', 'シルバー', 'ソフィスティケイテッド', 'プレミアム'],
  },
  {
    id: 'luxury-009',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'アールデコ',
    displayTitle: 'アールデコ',
    prompt: {
      composition: 'アールデコ様式の幾何学的構図',
      subject: '幾何学模様、ゴールドライン、アーチ',
      colorPalette: 'アールデコ（#000000、#FFD700、#1E3A5F、#FFFFFF）',
      designElements: '幾何学パターン、ゴールドライン、サンバースト',
      typography: 'アールデコフォント、ゴールド',
    },
    fullPrompt: 'An art deco luxury banner with art deco geometric composition, geometric patterns gold lines and arches, art deco color palette (black, gold, navy, white), geometric patterns gold lines and sunburst elements, art deco typography in gold, glamorous and vintage mood, 1200x628 pixels',
    tags: ['アールデコ', 'ジオメトリック', 'グラマラス', 'ヴィンテージ'],
  },
  {
    id: 'luxury-010',
    genre: '高級・ラグジュアリー',
    category: 'beauty',
    name: 'オリエンタルラグジュアリー',
    displayTitle: 'オリエンタル',
    prompt: {
      composition: '東洋の高級感を表現した構図',
      subject: '金箔、漆、和柄',
      colorPalette: 'オリエンタル（#8B0000、#FFD700、#000000、#F5F5DC）',
      designElements: '金箔、漆塗り、和柄',
      typography: '明朝体、金または黒',
    },
    fullPrompt: 'An oriental luxury banner with Eastern luxury composition, gold leaf lacquer and Japanese patterns, oriental color palette (dark red, gold, black, beige), gold leaf lacquer and Japanese pattern elements, Mincho typography in gold or black, elegant and exotic mood, 1200x628 pixels',
    tags: ['オリエンタル', '和風', 'エレガント', 'エキゾチック'],
  },

  // ナチュラル・オーガニック 追加5パターン
  {
    id: 'natural-006',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'モーニングデュー',
    displayTitle: 'モーニング',
    prompt: {
      composition: '朝露と新鮮な植物の構図',
      subject: '朝露、葉っぱ、朝日',
      colorPalette: 'モーニング（#98FB98、#FFFFFF、#87CEEB、#F0FFF0）',
      designElements: '水滴、光、新芽',
      typography: 'ライトサンセリフ、グリーン',
    },
    fullPrompt: 'A morning dew natural banner with morning dew and fresh plants composition, morning dew leaves and sunrise, morning color palette (pale green, white, sky blue, honeydew), water droplets light and sprouts elements, light sans-serif typography in green, fresh and awakening mood, 1200x628 pixels',
    tags: ['モーニング', 'デュー', 'フレッシュ', 'アウェイクニング'],
  },
  {
    id: 'natural-007',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'フォレストバス',
    displayTitle: 'フォレスト',
    prompt: {
      composition: '森林浴をテーマにした構図',
      subject: '森、木漏れ日、苔',
      colorPalette: 'フォレスト（#228B22、#8B4513、#F5F5DC、#90EE90）',
      designElements: '木々、木漏れ日、苔',
      typography: 'オーガニックフォント、ダークグリーン',
    },
    fullPrompt: 'A forest bath natural banner with forest bathing theme composition, forest sunlight through trees and moss, forest color palette (forest green, saddle brown, beige, light green), trees sunlight and moss elements, organic typography in dark green, peaceful and healing mood, 1200x628 pixels',
    tags: ['フォレスト', 'バス', 'ピースフル', 'ヒーリング'],
  },
  {
    id: 'natural-008',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'オーシャンブリーズ',
    displayTitle: 'オーシャン',
    prompt: {
      composition: '海と自然の融合した構図',
      subject: '海、貝殻、海藻',
      colorPalette: 'オーシャン（#20B2AA、#FFFFFF、#F5DEB3、#87CEEB）',
      designElements: '波、貝殻、砂',
      typography: 'フローイングサンセリフ、ティール',
    },
    fullPrompt: 'An ocean breeze natural banner with ocean and nature fusion composition, sea shells and seaweed, ocean color palette (light sea green, white, wheat, sky blue), waves shells and sand elements, flowing sans-serif typography in teal, refreshing and natural mood, 1200x628 pixels',
    tags: ['オーシャン', 'ブリーズ', 'リフレッシング', 'ナチュラル'],
  },
  {
    id: 'natural-009',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'ハニーゴールド',
    displayTitle: 'ハニー',
    prompt: {
      composition: 'はちみつと蜂をテーマにした構図',
      subject: 'はちみつ、蜂、花',
      colorPalette: 'ハニー（#FFD700、#F5DEB3、#8B4513、#FFFFFF）',
      designElements: 'はちみつの滴り、蜂の巣、花',
      typography: 'ウォームサンセリフ、ゴールド',
    },
    fullPrompt: 'A honey gold natural banner with honey and bee theme composition, honey bee and flowers, honey color palette (gold, wheat, saddle brown, white), honey drip honeycomb and flower elements, warm sans-serif typography in gold, sweet and natural mood, 1200x628 pixels',
    tags: ['ハニー', 'ゴールド', 'スイート', 'ナチュラル'],
  },
  {
    id: 'natural-010',
    genre: 'ナチュラル・オーガニック',
    category: 'beauty',
    name: 'ラベンダーフィールド',
    displayTitle: 'ラベンダー',
    prompt: {
      composition: 'ラベンダー畑の広がる構図',
      subject: 'ラベンダー、蝶、青空',
      colorPalette: 'ラベンダー（#E6E6FA、#9370DB、#FFFFFF、#87CEEB）',
      designElements: 'ラベンダーの花、蝶、柔らかい光',
      typography: 'エレガントサンセリフ、パープル',
    },
    fullPrompt: 'A lavender field natural banner with lavender field spreading composition, lavender butterfly and blue sky, lavender color palette (lavender, medium purple, white, sky blue), lavender flowers butterfly and soft light elements, elegant sans-serif typography in purple, calming and aromatic mood, 1200x628 pixels',
    tags: ['ラベンダー', 'フィールド', 'カーミング', 'アロマティック'],
  },
  
  // ============================================
  // BtoB・比較記事・ホワイトペーパー系（カスタム追加）
  // ============================================
  {
    id: 'btob-whitepaper-001',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'ホワイトペーパー比較記事',
    displayTitle: 'ホワイトペーパー15選',
    prompt: {
      composition: '横長16:9、右〜上部に複数のWebサイト・資料・スライドUIを斜めレイヤー状に配置、左下〜中央に余白を取りタイトルテキストを大きく配置',
      subject: '架空のホワイトペーパー表紙、スライド資料、LP/WebページのUI、グラフ・図解・テキストブロック入りドキュメント、Web管理画面風ビジュアル',
      colorPalette: 'ダークトーン基調（黒〜濃いグレー #1a1a1a, #2d2d2d）、アクセントに白・薄いグレー・イエロー（#FFD700）',
      designElements: '複数UIのコラージュ構成、斜めの動き、情報量が多いが整理されたレイアウト、BtoB向けプロフェッショナル感',
      typography: 'メインタイトル「【徹底比較】ホワイトペーパー制作会社15選」を大きく白文字で、サブコピー「失敗しないためのおすすめの決め方もご紹介」を小さく、「15選」を強調',
    },
    fullPrompt: 'A professional BtoB comparison article thumbnail with dark tone background (black to dark gray), multiple website UI mockups, whitepaper covers, slide presentations, and document screens arranged diagonally in layers on the right and top area, large title text area on the left bottom with Japanese text "【徹底比較】ホワイトペーパー制作会社15選" in white, subtitle "失敗しないためのおすすめの決め方もご紹介" below, cool intellectual trustworthy design, corporate media style, digital UI focused visuals without real company logos, 1200x628 pixels',
    tags: ['BtoB', '比較記事', 'ホワイトペーパー', 'ダークトーン', 'プロフェッショナル', 'SEO記事'],
  },

  // ============================================
  // 参考画像ベースの新プロンプト（19種類）
  // ============================================
  
  // 1. 神社グルメ特集風（和風・グルメ）
  {
    id: 'reference-shrine-gourmet-001',
    genre: '飲料・食品',
    category: 'ec',
    name: '神社グルメ特集',
    displayTitle: '参拝グルメ特集',
    prompt: {
      composition: '正方形、中央に縦書き日本語タイトル、周囲に料理写真を円形配置',
      subject: '和食料理（うどん、和菓子、定食など）、神社・参拝イメージ',
      colorPalette: '和風カラー（クリーム #F5F5DC、朱色 #E63946、金 #D4AF37）',
      designElements: '和柄パターン背景、円形フレーム、縦書きタイポグラフィ',
      typography: '縦書き筆文字風、朱色アクセント、「グルメ特集」強調',
    },
    fullPrompt: 'A Japanese shrine gourmet guide banner with cream and vermillion color scheme, traditional Japanese food photos (udon, wagashi, teishoku) arranged in circular frames around center, vertical Japanese title text "参拝と一緒に楽しみたい！〇〇神宮 周辺グルメ特集" in brush calligraphy style, traditional Japanese patterns in background, warm inviting atmosphere, 1080x1080 pixels',
    tags: ['和風', 'グルメ', '神社', '観光', '縦書き'],
  },

  // 2. 冬ファッションスタイルブック風
  {
    id: 'reference-winter-fashion-001',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: 'ウィンタースタイルブック',
    displayTitle: '冬の着こなし',
    prompt: {
      composition: '縦長、複数モデルのレイヤー配置、右側に縦書きタイトル',
      subject: '冬服を着た女性モデル（ニット、マフラー、コート）',
      colorPalette: 'ニュートラルトーン（グレー、ベージュ、赤アクセント）',
      designElements: 'モデル写真の重なり、ブランド名ロゴ、シンプルなレイアウト',
      typography: '縦書き日本語「あのブランドの冬の推しの着こなし」、欧文ブランド名',
    },
    fullPrompt: 'A winter fashion style book banner with neutral gray background, multiple female models wearing winter clothes (knit sweaters, scarves, coats) in layered composition, vertical Japanese text "あのブランドの冬の推しの着こなし" on right side, brand names in small text, sophisticated fashion magazine aesthetic, muted color palette with red accent, 1080x1350 pixels',
    tags: ['ファッション', '冬', 'スタイルブック', 'モデル', 'アパレル'],
  },

  // 3. ヒップホップイベント風
  {
    id: 'reference-hiphop-event-001',
    genre: 'イベント・メディア',
    category: 'ec',
    name: 'ヒップホップパーティー',
    displayTitle: 'AFTER PARTY',
    prompt: {
      composition: '縦長、上部にロゴ、中央にアーティスト集合写真、下部に詳細情報',
      subject: 'ヒップホップアーティストグループ、ストリートファッション',
      colorPalette: 'ダークブルー基調（#0A1628）、ネオンブルー（#00D4FF）アクセント',
      designElements: 'ネオン光線、スモークエフェクト、メタリックロゴ',
      typography: 'メタリック3Dロゴ「RAPSTAR 2025」、出演者名リスト、日時情報',
    },
    fullPrompt: 'A hip-hop after party event poster with dark blue background (#0A1628), group of artists in street fashion at center, metallic 3D logo "RAPSTAR 2025 AFTER PARTY" at top, neon blue light effects and smoke, artist names listed at bottom, event date and venue info, ABEMAプレミアムで生中継 text, urban nightclub atmosphere, 1080x1350 pixels',
    tags: ['ヒップホップ', 'イベント', 'パーティー', 'ネオン', 'アーティスト'],
  },

  // 4. テーマパーク周年記念風
  {
    id: 'reference-themepark-anniversary-001',
    genre: 'イベント・メディア',
    category: 'ec',
    name: 'テーマパーク周年',
    displayTitle: 'オープン1周年',
    prompt: {
      composition: '横長、左に雑誌風レイアウト、右にキャラクター・アトラクション',
      subject: 'テーマパークのアトラクション、キャラクター、ファミリー向けビジュアル',
      colorPalette: '明るいブルー（#0066CC）、イエロー（#FFD700）、レッド（#E63946）',
      designElements: '雑誌表紙風レイアウト、吹き出し、ロゴバッジ',
      typography: '「祝！オープン1周年」大きく、キャッチコピー、週刊誌風ヘッダー',
    },
    fullPrompt: 'A theme park anniversary celebration banner with bright blue and yellow color scheme, magazine cover style layout with "WEEKLY" header, theme park attraction visuals and cartoon characters on right, large Japanese text "祝！オープン1周年" with red accent, speech bubbles with excitement text, family-friendly festive atmosphere, 1200x628 pixels',
    tags: ['テーマパーク', '周年', 'ファミリー', '雑誌風', 'エンタメ'],
  },

  // 5. お土産・ギフトガイド風
  {
    id: 'reference-gift-guide-001',
    genre: '飲料・食品',
    category: 'ec',
    name: 'ギフトガイド',
    displayTitle: '手土産図鑑',
    prompt: {
      composition: '正方形、4分割グリッド（各色異なる）、中央にタイトル',
      subject: 'スイーツ・お菓子（ロールケーキ、クッキー、和菓子）を俯瞰撮影',
      colorPalette: '4色グリッド（赤 #E63946、黄 #FFD93D、青 #4ECDC4、ピンク #FFB6C1）',
      designElements: 'カラーブロック背景、商品の俯瞰写真、エレガントなフレーム',
      typography: '中央に縦書き「とっておきの手土産図鑑」、サブタイトル小さく',
    },
    fullPrompt: 'A gift guide souvenir banner with 4-color grid background (red, yellow, teal, pink quadrants), various Japanese sweets and confectionery products photographed from above in each section, centered vertical Japanese title "とっておきの手土産図鑑 Guide to Souvenirs", elegant gift box aesthetic, premium quality feel, 1080x1080 pixels',
    tags: ['ギフト', '手土産', 'スイーツ', 'グリッド', 'プレミアム'],
  },

  // 6. お笑い番組風
  {
    id: 'reference-comedy-show-001',
    genre: 'イベント・メディア',
    category: 'ec',
    name: 'お笑い番組',
    displayTitle: 'コメディアン特番',
    prompt: {
      composition: '正方形、対角線で分割、両側にコンビ・芸人',
      subject: '笑っているお笑い芸人、スーツ姿、エンタメ感',
      colorPalette: 'ロイヤルブルー（#1E3A8A）、ゴールド（#FFD700）ストライプ',
      designElements: '斜めストライプ背景、キラキラエフェクト、番組ロゴ',
      typography: '「ザ・コメディアン2025」メタリックロゴ、配信日時、プラットフォーム名',
    },
    fullPrompt: 'A comedy TV show banner with royal blue and gold diagonal stripe background, comedians in suits laughing on both sides, metallic logo "ザ・コメディアン2025" at top, sparkle effects, broadcast date "12月30日(火)" and "プライムビデオで独占配信開始!" text, entertainment show atmosphere, 1080x1080 pixels',
    tags: ['お笑い', '番組', 'エンタメ', 'ストライプ', '配信'],
  },

  // 7. ドラマ・SNSキャンペーン風
  {
    id: 'reference-drama-campaign-001',
    genre: 'イベント・メディア',
    category: 'ec',
    name: 'ドラマキャンペーン',
    displayTitle: 'SNSキャンペーン',
    prompt: {
      composition: '正方形、上半分に人物・タイトル、下半分にキャンペーン情報',
      subject: '俳優のポートレート、モダンなファッション',
      colorPalette: 'ネイビー（#1E3A5F）、マゼンタ（#E91E8C）、ホワイト',
      designElements: 'グラデーション背景、矢印アイコン、SNS風デザイン',
      typography: '「GOOD BUY」英語ロゴ、キャンペーン詳細、フォロー促進テキスト',
    },
    fullPrompt: 'A drama SNS campaign banner with navy to magenta gradient background, actor portrait in modern fashion at top, title "スナック GOOD BUY" in stylized text, campaign info section at bottom with pink background, "フォロー＆景品をタップして応募！" call-to-action text, arrow icons, modern social media aesthetic, 1080x1350 pixels',
    tags: ['ドラマ', 'キャンペーン', 'SNS', 'プロモーション', 'グラデーション'],
  },

  // 8. ビジネス書籍要約風
  {
    id: 'reference-book-summary-001',
    genre: '教育・学習・セミナー',
    category: 'it',
    name: '書籍要約',
    displayTitle: '10分読書',
    prompt: {
      composition: '横長、左に大きな縦書きタイトル、右に本のアイコン',
      subject: '本・読書のアイコン、シンプルなイラスト',
      colorPalette: 'ライトブルーグレー（#E8F4F8）、ネイビー（#1E3A5F）、赤アクセント',
      designElements: 'ミニマルデザイン、アイコン、余白を活かしたレイアウト',
      typography: '縦書き「目標達成の技術」を大きく、「10分読書」バッジ',
    },
    fullPrompt: 'A business book summary banner with light blue-gray background (#E8F4F8), vertical Japanese text "一生使える目標達成の技術" in bold navy typography with red accent on key characters, minimalist book icon on right, "10分読書" badge in corner, clean professional educational aesthetic, plenty of whitespace, 1200x628 pixels',
    tags: ['書籍', '要約', 'ビジネス', 'ミニマル', '教育'],
  },

  // 9. プレミアムビール風
  {
    id: 'reference-premium-beer-001',
    genre: '飲料・食品',
    category: 'ec',
    name: 'プレミアムビール',
    displayTitle: 'クラフトビール',
    prompt: {
      composition: '横長、左に幾何学模様、中央にテキスト、右に商品',
      subject: 'プレミアムビール缶、グラスに注いだビール',
      colorPalette: 'ホワイト、ゴールド（#D4AF37）、ライトブルー（#87CEEB）',
      designElements: '星形幾何学模様、企業限定バッジ、高級感のある装飾',
      typography: '「Premium YEBISU」ロゴ、「WHITE SUN」商品名、キャッチコピー',
    },
    fullPrompt: 'A premium craft beer banner with white and gold color scheme, geometric star pattern on left side, "Premium YEBISU CREATIVE BREW WHITE SUN" text in center, beer can and glass product shot on right, "企業限定" badge, "スパイスが彩る爽やかなコク" tagline, elegant sophisticated design, 1200x628 pixels',
    tags: ['ビール', 'プレミアム', '限定', 'ゴールド', '高級'],
  },

  // 10. スポーツドリンク風
  {
    id: 'reference-sports-drink-001',
    genre: '飲料・食品',
    category: 'ec',
    name: 'スポーツドリンク',
    displayTitle: 'アクエリアス',
    prompt: {
      composition: '正方形、上部にロゴ、中央に商品、両サイドにアスリート',
      subject: 'スポーツドリンクボトル、スノーボーダー、オリンピック',
      colorPalette: 'ビビッドブルー（#0066FF）、ホワイト、オレンジアクセント',
      designElements: 'ダイナミックなアクションショット、オリンピックリング、躍動感',
      typography: '「AQUARIUS」ロゴ大きく、「WORLDWIDE PARTNER」、商品名',
    },
    fullPrompt: 'A sports drink Olympic partner banner with vivid blue background (#0066FF), "AQUARIUS" logo at top with Olympic rings, large sports drink bottle at center, snowboarders in action on both sides, dynamic athletic energy, "SUPERIOR HYDRATION" text, official Olympic partnership aesthetic, 1080x1080 pixels',
    tags: ['スポーツ', 'ドリンク', 'オリンピック', 'ダイナミック', 'ブルー'],
  },

  // 11. ウイスキー商品紹介風
  {
    id: 'reference-whisky-product-001',
    genre: '飲料・食品',
    category: 'ec',
    name: 'ウイスキー商品',
    displayTitle: 'プレミアムウイスキー',
    prompt: {
      composition: '横長、左にボトル、右に商品情報リスト',
      subject: 'ウイスキーボトル、グラス、琥珀色の液体',
      colorPalette: 'ダークブラウン（#3D2914）、アンバー（#FFBF00）、ブラック',
      designElements: 'スプラッシュエフェクト、箇条書き情報、QRコード',
      typography: '「NIKKA FRONTIER」ロゴ、商品スペック箇条書き、「家庭用 再発売」バッジ',
    },
    fullPrompt: 'A premium whisky product banner with dark brown to black gradient background, whisky bottle and glass with amber liquid splash on left, bullet point product specs on right (余市のヘビーピートモルト使用, 度数48%の高アルコール, モルト比率51%以上), "NIKKA FRONTIER" logo, "家庭用 再発売" red badge, sophisticated masculine aesthetic, 1200x628 pixels',
    tags: ['ウイスキー', '商品', 'プレミアム', 'ダーク', 'スペック'],
  },

  // 12. HR・インタビュー記事風
  {
    id: 'reference-hr-interview-001',
    genre: 'ビジネス・SaaS',
    category: 'it',
    name: 'HRインタビュー',
    displayTitle: 'エースの流儀',
    prompt: {
      composition: '横長、左に人物写真、右にタイトル・テキスト',
      subject: 'ビジネスパーソンのポートレート、オフィス環境',
      colorPalette: 'ティール（#20B2AA）、ダークグレー（#2D2D2D）、ホワイト',
      designElements: '斜めのカラーブロック、企業ロゴ、引用テキスト',
      typography: '「エースの流儀」大きく、会社名・人名、インスピレーショナルな引用',
    },
    fullPrompt: 'A HR interview article banner with teal and dark gray color blocks at angles, business person portrait with glasses on left side looking thoughtful, "エースの流儀 -THE ACE FACTOR-" title on right, company logos (YOUTRUST, SmartHR), inspirational quote "微かな光から兆しを見出し、正解のない道を進む。" on left, professional corporate aesthetic, 1200x628 pixels',
    tags: ['HR', 'インタビュー', 'ビジネス', 'ポートレート', 'コーポレート'],
  },

  // 13. 春ファッション・ロケーション風
  {
    id: 'reference-spring-fashion-001',
    genre: 'ファッション・アパレル',
    category: 'ec',
    name: '春ファッションロケ',
    displayTitle: '移ろう季節',
    prompt: {
      composition: '縦長、全身モデルショット、周囲に縦書きテキスト',
      subject: '春服の女性モデル、公園・自然のロケーション',
      colorPalette: 'ナチュラルグリーン、ホワイト、淡いパープル',
      designElements: '自然光、ロケーション撮影、ファッション誌風レイアウト',
      typography: '縦書き「移ろう季節、ここだけの物語を。」、ブランド名、ロケーション情報',
    },
    fullPrompt: 'A spring fashion location shoot banner with natural green park setting, female model in white skirt and blue blouse walking on stairs, vertical Japanese text "移ろう季節、ここだけの物語を。" in elegant typography, LUMINE brand logo, location credit at bottom, fashion magazine editorial aesthetic, natural lighting, 1080x1350 pixels',
    tags: ['ファッション', '春', 'ロケーション', '自然', 'エディトリアル'],
  },

  // 14. スタバ季節限定風
  {
    id: 'reference-starbucks-seasonal-001',
    genre: '飲料・食品',
    category: 'ec',
    name: 'カフェ季節限定',
    displayTitle: '季節限定ドリンク',
    prompt: {
      composition: '正方形、中央に商品、周囲に季節装飾',
      subject: 'カフェドリンク（カップ入り）、季節のデコレーション',
      colorPalette: 'クリームゴールド（#F5E6C8）、グリーン（#00704A）、レッド',
      designElements: '和柄モチーフ、キラキラエフェクト、「期間限定」バッジ',
      typography: '商品名「YUZU HONEY TEA LATTE」大きく、ブランドロゴ',
    },
    fullPrompt: 'A cafe seasonal drink banner with cream gold gradient background with Japanese pattern motifs, Starbucks cup product at center, "YUZU HONEY TEA LATTE" product name prominently displayed, "期間限定" badges, sparkle and confetti effects, festive new year atmosphere, green and gold color accents, 1080x1080 pixels',
    tags: ['カフェ', '季節限定', 'ドリンク', '和風', 'スターバックス'],
  },

  // 15. 住宅・不動産風
  {
    id: 'reference-realestate-home-001',
    genre: '住宅・不動産',
    category: 'ec',
    name: '住宅ブランド',
    displayTitle: 'ホームズ',
    prompt: {
      composition: '縦長、上部にインテリア写真、下部にブランド情報',
      subject: 'モダンなリビング・キッチン、家族のシルエット',
      colorPalette: 'ナチュラルウッド、ホワイト、ゴールドアクセント',
      designElements: '明るい室内写真、No.1バッジ、家のイラストアイコン',
      typography: '「The JOHNSON HOMES」ロゴ、「毎日の暮らし、もっと自分らしく。」コピー',
    },
    fullPrompt: 'A home builder brand banner with bright modern kitchen and living room interior photo at top, family silhouette, "The JOHNSON HOMES" elegant logo in center, "毎日の暮らし、もっと自分らしく。" tagline, "No.1" award badge, small house illustrations at bottom, natural wood and white color scheme, warm inviting family home aesthetic, 1080x1350 pixels',
    tags: ['住宅', '不動産', 'インテリア', 'ファミリー', 'ナチュラル'],
  },

  // 16. ECセール風
  {
    id: 'reference-ec-sale-001',
    genre: 'EC・セール',
    category: 'ec',
    name: 'ファッションセール',
    displayTitle: 'MAX95%OFF',
    prompt: {
      composition: '正方形、中央にモデル2人、周囲にセール情報',
      subject: 'カラフルな服を着たモデル、笑顔、ショッピング感',
      colorPalette: 'ビビッドレッド（#FF0000）、オレンジ、イエロー、グリーン',
      designElements: 'ポップなイラスト装飾、セールバッジ、CTAボタン',
      typography: '「ZOZOSALE」大きく、「MAX95%OFF」強調、「詳細はこちら」CTA',
    },
    fullPrompt: 'A fashion EC sale banner with vivid red background, two models (male and female) in colorful winter clothes smiling at center, "ZOZOSALE" large logo, "着たい！が、今トク。" tagline, "MAX95%OFF" in white box, pop art style decorations (daruma, trees, house icons), "新春WEEK 第2弾" badge, "詳細はこちら" CTA button, energetic sale atmosphere, 1080x1080 pixels',
    tags: ['セール', 'EC', 'ファッション', 'ポップ', 'カラフル'],
  },

  // 17. 新春キャンペーン風
  {
    id: 'reference-newyear-campaign-001',
    genre: 'イベント・メディア',
    category: 'ec',
    name: '新春キャンペーン',
    displayTitle: '紅白クイズ',
    prompt: {
      composition: '縦長、上部にタイトル、中央にキャンペーン内容、下部に日程',
      subject: '和風装飾、金色の背景、お正月モチーフ',
      colorPalette: '紅白（#E63946、#FFFFFF）、ゴールド（#FFD700）、和柄',
      designElements: '和柄パターン、金箔エフェクト、縁起物モチーフ',
      typography: '「紅白クイズバトル」大きく、「新春」縦書き、キャンペーン詳細',
    },
    fullPrompt: 'A new year campaign banner with red white and gold color scheme, Japanese patterns (shippo, seigaiha) in background, "紅白クイズバトル" title in bold red and white, "新春" vertical text, gold foil textures, "最大3万円のクーポンが当たる プレゼントキャンペーン" text, "2026.1.1 Thu - 1.15Thu" date, festive Japanese new year aesthetic, 1080x1350 pixels',
    tags: ['新春', 'キャンペーン', '和風', '紅白', 'クイズ'],
  },

  // 18. モバイル家族割風
  {
    id: 'reference-mobile-family-001',
    genre: '通信・サービス',
    category: 'it',
    name: 'モバイル家族割',
    displayTitle: '親子割',
    prompt: {
      composition: '縦長、上部にモデル（親子）、下部に料金プラン詳細',
      subject: '制服の学生と親、桜、家族イメージ',
      colorPalette: 'ダークネイビー（#0A1628）、桜ピンク（#FFB7C5）、ホワイト',
      designElements: '桜の花びら、料金表、ブランドロゴ',
      typography: '「ワイモバ親子割」大きく、料金「780円/月〜」強調、詳細テキスト',
    },
    fullPrompt: 'A mobile family plan banner with dark navy background and cherry blossom petals, mother and student daughter in school uniform at top, "ワイモバ「親子」割" title with arrow, "親も子も超オトク！" tagline, price "780円/月〜" prominently displayed, detailed pricing table at bottom, SoftBank and PayPay logos, "詳しく見る" CTA button, spring family campaign aesthetic, 1080x1350 pixels',
    tags: ['モバイル', '家族割', '通信', '桜', 'キャンペーン'],
  },

  // 19. ソフトウェア開発ツール風
  {
    id: 'reference-software-dev-001',
    genre: 'IT・テクノロジー',
    category: 'it',
    name: 'ソフトウェア開発',
    displayTitle: '開発自動化',
    prompt: {
      composition: '正方形、左上に人物写真、右に円形CTA、下部にロゴ',
      subject: 'ラップトップを使うビジネスパーソン、オフィス環境',
      colorPalette: 'ダークブルー（#1E3A5F）、ティール（#20B2AA）、ホワイト',
      designElements: '斜めの写真クロップ、円形ボタン、モダンなレイアウト',
      typography: '「ソフトウェア開発を自動化」キャッチコピー、「GeneXus」ロゴ、「詳細はこちら」CTA',
    },
    fullPrompt: 'A software development tool banner with dark blue gradient background, business person using laptop photo cropped at angle on left, "詳細はこちら" teal circular CTA button on right, "ソフトウェア開発を自動化" tagline in white, "GeneXus" logo at bottom, modern B2B SaaS aesthetic, clean professional design, 1080x1080 pixels',
    tags: ['ソフトウェア', '開発', 'IT', 'SaaS', 'B2B'],
  },
]

/**
 * ジャンル別にプロンプトを取得
 */
export function getPromptsByGenre(genre: string): BannerPromptV2[] {
  return BANNER_PROMPTS_V2.filter(p => p.genre === genre)
}

/**
 * カテゴリ別にプロンプトを取得
 */
export function getPromptsByCategory(category: string): BannerPromptV2[] {
  return BANNER_PROMPTS_V2.filter(p => p.category === category)
}

/**
 * 全ジャンルのリストを取得
 */
export function getAllGenres(): string[] {
  return [...new Set(BANNER_PROMPTS_V2.map(p => p.genre))]
}

/**
 * プロンプトの総数を取得
 */
export function getTotalPromptCount(): number {
  return BANNER_PROMPTS_V2.length
}
