import { ArticleTemplate, ArticleCategory } from './types'

const templates: ArticleTemplate[] = [
  // --- 入門・解説 ---
  {
    id: 'guide-1',
    title: 'ChatGPTの使い方 完全ガイド',
    patternLabel: '完全ガイド',
    description: '初心者でもわかるように、基礎から活用術まで網羅的に解説する記事',
    category: 'guide',
    icon: '📖',
    defaultKeyword: 'ChatGPT 使い方 初心者',
    defaultTitle: 'ChatGPTの使い方｜初心者でも5分で始められる完全ガイド【2026年版】',
    exampleKeywords: ['ChatGPT', '使い方', '初心者', 'AI', 'プロンプト'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    articleType: 'explanation',
  },
  {
    id: 'guide-2',
    title: '副業の始め方｜月5万円ロードマップ',
    patternLabel: 'ロードマップ',
    description: 'ゴールまでの道筋をステップで示す、実践型ロードマップ記事',
    category: 'guide',
    icon: '💰',
    defaultKeyword: '副業 始め方 会社員',
    defaultTitle: '副業の始め方｜会社員でもできる月5万円の稼ぎ方【2026年版】',
    exampleKeywords: ['副業', '会社員', '稼ぎ方', '在宅ワーク', '収入'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'howto',
  },
  {
    id: 'guide-3',
    title: 'マーケティングとは？基礎から実践',
    patternLabel: '「〇〇とは」基礎解説',
    description: '「〇〇とは？」から始まり、基礎→実践まで段階的に解説する記事',
    category: 'guide',
    icon: '📊',
    defaultKeyword: 'マーケティング とは 基礎',
    defaultTitle: 'マーケティングとは？基礎から実践まで徹底解説【入門編】',
    exampleKeywords: ['マーケティング', '基礎', '入門', '戦略', '施策'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'explanation',
  },
  {
    id: 'guide-4',
    title: 'DX推進の進め方｜成功する7ステップ',
    patternLabel: '成功Nステップ',
    description: '成功に必要なステップを番号付きで整理し、順番に解説する記事',
    category: 'guide',
    icon: '🚀',
    defaultKeyword: 'DX推進 進め方 ステップ',
    defaultTitle: '【徹底解説】DX推進の進め方｜成功企業に学ぶ7つのステップ',
    exampleKeywords: ['DX', 'デジタルトランスフォーメーション', '推進', '成功事例'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 20000,
    articleType: 'explanation',
  },

  // --- 比較・ランキング ---
  {
    id: 'compare-1',
    title: 'プロジェクト管理ツール10選比較',
    patternLabel: 'N選 徹底比較',
    description: '複数の製品・サービスを一覧で比較し、おすすめを紹介する記事',
    category: 'compare',
    icon: '⚖️',
    defaultKeyword: 'プロジェクト管理ツール 比較 おすすめ',
    defaultTitle: 'プロジェクト管理ツール10選比較｜チーム規模別おすすめ【2026年版】',
    exampleKeywords: ['プロジェクト管理', 'ツール', '比較', 'Asana', 'Notion'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'comparison',
  },
  {
    id: 'compare-2',
    title: 'AIライティングツール比較',
    patternLabel: 'VS 対決比較',
    description: '2〜3つの製品を機能・料金・品質で直接対決させる比較記事',
    category: 'compare',
    icon: '🤖',
    defaultKeyword: 'AIライティングツール 比較',
    defaultTitle: 'AIライティングツール比較｜ChatGPT vs Claude vs Gemini【2026年版】',
    exampleKeywords: ['AI', 'ライティング', 'ChatGPT', 'Claude', 'Gemini'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'comparison',
  },
  {
    id: 'compare-3',
    title: 'クラウド会計ソフト比較',
    patternLabel: '機能×料金 比較表',
    description: '機能と料金を表形式で整理し、用途別のおすすめを示す比較記事',
    category: 'compare',
    icon: '🧮',
    defaultKeyword: 'クラウド会計ソフト 比較',
    defaultTitle: 'クラウド会計ソフト比較｜freee vs マネーフォワード vs 弥生【2026年版】',
    exampleKeywords: ['会計ソフト', 'freee', 'マネーフォワード', '弥生', '比較'],
    targetAudience: 'executive',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'comparison',
  },
  {
    id: 'compare-4',
    title: 'CRMツール比較｜導入ガイド',
    patternLabel: '比較＋導入ガイド',
    description: '比較だけでなく、導入手順や選び方のポイントまで解説する記事',
    category: 'compare',
    icon: '📋',
    defaultKeyword: 'CRM ツール 比較',
    defaultTitle: 'CRMツール比較｜Salesforce vs HubSpot vs Zoho【2026年版】',
    exampleKeywords: ['CRM', 'Salesforce', 'HubSpot', 'Zoho', '顧客管理'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'comparison',
  },

  // --- HowTo・実践 ---
  {
    id: 'howto-1',
    title: 'LP制作でCVRを上げる7ステップ',
    patternLabel: '改善ステップ',
    description: '現状の課題を特定し、改善ステップを順番に解説する実践記事',
    category: 'howto',
    icon: '🎯',
    defaultKeyword: 'LP制作 手順 コンバージョン',
    defaultTitle: 'LP制作の手順｜コンバージョン率を上げる7ステップ【完全ガイド】',
    exampleKeywords: ['LP', 'ランディングページ', '制作', 'コンバージョン', 'CVR'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'howto',
  },
  {
    id: 'howto-2',
    title: 'コンテンツマーケティングの始め方',
    patternLabel: '始め方マニュアル',
    description: 'ゼロから始める人向けに、立ち上げから運営まで全手順を解説する記事',
    category: 'howto',
    icon: '✍️',
    defaultKeyword: 'コンテンツマーケティング 始め方',
    defaultTitle: 'コンテンツマーケティングの始め方｜成功するメディア運営の全手順',
    exampleKeywords: ['コンテンツマーケティング', 'オウンドメディア', '運営', '戦略'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },
  {
    id: 'howto-3',
    title: '採用ブランディング戦略',
    patternLabel: '戦略設計 完全版',
    description: '戦略の設計から実行まで、フレームワーク付きで解説する記事',
    category: 'howto',
    icon: '👥',
    defaultKeyword: '採用ブランディング 戦略',
    defaultTitle: '【完全版】採用ブランディング戦略｜応募数を5倍にする方法',
    exampleKeywords: ['採用', 'ブランディング', '応募', '人事', '戦略'],
    targetAudience: 'hr',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },
  {
    id: 'howto-4',
    title: 'ECサイトのCVR改善実践ガイド',
    patternLabel: '最適化 実践ガイド',
    description: 'データに基づく最適化手法を、具体例付きで解説する実践記事',
    category: 'howto',
    icon: '🛒',
    defaultKeyword: 'ECサイト CVR改善',
    defaultTitle: 'ECサイトのCVR改善｜売上を2倍にする最適化手法【実践編】',
    exampleKeywords: ['EC', 'CVR', 'コンバージョン', '売上', '最適化'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },

  // --- 事例・トレンド ---
  {
    id: 'case-1',
    title: 'BtoB営業成功事例10選',
    patternLabel: '成功事例 N選',
    description: '実際の成功事例を複数集め、共通する戦略やポイントを分析する記事',
    category: 'case',
    icon: '🏆',
    defaultKeyword: 'BtoB営業 成功事例',
    defaultTitle: 'BtoB営業成功事例10選｜受注率を3倍にした戦略を公開',
    exampleKeywords: ['BtoB', '営業', '成功事例', '受注率', '戦略'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'case',
  },
  {
    id: 'case-2',
    title: 'SNSマーケティング成功事例',
    patternLabel: '施策レポート',
    description: '具体的な施策とその結果をレポート形式でまとめる事例記事',
    category: 'case',
    icon: '📱',
    defaultKeyword: 'SNSマーケティング 成功事例',
    defaultTitle: 'SNSマーケティング成功事例｜フォロワー10万人達成の軌跡',
    exampleKeywords: ['SNS', 'マーケティング', '成功事例', 'Instagram', 'X'],
    targetAudience: 'marketer',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'case',
  },
  {
    id: 'case-3',
    title: '2026年注目SaaSトレンド20選',
    patternLabel: 'トレンドまとめ N選',
    description: '最新トレンドを業界別・カテゴリ別にまとめるランキング記事',
    category: 'case',
    icon: '📈',
    defaultKeyword: 'SaaS トレンド 2026',
    defaultTitle: '2026年注目のSaaSトレンド20選｜業界別まとめ【保存版】',
    exampleKeywords: ['SaaS', 'トレンド', '2026年', 'クラウド', 'ビジネス'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'ranking',
  },
  {
    id: 'case-4',
    title: 'データドリブン経営 完全ガイド',
    patternLabel: '手法解説ガイド',
    description: '専門的な手法や考え方を、導入ステップ付きで解説する記事',
    category: 'case',
    icon: '📊',
    defaultKeyword: 'データドリブン 経営 分析',
    defaultTitle: 'データドリブン経営完全ガイド｜意思決定を変える分析手法',
    exampleKeywords: ['データドリブン', '経営', '分析', 'KPI', 'BI'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'explanation',
  },
]

export const categories: ArticleCategory[] = [
  {
    id: 'guide',
    label: '入門・解説',
    emoji: '📖',
    color: 'blue',
    templates: templates.filter((t) => t.category === 'guide'),
  },
  {
    id: 'compare',
    label: '比較・ランキング',
    emoji: '⚖️',
    color: 'amber',
    templates: templates.filter((t) => t.category === 'compare'),
  },
  {
    id: 'howto',
    label: 'HowTo・実践',
    emoji: '🎯',
    color: 'emerald',
    templates: templates.filter((t) => t.category === 'howto'),
  },
  {
    id: 'case',
    label: '事例・トレンド',
    emoji: '🏆',
    color: 'purple',
    templates: templates.filter((t) => t.category === 'case'),
  },
]

export const allTemplates = templates

// 後方互換: generate-banners.ts / banners/route.ts が参照
export const articleTemplates = templates

// 後方互換: 旧 HorizontalScrollSection 用 (使われなくなったが念のため)
export const articleSections = categories.map((c) => ({
  id: c.id,
  title: c.label,
  description: '',
  templates: c.templates,
}))
