import { ArticleTemplate, ArticleSection } from './types'

// マスターデータ：記事テンプレート（30個、多様なジャンル・バリエーション）
// ドヤバナーAIと同じ形式で、各テンプレートに具体的なタイトルと画像を設定
const articleTemplates: ArticleTemplate[] = [
  // 棚①：まずはここから（8個）- 初心者向け・入門系
  { 
    id: 'intro-1', 
    title: 'ChatGPTの使い方｜初心者でも5分で始められる完全ガイド', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'ChatGPT 使い方 初心者',
    defaultTitle: 'ChatGPTの使い方｜初心者でも5分で始められる完全ガイド【2026年版】',
    description: 'ChatGPTを初めて使う人向けに、登録から活用まで丁寧に解説',
    exampleContent: 'アカウント作成手順、基本的なプロンプトの書き方、よくある質問など',
    exampleKeywords: ['ChatGPT', '使い方', '初心者', 'AI', 'プロンプト'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    // imageUrl: '/images/seo-templates/intro-1.png', // バナー生成後に有効化
  },
  { 
    id: 'intro-2', 
    title: 'Notionの始め方｜タスク管理からメモまで一元化する方法', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'Notion 始め方 使い方',
    defaultTitle: 'Notionの始め方｜タスク管理からメモまで一元化する方法',
    description: 'Notionを使った効率的な情報管理の始め方を解説',
    exampleContent: 'ワークスペースの作成、テンプレートの活用、チームでの共有方法など',
    exampleKeywords: ['Notion', 'タスク管理', 'メモ', '生産性', 'ツール'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 8000,
    // imageUrl: '/images/seo-templates/intro-2.png',
  },
  { 
    id: 'intro-3', 
    title: '副業の始め方｜会社員でもできる月5万円の稼ぎ方', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: '副業 始め方 会社員',
    defaultTitle: '副業の始め方｜会社員でもできる月5万円の稼ぎ方【2026年版】',
    description: '会社員が副業を始めるための具体的なステップを解説',
    exampleContent: '副業の種類、時間の作り方、確定申告の基礎知識など',
    exampleKeywords: ['副業', '会社員', '稼ぎ方', '在宅ワーク', '収入'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/intro-3.png',
  },
  { 
    id: 'intro-4', 
    title: 'プログラミング学習ロードマップ｜未経験から転職までの道のり', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'プログラミング 学習 ロードマップ',
    defaultTitle: 'プログラミング学習ロードマップ｜未経験から転職までの道のり',
    description: 'プログラミング未経験者が効率的に学習するためのロードマップ',
    exampleContent: '言語の選び方、学習順序、ポートフォリオの作り方など',
    exampleKeywords: ['プログラミング', '学習', '未経験', '転職', 'エンジニア'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/intro-4.png',
  },
  { 
    id: 'intro-5', 
    title: '投資信託の選び方｜初心者が失敗しない3つのポイント', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: '投資信託 選び方 初心者',
    defaultTitle: '投資信託の選び方｜初心者が失敗しない3つのポイント',
    description: '投資初心者向けに投資信託の選び方を分かりやすく解説',
    exampleContent: '手数料の見方、リスクの考え方、おすすめの銘柄など',
    exampleKeywords: ['投資信託', '選び方', '初心者', 'NISA', '資産運用'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    // imageUrl: '/images/seo-templates/intro-5.png',
  },
  { 
    id: 'intro-6', 
    title: 'Webデザインの基本｜センスがなくても作れるコツ', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'Webデザイン 基本 コツ',
    defaultTitle: 'Webデザインの基本｜センスがなくても作れるコツ【初心者向け】',
    description: 'デザイン未経験者でも実践できるWebデザインの基本を解説',
    exampleContent: '配色の基本、レイアウトのルール、フォントの選び方など',
    exampleKeywords: ['Webデザイン', '基本', '初心者', 'UI', 'UX'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    // imageUrl: '/images/seo-templates/intro-6.png',
  },
  { 
    id: 'intro-7', 
    title: 'マーケティングとは？基礎から実践まで徹底解説', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'マーケティング とは 基礎',
    defaultTitle: 'マーケティングとは？基礎から実践まで徹底解説【入門編】',
    description: 'マーケティングの基本概念から実践方法まで網羅的に解説',
    exampleContent: '4Pの考え方、ターゲティング、実際の施策例など',
    exampleKeywords: ['マーケティング', '基礎', '入門', '戦略', '施策'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/intro-7.png',
  },
  { 
    id: 'intro-8', 
    title: 'リモートワークの始め方｜在宅勤務を快適にする環境づくり', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'リモートワーク 始め方 環境',
    defaultTitle: 'リモートワークの始め方｜在宅勤務を快適にする環境づくり',
    description: 'リモートワークを快適に行うための環境構築ガイド',
    exampleContent: 'デスク環境、ツールの選び方、集中力を保つコツなど',
    exampleKeywords: ['リモートワーク', '在宅勤務', '環境', 'ツール', '生産性'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 8000,
    // imageUrl: '/images/seo-templates/intro-8.png',
  },
  
  // 棚②：比較・検討向け（8個）- ツール比較・選び方
  { 
    id: 'compare-1', 
    title: 'プロジェクト管理ツール10選比較｜チーム規模別おすすめ', 
    phase: '比較', 
    category: '比較型', 
    usage: 'ブログ向け',
    defaultKeyword: 'プロジェクト管理ツール 比較 おすすめ',
    defaultTitle: 'プロジェクト管理ツール10選比較｜チーム規模別おすすめ【2026年版】',
    description: '主要なプロジェクト管理ツールを徹底比較し、チーム規模別のおすすめを紹介',
    exampleContent: '各ツールの機能比較表、料金プラン、実際の使用感レビューなど',
    exampleKeywords: ['プロジェクト管理', 'ツール', '比較', 'Asana', 'Notion'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/compare-1.png',
  },
  { 
    id: 'compare-2', 
    title: 'クラウド会計ソフト比較｜freee vs マネーフォワード vs 弥生', 
    phase: '比較', 
    category: '比較型', 
    usage: 'ブログ向け',
    defaultKeyword: 'クラウド会計ソフト 比較',
    defaultTitle: 'クラウド会計ソフト比較｜freee vs マネーフォワード vs 弥生【2026年版】',
    description: '3大クラウド会計ソフトを機能・料金・使いやすさで徹底比較',
    exampleContent: '各ソフトの強み・弱み、料金プランの違い、業種別のおすすめなど',
    exampleKeywords: ['会計ソフト', 'freee', 'マネーフォワード', '弥生', '比較'],
    targetAudience: 'executive',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/compare-2.png',
  },
  { 
    id: 'compare-3', 
    title: '動画編集ソフトおすすめ15選｜無料・有料別に徹底比較', 
    phase: '比較', 
    category: '比較型', 
    usage: 'ブログ向け',
    defaultKeyword: '動画編集ソフト おすすめ 比較',
    defaultTitle: '動画編集ソフトおすすめ15選｜無料・有料別に徹底比較【2026年版】',
    description: '動画編集ソフトを無料・有料別に比較し、用途別のおすすめを紹介',
    exampleContent: '各ソフトの特徴、対応OS、初心者向け・プロ向けの違いなど',
    exampleKeywords: ['動画編集', 'ソフト', '無料', '有料', 'YouTube'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/compare-3.png',
  },
  { 
    id: 'compare-4', 
    title: 'オンライン英会話比較｜料金・講師・教材で選ぶベスト10', 
    phase: '比較', 
    category: '比較型', 
    usage: 'ブログ向け',
    defaultKeyword: 'オンライン英会話 比較 おすすめ',
    defaultTitle: 'オンライン英会話比較｜料金・講師・教材で選ぶベスト10',
    description: 'オンライン英会話サービスを料金・講師・教材の観点で徹底比較',
    exampleContent: '各サービスの特徴、無料体験の内容、目的別のおすすめなど',
    exampleKeywords: ['オンライン英会話', '比較', '料金', '講師', '英語学習'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/compare-4.png',
  },
  { 
    id: 'compare-5', 
    title: 'AIライティングツール比較｜ChatGPT vs Claude vs Gemini', 
    phase: '比較', 
    category: '比較型', 
    usage: 'ブログ向け',
    defaultKeyword: 'AIライティングツール 比較',
    defaultTitle: 'AIライティングツール比較｜ChatGPT vs Claude vs Gemini【2026年版】',
    description: '主要なAIライティングツールを文章品質・機能・料金で比較',
    exampleContent: '各ツールの得意分野、料金プラン、実際の出力例など',
    exampleKeywords: ['AI', 'ライティング', 'ChatGPT', 'Claude', 'Gemini'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/compare-5.png',
  },
  { 
    id: 'compare-6', 
    title: 'ノーコードツール比較｜Bubble vs Webflow vs STUDIO', 
    phase: '比較', 
    category: '比較型', 
    usage: 'ブログ向け',
    defaultKeyword: 'ノーコード ツール 比較',
    defaultTitle: 'ノーコードツール比較｜Bubble vs Webflow vs STUDIO【2026年版】',
    description: '主要なノーコードツールを機能・料金・学習コストで比較',
    exampleContent: '各ツールの特徴、作れるものの違い、日本語対応状況など',
    exampleKeywords: ['ノーコード', 'Bubble', 'Webflow', 'STUDIO', '比較'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/compare-6.png',
  },
  { 
    id: 'compare-7', 
    title: 'CRMツール比較｜Salesforce vs HubSpot vs Zoho', 
    phase: '比較', 
    category: '比較型', 
    usage: 'DL誘導向け',
    defaultKeyword: 'CRM ツール 比較',
    defaultTitle: 'CRMツール比較｜Salesforce vs HubSpot vs Zoho【2026年版】',
    description: '主要なCRMツールを機能・料金・導入のしやすさで比較',
    exampleContent: '各ツールの強み、企業規模別のおすすめ、導入事例など',
    exampleKeywords: ['CRM', 'Salesforce', 'HubSpot', 'Zoho', '顧客管理'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/compare-7.png',
  },
  { 
    id: 'compare-8', 
    title: 'Web会議ツール比較｜Zoom vs Teams vs Google Meet', 
    phase: '比較', 
    category: '比較型', 
    usage: 'ブログ向け',
    defaultKeyword: 'Web会議 ツール 比較',
    defaultTitle: 'Web会議ツール比較｜Zoom vs Teams vs Google Meet【2026年版】',
    description: '主要なWeb会議ツールを機能・料金・使いやすさで比較',
    exampleContent: '各ツールの特徴、無料プランの制限、セキュリティ面の違いなど',
    exampleKeywords: ['Web会議', 'Zoom', 'Teams', 'Google Meet', 'オンライン'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 10000,
    // imageUrl: '/images/seo-templates/compare-8.png',
  },
  
  // 棚③：構造タイプ別（7個）- 記事構成パターン
  { 
    id: 'structure-1', 
    title: '【徹底解説】DX推進の進め方｜成功企業に学ぶ7つのステップ', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'DX推進 進め方 ステップ',
    defaultTitle: '【徹底解説】DX推進の進め方｜成功企業に学ぶ7つのステップ',
    description: 'DX推進を成功させるための具体的なステップを事例とともに解説',
    exampleContent: '現状分析、ロードマップ作成、組織体制、成功事例など',
    exampleKeywords: ['DX', 'デジタルトランスフォーメーション', '推進', '成功事例', '戦略'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 20000,
    // imageUrl: '/images/seo-templates/structure-1.png',
  },
  { 
    id: 'structure-2', 
    title: 'スタートアップ資金調達チェックリスト50項目', 
    phase: '認知', 
    category: '一覧型', 
    usage: 'DL誘導向け',
    defaultKeyword: 'スタートアップ 資金調達 チェックリスト',
    defaultTitle: 'スタートアップ資金調達チェックリスト50項目【保存版】',
    description: '資金調達を成功させるために確認すべき50のポイントを一覧化',
    exampleContent: '事業計画、財務諸表、ピッチ資料、投資家対応など',
    exampleKeywords: ['スタートアップ', '資金調達', 'VC', '投資', 'チェックリスト'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 10000,
    // imageUrl: '/images/seo-templates/structure-2.png',
  },
  { 
    id: 'structure-3', 
    title: '2026年注目のSaaSトレンド20選｜業界別まとめ', 
    phase: '認知', 
    category: '一覧型', 
    usage: 'ブログ向け',
    defaultKeyword: 'SaaS トレンド 2026',
    defaultTitle: '2026年注目のSaaSトレンド20選｜業界別まとめ【保存版】',
    description: '2026年に注目すべきSaaSのトレンドを業界別にまとめて紹介',
    exampleContent: 'AI活用、業界特化型SaaS、新興サービスなど',
    exampleKeywords: ['SaaS', 'トレンド', '2026年', 'クラウド', 'ビジネス'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/structure-3.png',
  },
  { 
    id: 'structure-4', 
    title: 'LP制作の手順｜コンバージョン率を上げる7ステップ', 
    phase: '認知', 
    category: '解説型', 
    usage: 'ブログ向け',
    defaultKeyword: 'LP制作 手順 コンバージョン',
    defaultTitle: 'LP制作の手順｜コンバージョン率を上げる7ステップ【完全ガイド】',
    description: '効果的なLPを制作するための7つのステップを順を追って解説',
    exampleContent: '構成設計、コピーライティング、デザイン、A/Bテストなど',
    exampleKeywords: ['LP', 'ランディングページ', '制作', 'コンバージョン', 'CVR'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/structure-4.png',
  },
  { 
    id: 'structure-5', 
    title: 'BtoB営業成功事例10選｜受注率を3倍にした戦略', 
    phase: '認知', 
    category: '解説型', 
    usage: 'DL誘導向け',
    defaultKeyword: 'BtoB営業 成功事例',
    defaultTitle: 'BtoB営業成功事例10選｜受注率を3倍にした戦略を公開',
    description: '実際にBtoB営業で成功した企業の事例と戦略を詳しく解説',
    exampleContent: '各企業の施策内容、成果データ、成功のポイントなど',
    exampleKeywords: ['BtoB', '営業', '成功事例', '受注率', '戦略'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/structure-5.png',
  },
  { 
    id: 'structure-6', 
    title: 'マーケティングオートメーションツールランキングTOP10', 
    phase: '認知', 
    category: '一覧型', 
    usage: 'ブログ向け',
    defaultKeyword: 'MA ツール ランキング',
    defaultTitle: 'マーケティングオートメーションツールランキングTOP10【2026年版】',
    description: 'MAツールをプロが厳選してランキング形式で紹介',
    exampleContent: '各ツールの特徴、料金、使い方、おすすめポイントなど',
    exampleKeywords: ['MA', 'マーケティングオートメーション', 'ツール', 'ランキング', 'HubSpot'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/structure-6.png',
  },
  { 
    id: 'structure-7', 
    title: 'カスタマーサクセスに関するよくある質問30選', 
    phase: '認知', 
    category: '一覧型', 
    usage: 'ブログ向け',
    defaultKeyword: 'カスタマーサクセス FAQ',
    defaultTitle: 'カスタマーサクセスに関するよくある質問30選【完全解決】',
    description: 'カスタマーサクセスに関するよくある質問30個に分かりやすく回答',
    exampleContent: '基本的な質問から実践的な疑問まで幅広くカバー',
    exampleKeywords: ['カスタマーサクセス', 'FAQ', 'よくある質問', 'CS', 'SaaS'],
    targetAudience: 'marketer',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    // imageUrl: '/images/seo-templates/structure-7.png',
  },
  
  // 棚④：鉄板テンプレ（7個）- CV・リード獲得向け
  { 
    id: 'template-1', 
    title: '【完全版】採用ブランディング戦略｜応募数を5倍にする方法', 
    phase: 'CV', 
    category: '解説型', 
    usage: 'LP補助向け',
    defaultKeyword: '採用ブランディング 戦略',
    defaultTitle: '【完全版】採用ブランディング戦略｜応募数を5倍にする方法',
    description: '採用ブランディングを成功させ、応募数を増やすための戦略を解説',
    exampleContent: 'ブランド構築、発信チャネル、コンテンツ戦略、成功事例など',
    exampleKeywords: ['採用', 'ブランディング', '応募', '人事', '戦略'],
    targetAudience: 'hr',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/template-1.png',
  },
  { 
    id: 'template-2', 
    title: 'コンテンツマーケティングの始め方｜成功するメディア運営の全手順', 
    phase: 'CV', 
    category: '比較型', 
    usage: 'DL誘導向け',
    defaultKeyword: 'コンテンツマーケティング 始め方',
    defaultTitle: 'コンテンツマーケティングの始め方｜成功するメディア運営の全手順',
    description: 'コンテンツマーケティングの立ち上げから運営まで全手順を解説',
    exampleContent: '企画立案、コンテンツ制作、運用体制、KPI設定など',
    exampleKeywords: ['コンテンツマーケティング', 'オウンドメディア', '運営', '戦略', 'KPI'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/template-2.png',
  },
  { 
    id: 'template-3', 
    title: 'ビジネス文書テンプレート集｜すぐに使える書式10選', 
    phase: 'CV', 
    category: '一覧型', 
    usage: 'DL誘導向け',
    defaultKeyword: 'ビジネス文書 テンプレート',
    defaultTitle: 'ビジネス文書テンプレート集｜すぐに使える書式10選【コピペOK】',
    description: 'すぐに使えるビジネス文書のテンプレートを10種類紹介',
    exampleContent: '企画書、報告書、議事録、メールなど目的別のテンプレート',
    exampleKeywords: ['ビジネス文書', 'テンプレート', '書式', 'フォーマット', '無料'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/template-3.png',
  },
  { 
    id: 'template-4', 
    title: 'ECサイトのCVR改善｜売上を2倍にする最適化手法', 
    phase: 'CV', 
    category: '比較型', 
    usage: 'LP補助向け',
    defaultKeyword: 'ECサイト CVR改善',
    defaultTitle: 'ECサイトのCVR改善｜売上を2倍にする最適化手法【実践編】',
    description: 'ECサイトのCVRを改善し、売上を伸ばすための最適化手法を解説',
    exampleContent: 'UI/UX改善、カート離脱対策、決済最適化など',
    exampleKeywords: ['EC', 'CVR', 'コンバージョン', '売上', '最適化'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/template-4.png',
  },
  { 
    id: 'template-5', 
    title: 'データドリブン経営完全ガイド｜意思決定を変える分析手法', 
    phase: 'CV', 
    category: '解説型', 
    usage: 'DL誘導向け',
    defaultKeyword: 'データドリブン 経営 分析',
    defaultTitle: 'データドリブン経営完全ガイド｜意思決定を変える分析手法',
    description: 'データドリブン経営を実現するための分析手法と導入ステップを解説',
    exampleContent: 'KPI設計、ダッシュボード構築、分析ツール、組織体制など',
    exampleKeywords: ['データドリブン', '経営', '分析', 'KPI', 'BI'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/template-5.png',
  },
  { 
    id: 'template-6', 
    title: 'SNSマーケティング成功事例｜フォロワー10万人達成の軌跡', 
    phase: 'CV', 
    category: '一覧型', 
    usage: 'ブログ向け',
    defaultKeyword: 'SNSマーケティング 成功事例',
    defaultTitle: 'SNSマーケティング成功事例｜フォロワー10万人達成の軌跡',
    description: '実際にSNSマーケティングで成功した事例と施策を詳しく紹介',
    exampleContent: '各SNSの特性、コンテンツ戦略、エンゲージメント向上施策など',
    exampleKeywords: ['SNS', 'マーケティング', '成功事例', 'フォロワー', 'Instagram'],
    targetAudience: 'marketer',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    // imageUrl: '/images/seo-templates/template-6.png',
  },
  { 
    id: 'template-7', 
    title: 'インサイドセールス導入ガイド｜商談数を3倍にする仕組み', 
    phase: 'CV', 
    category: '比較型', 
    usage: 'DL誘導向け',
    defaultKeyword: 'インサイドセールス 導入',
    defaultTitle: 'インサイドセールス導入ガイド｜商談数を3倍にする仕組み',
    description: 'インサイドセールスを導入して商談数を増やすための仕組みを解説',
    exampleContent: '組織設計、ツール選定、KPI設計、成功事例など',
    exampleKeywords: ['インサイドセールス', '導入', '商談', 'BtoB', '営業'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    // imageUrl: '/images/seo-templates/template-7.png',
  },
]

// 棚（Section）の定義
export const articleSections: ArticleSection[] = [
  {
    id: 'intro',
    title: 'まずはここから',
    description: '初心者向け・入門系の記事テンプレート',
    templates: articleTemplates.filter(t => t.id.startsWith('intro-')),
  },
  {
    id: 'compare',
    title: '比較・検討向け',
    description: 'ツール比較・選び方の記事テンプレート',
    templates: articleTemplates.filter(t => t.id.startsWith('compare-')),
  },
  {
    id: 'structure',
    title: '構造タイプ別',
    description: '記事の構造パターン別テンプレート',
    templates: articleTemplates.filter(t => t.id.startsWith('structure-')),
  },
  {
    id: 'template',
    title: '鉄板テンプレ',
    description: 'CV・リード獲得に効果的なテンプレート',
    templates: articleTemplates.filter(t => t.id.startsWith('template-')),
  },
]

// テンプレート一覧をエクスポート（バナー生成用）
export { articleTemplates }
