import { ArticleTemplate, ArticleCategory } from './types'

const templates: ArticleTemplate[] = [
  // --- 入門・解説 ---
  {
    id: 'guide-1',
    title: 'ChatGPTの使い方 完全ガイド',
    description: '初心者向けにChatGPTの登録から活用術まで丁寧に解説',
    category: 'guide',
    icon: '📖',
    defaultKeyword: 'ChatGPT 使い方 初心者',
    defaultTitle: 'ChatGPTの使い方｜初心者でも5分で始められる完全ガイド【2026年版】',
    exampleKeywords: ['ChatGPT', '使い方', '初心者', 'AI', 'プロンプト'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    articleType: 'explanation',
  },
  {
    id: 'guide-2',
    title: '副業の始め方｜月5万円ロードマップ',
    description: '会社員でも始められる副業の具体的なステップを解説',
    category: 'guide',
    icon: '💰',
    defaultKeyword: '副業 始め方 会社員',
    defaultTitle: '副業の始め方｜会社員でもできる月5万円の稼ぎ方【2026年版】',
    exampleKeywords: ['副業', '会社員', '稼ぎ方', '在宅ワーク', '収入'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'howto',
  },
  {
    id: 'guide-3',
    title: 'マーケティングとは？基礎から実践',
    description: 'マーケティングの基本概念から実践方法まで網羅的に解説',
    category: 'guide',
    icon: '📊',
    defaultKeyword: 'マーケティング とは 基礎',
    defaultTitle: 'マーケティングとは？基礎から実践まで徹底解説【入門編】',
    exampleKeywords: ['マーケティング', '基礎', '入門', '戦略', '施策'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'explanation',
  },
  {
    id: 'guide-4',
    title: 'DX推進の進め方｜成功する7ステップ',
    description: 'DX推進を成功させるための具体的なステップを事例とともに解説',
    category: 'guide',
    icon: '🚀',
    defaultKeyword: 'DX推進 進め方 ステップ',
    defaultTitle: '【徹底解説】DX推進の進め方｜成功企業に学ぶ7つのステップ',
    exampleKeywords: ['DX', 'デジタルトランスフォーメーション', '推進', '成功事例'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 20000,
    articleType: 'explanation',
  },

  // --- 比較・ランキング ---
  {
    id: 'compare-1',
    title: 'プロジェクト管理ツール10選比較',
    description: '主要なプロジェクト管理ツールを規模別に徹底比較',
    category: 'compare',
    icon: '⚖️',
    defaultKeyword: 'プロジェクト管理ツール 比較 おすすめ',
    defaultTitle: 'プロジェクト管理ツール10選比較｜チーム規模別おすすめ【2026年版】',
    exampleKeywords: ['プロジェクト管理', 'ツール', '比較', 'Asana', 'Notion'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'comparison',
  },
  {
    id: 'compare-2',
    title: 'AIライティングツール比較',
    description: 'ChatGPT・Claude・Geminiを文章品質・機能・料金で比較',
    category: 'compare',
    icon: '🤖',
    defaultKeyword: 'AIライティングツール 比較',
    defaultTitle: 'AIライティングツール比較｜ChatGPT vs Claude vs Gemini【2026年版】',
    exampleKeywords: ['AI', 'ライティング', 'ChatGPT', 'Claude', 'Gemini'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'comparison',
  },
  {
    id: 'compare-3',
    title: 'クラウド会計ソフト比較',
    description: 'freee・マネーフォワード・弥生を機能と料金で徹底比較',
    category: 'compare',
    icon: '🧮',
    defaultKeyword: 'クラウド会計ソフト 比較',
    defaultTitle: 'クラウド会計ソフト比較｜freee vs マネーフォワード vs 弥生【2026年版】',
    exampleKeywords: ['会計ソフト', 'freee', 'マネーフォワード', '弥生', '比較'],
    targetAudience: 'executive',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'comparison',
  },
  {
    id: 'compare-4',
    title: 'CRMツール比較｜導入ガイド',
    description: 'Salesforce・HubSpot・Zohoを企業規模別におすすめ',
    category: 'compare',
    icon: '📋',
    defaultKeyword: 'CRM ツール 比較',
    defaultTitle: 'CRMツール比較｜Salesforce vs HubSpot vs Zoho【2026年版】',
    exampleKeywords: ['CRM', 'Salesforce', 'HubSpot', 'Zoho', '顧客管理'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'comparison',
  },

  // --- HowTo・実践 ---
  {
    id: 'howto-1',
    title: 'LP制作でCVRを上げる7ステップ',
    description: '効果的なLPを制作するための手順を順を追って解説',
    category: 'howto',
    icon: '🎯',
    defaultKeyword: 'LP制作 手順 コンバージョン',
    defaultTitle: 'LP制作の手順｜コンバージョン率を上げる7ステップ【完全ガイド】',
    exampleKeywords: ['LP', 'ランディングページ', '制作', 'コンバージョン', 'CVR'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'howto',
  },
  {
    id: 'howto-2',
    title: 'コンテンツマーケティングの始め方',
    description: 'オウンドメディアの立ち上げから運営まで全手順を解説',
    category: 'howto',
    icon: '✍️',
    defaultKeyword: 'コンテンツマーケティング 始め方',
    defaultTitle: 'コンテンツマーケティングの始め方｜成功するメディア運営の全手順',
    exampleKeywords: ['コンテンツマーケティング', 'オウンドメディア', '運営', '戦略'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },
  {
    id: 'howto-3',
    title: '採用ブランディング戦略',
    description: '応募数を増やすための採用ブランディング戦略を解説',
    category: 'howto',
    icon: '👥',
    defaultKeyword: '採用ブランディング 戦略',
    defaultTitle: '【完全版】採用ブランディング戦略｜応募数を5倍にする方法',
    exampleKeywords: ['採用', 'ブランディング', '応募', '人事', '戦略'],
    targetAudience: 'hr',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },
  {
    id: 'howto-4',
    title: 'ECサイトのCVR改善実践ガイド',
    description: 'ECサイトの売上を伸ばすための最適化手法を解説',
    category: 'howto',
    icon: '🛒',
    defaultKeyword: 'ECサイト CVR改善',
    defaultTitle: 'ECサイトのCVR改善｜売上を2倍にする最適化手法【実践編】',
    exampleKeywords: ['EC', 'CVR', 'コンバージョン', '売上', '最適化'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },

  // --- 事例・トレンド ---
  {
    id: 'case-1',
    title: 'BtoB営業成功事例10選',
    description: '実際にBtoB営業で成功した企業の事例と戦略を紹介',
    category: 'case',
    icon: '🏆',
    defaultKeyword: 'BtoB営業 成功事例',
    defaultTitle: 'BtoB営業成功事例10選｜受注率を3倍にした戦略を公開',
    exampleKeywords: ['BtoB', '営業', '成功事例', '受注率', '戦略'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'case',
  },
  {
    id: 'case-2',
    title: 'SNSマーケティング成功事例',
    description: 'SNSでフォロワー10万人達成の事例と施策を紹介',
    category: 'case',
    icon: '📱',
    defaultKeyword: 'SNSマーケティング 成功事例',
    defaultTitle: 'SNSマーケティング成功事例｜フォロワー10万人達成の軌跡',
    exampleKeywords: ['SNS', 'マーケティング', '成功事例', 'Instagram', 'X'],
    targetAudience: 'marketer',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'case',
  },
  {
    id: 'case-3',
    title: '2026年注目SaaSトレンド20選',
    description: '2026年に注目すべきSaaSトレンドを業界別にまとめ',
    category: 'case',
    icon: '📈',
    defaultKeyword: 'SaaS トレンド 2026',
    defaultTitle: '2026年注目のSaaSトレンド20選｜業界別まとめ【保存版】',
    exampleKeywords: ['SaaS', 'トレンド', '2026年', 'クラウド', 'ビジネス'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'ranking',
  },
  {
    id: 'case-4',
    title: 'データドリブン経営 完全ガイド',
    description: 'データに基づく意思決定の手法と導入ステップを解説',
    category: 'case',
    icon: '📊',
    defaultKeyword: 'データドリブン 経営 分析',
    defaultTitle: 'データドリブン経営完全ガイド｜意思決定を変える分析手法',
    exampleKeywords: ['データドリブン', '経営', '分析', 'KPI', 'BI'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'explanation',
  },
]

export const categories: ArticleCategory[] = [
  {
    id: 'guide',
    label: '入門・解説',
    emoji: '📖',
    color: 'blue',
    templates: templates.filter((t) => t.category === 'guide'),
  },
  {
    id: 'compare',
    label: '比較・ランキング',
    emoji: '⚖️',
    color: 'amber',
    templates: templates.filter((t) => t.category === 'compare'),
  },
  {
    id: 'howto',
    label: 'HowTo・実践',
    emoji: '🎯',
    color: 'emerald',
    templates: templates.filter((t) => t.category === 'howto'),
  },
  {
    id: 'case',
    label: '事例・トレンド',
    emoji: '🏆',
    color: 'purple',
    templates: templates.filter((t) => t.category === 'case'),
  },
]

export const allTemplates = templates

// 後方互換: generate-banners.ts / banners/route.ts が参照
export const articleTemplates = templates

// 後方互換: 旧 HorizontalScrollSection 用 (使われなくなったが念のため)
export const articleSections = categories.map((c) => ({
  id: c.id,
  title: c.label,
  description: '',
  templates: c.templates,
}))
