import type { LpDesignTheme } from './types'

export const LP_THEMES: LpDesignTheme[] = [
  {
    id: 'corporate',
    name: 'Corporate',
    description: '青系・信頼感・整然',
    industries: 'BtoB、金融、コンサル',
    colors: { primary: '#1e40af', secondary: '#1d4ed8', accent: '#3b82f6', background: '#ffffff', text: '#1e293b', muted: '#64748b' },
    fonts: { heading: 'Noto Sans JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-md',
    dividerStyle: 'straight',
    tailwindClasses: {
      hero: 'bg-gradient-to-br from-blue-900 to-blue-700 text-white',
      section: 'bg-white',
      heading: 'text-blue-900 font-bold',
      body: 'text-slate-600',
      button: 'bg-blue-700 hover:bg-blue-800 text-white rounded-md px-8 py-3 font-semibold',
      accent: 'text-blue-600',
    },
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'カラフル・遊び心',
    industries: 'クリエイティブ、メディア',
    colors: { primary: '#7c3aed', secondary: '#ec4899', accent: '#f59e0b', background: '#fafafa', text: '#1f2937', muted: '#6b7280' },
    fonts: { heading: 'Noto Sans JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-full',
    dividerStyle: 'wave',
    tailwindClasses: {
      hero: 'bg-gradient-to-br from-purple-600 via-pink-500 to-orange-400 text-white',
      section: 'bg-white',
      heading: 'text-purple-700 font-extrabold',
      body: 'text-gray-600',
      button: 'bg-gradient-to-r from-purple-600 to-pink-500 text-white rounded-full px-8 py-3 font-bold',
      accent: 'text-pink-500',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: '白基調・余白多め',
    industries: 'SaaS、テック',
    colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#6366f1', background: '#ffffff', text: '#0f172a', muted: '#94a3b8' },
    fonts: { heading: 'Noto Sans JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-lg',
    dividerStyle: 'straight',
    tailwindClasses: {
      hero: 'bg-slate-950 text-white',
      section: 'bg-white',
      heading: 'text-slate-900 font-bold tracking-tight',
      body: 'text-slate-500',
      button: 'bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg px-8 py-3 font-medium',
      accent: 'text-indigo-600',
    },
  },
  {
    id: 'bold',
    name: 'Bold',
    description: '大胆・インパクト',
    industries: 'EC、飲食、エンタメ',
    colors: { primary: '#dc2626', secondary: '#b91c1c', accent: '#fbbf24', background: '#ffffff', text: '#111827', muted: '#6b7280' },
    fonts: { heading: 'Noto Sans JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-none',
    dividerStyle: 'diagonal',
    tailwindClasses: {
      hero: 'bg-red-600 text-white',
      section: 'bg-white',
      heading: 'text-red-600 font-black uppercase tracking-wide',
      body: 'text-gray-700',
      button: 'bg-red-600 hover:bg-red-700 text-white px-8 py-4 font-black text-lg',
      accent: 'text-yellow-500',
    },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: '高級感・セリフ体',
    industries: '美容、ファッション、高価格帯',
    colors: { primary: '#78350f', secondary: '#92400e', accent: '#d97706', background: '#fffbf5', text: '#1c1917', muted: '#78716c' },
    fonts: { heading: 'Noto Serif JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-sm',
    dividerStyle: 'straight',
    tailwindClasses: {
      hero: 'bg-stone-900 text-amber-50',
      section: 'bg-amber-50',
      heading: 'text-stone-800 font-bold',
      body: 'text-stone-600',
      button: 'bg-amber-700 hover:bg-amber-800 text-white px-10 py-3 font-medium tracking-widest text-sm',
      accent: 'text-amber-600',
    },
  },
  {
    id: 'warm',
    name: 'Warm',
    description: '暖色・親しみやすい',
    industries: '教育、福祉、地域',
    colors: { primary: '#ea580c', secondary: '#d97706', accent: '#16a34a', background: '#fff7ed', text: '#1c1917', muted: '#78716c' },
    fonts: { heading: 'Noto Sans JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-xl',
    dividerStyle: 'wave',
    tailwindClasses: {
      hero: 'bg-gradient-to-br from-orange-500 to-amber-400 text-white',
      section: 'bg-orange-50',
      heading: 'text-orange-800 font-bold',
      body: 'text-stone-600',
      button: 'bg-orange-500 hover:bg-orange-600 text-white rounded-xl px-8 py-3 font-semibold',
      accent: 'text-green-600',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'ダーク背景・モダン',
    industries: 'ゲーム、IT、スタートアップ',
    colors: { primary: '#6366f1', secondary: '#8b5cf6', accent: '#06b6d4', background: '#0f172a', text: '#f1f5f9', muted: '#64748b' },
    fonts: { heading: 'Noto Sans JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-lg',
    dividerStyle: 'diagonal',
    tailwindClasses: {
      hero: 'bg-slate-950 text-white',
      section: 'bg-slate-900',
      heading: 'text-white font-bold',
      body: 'text-slate-400',
      button: 'bg-indigo-500 hover:bg-indigo-400 text-white rounded-lg px-8 py-3 font-semibold',
      accent: 'text-cyan-400',
    },
  },
  {
    id: 'medical',
    name: 'Medical',
    description: '清潔感・安心感',
    industries: '医療、ヘルスケア',
    colors: { primary: '#0284c7', secondary: '#0369a1', accent: '#10b981', background: '#f0f9ff', text: '#0c4a6e', muted: '#475569' },
    fonts: { heading: 'Noto Sans JP', body: 'Noto Sans JP' },
    buttonStyle: 'rounded-md',
    dividerStyle: 'straight',
    tailwindClasses: {
      hero: 'bg-gradient-to-br from-sky-700 to-teal-600 text-white',
      section: 'bg-sky-50',
      heading: 'text-sky-800 font-bold',
      body: 'text-slate-600',
      button: 'bg-sky-600 hover:bg-sky-700 text-white rounded-md px-8 py-3 font-semibold',
      accent: 'text-emerald-600',
    },
  },
]

export function getLpTheme(id: string): LpDesignTheme {
  return LP_THEMES.find((t) => t.id === id) ?? LP_THEMES[2]
}

export const FREE_THEME_IDS: LpDesignTheme['id'][] = ['corporate', 'minimal', 'warm']
