import { getLpTheme } from './themes'
import type { LpDesignTheme } from './types'

interface SectionData {
  type: string
  name: string
  headline?: string | null
  subheadline?: string | null
  body?: string | null
  ctaText?: string | null
  ctaUrl?: string | null
  layout?: string
  items?: Array<{ title?: string; description?: string }> | null
}

interface ExportOptions {
  projectName: string
  themeId: string
  sections: SectionData[]
}

function renderItems(items: Array<{ title?: string; description?: string }>): string {
  return `<div class="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
    ${items
      .map(
        (item) => `
      <div class="p-6 rounded-lg border border-gray-200 bg-white shadow-sm">
        <h3 class="font-bold text-lg mb-2">${item.title || ''}</h3>
        <p class="text-sm text-gray-600">${item.description || ''}</p>
      </div>`
      )
      .join('')}
  </div>`
}

function renderSection(section: SectionData, theme: LpDesignTheme, idx: number): string {
  const isHero = section.type === 'hero'
  const isCta = section.type === 'cta'
  const isFooter = section.type === 'footer'

  let bgClass = idx % 2 === 0 ? theme.tailwindClasses.section : 'bg-gray-50'
  if (isHero) bgClass = theme.tailwindClasses.hero
  if (isCta) bgClass = theme.tailwindClasses.hero
  if (isFooter) bgClass = 'bg-gray-900 text-white'

  const itemsHtml =
    section.items && section.items.length > 0 ? renderItems(section.items) : ''

  const ctaHtml = section.ctaText
    ? `<div class="mt-8 text-center">
        <a href="${section.ctaUrl || '#'}" class="${theme.tailwindClasses.button} inline-block">
          ${section.ctaText}
        </a>
      </div>`
    : ''

  return `
  <!-- ${section.name} -->
  <section class="py-16 px-4 ${bgClass}" id="section-${idx}">
    <div class="max-w-4xl mx-auto text-center">
      ${section.headline ? `<h2 class="text-3xl md:text-4xl ${theme.tailwindClasses.heading} mb-4">${section.headline}</h2>` : ''}
      ${section.subheadline ? `<p class="text-xl ${theme.tailwindClasses.accent} mb-6">${section.subheadline}</p>` : ''}
      ${section.body ? `<div class="prose prose-lg max-w-2xl mx-auto ${theme.tailwindClasses.body} text-left">${section.body.replace(/\n/g, '<br>')}</div>` : ''}
      ${itemsHtml}
      ${ctaHtml}
    </div>
  </section>`
}

export function generateHtml(opts: ExportOptions): string {
  const theme = getLpTheme(opts.themeId)
  const sectionsHtml = opts.sections.map((s, i) => renderSection(s, theme, i)).join('\n')

  return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${opts.projectName}</title>
  <meta name="description" content="${opts.projectName}">
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&family=Noto+Serif+JP:wght@400;700&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Noto Sans JP', sans-serif; }
    .prose p { margin-bottom: 1rem; }
    .prose ul { list-style: disc; padding-left: 1.5rem; margin-bottom: 1rem; }
    .prose li { margin-bottom: 0.5rem; }
  </style>
</head>
<body class="antialiased">
  <!-- Generated by ドヤLP AI - https://doya-ai.surisuta.jp -->
${sectionsHtml}
</body>
</html>`
}
