import { ArticleTemplate, ArticleSection } from './types'

// マスターデータ：記事テンプレート（16個、各棚4つずつ）
// ドヤバナーAIと同じ形式で、各テンプレートに具体的なタイトルと画像を設定
const articleTemplates: ArticleTemplate[] = [
  // 棚①：まずはここから（4個）- 初心者向け・入門系
  {
    id: 'intro-1',
    title: 'ChatGPTの使い方｜初心者でも5分で始められる完全ガイド',
    phase: '認知',
    category: '解説型',
    usage: 'ブログ向け',
    defaultKeyword: 'ChatGPT 使い方 初心者',
    defaultTitle: 'ChatGPTの使い方｜初心者でも5分で始められる完全ガイド【2026年版】',
    description: 'ChatGPTを初めて使う人向けに、登録から活用まで丁寧に解説',
    exampleContent: 'アカウント作成手順、基本的なプロンプトの書き方、よくある質問など',
    exampleKeywords: ['ChatGPT', '使い方', '初心者', 'AI', 'プロンプト'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
  },
  {
    id: 'intro-2',
    title: 'Notionの始め方｜タスク管理からメモまで一元化する方法',
    phase: '認知',
    category: '解説型',
    usage: 'ブログ向け',
    defaultKeyword: 'Notion 始め方 使い方',
    defaultTitle: 'Notionの始め方｜タスク管理からメモまで一元化する方法',
    description: 'Notionを使った効率的な情報管理の始め方を解説',
    exampleContent: 'ワークスペースの作成、テンプレートの活用、チームでの共有方法など',
    exampleKeywords: ['Notion', 'タスク管理', 'メモ', '生産性', 'ツール'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 8000,
  },
  {
    id: 'intro-3',
    title: '副業の始め方｜会社員でもできる月5万円の稼ぎ方',
    phase: '認知',
    category: '解説型',
    usage: 'ブログ向け',
    defaultKeyword: '副業 始め方 会社員',
    defaultTitle: '副業の始め方｜会社員でもできる月5万円の稼ぎ方【2026年版】',
    description: '会社員が副業を始めるための具体的なステップを解説',
    exampleContent: '副業の種類、時間の作り方、確定申告の基礎知識など',
    exampleKeywords: ['副業', '会社員', '稼ぎ方', '在宅ワーク', '収入'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
  },
  {
    id: 'intro-4',
    title: 'プログラミング学習ロードマップ｜未経験から転職までの道のり',
    phase: '認知',
    category: '解説型',
    usage: 'ブログ向け',
    defaultKeyword: 'プログラミング 学習 ロードマップ',
    defaultTitle: 'プログラミング学習ロードマップ｜未経験から転職までの道のり',
    description: 'プログラミング未経験者が効率的に学習するためのロードマップ',
    exampleContent: '言語の選び方、学習順序、ポートフォリオの作り方など',
    exampleKeywords: ['プログラミング', '学習', '未経験', '転職', 'エンジニア'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 15000,
  },

  // 棚②：比較・検討向け（4個）- ツール比較・選び方
  {
    id: 'compare-1',
    title: 'プロジェクト管理ツール10選比較｜チーム規模別おすすめ',
    phase: '比較',
    category: '比較型',
    usage: 'ブログ向け',
    defaultKeyword: 'プロジェクト管理ツール 比較 おすすめ',
    defaultTitle: 'プロジェクト管理ツール10選比較｜チーム規模別おすすめ【2026年版】',
    description: '主要なプロジェクト管理ツールを徹底比較し、チーム規模別のおすすめを紹介',
    exampleContent: '各ツールの機能比較表、料金プラン、実際の使用感レビューなど',
    exampleKeywords: ['プロジェクト管理', 'ツール', '比較', 'Asana', 'Notion'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
  },
  {
    id: 'compare-2',
    title: 'クラウド会計ソフト比較｜freee vs マネーフォワード vs 弥生',
    phase: '比較',
    category: '比較型',
    usage: 'ブログ向け',
    defaultKeyword: 'クラウド会計ソフト 比較',
    defaultTitle: 'クラウド会計ソフト比較｜freee vs マネーフォワード vs 弥生【2026年版】',
    description: '3大クラウド会計ソフトを機能・料金・使いやすさで徹底比較',
    exampleContent: '各ソフトの強み・弱み、料金プランの違い、業種別のおすすめなど',
    exampleKeywords: ['会計ソフト', 'freee', 'マネーフォワード', '弥生', '比較'],
    targetAudience: 'executive',
    recommendedTone: 'logical',
    recommendedChars: 12000,
  },
  {
    id: 'compare-3',
    title: 'AIライティングツール比較｜ChatGPT vs Claude vs Gemini',
    phase: '比較',
    category: '比較型',
    usage: 'ブログ向け',
    defaultKeyword: 'AIライティングツール 比較',
    defaultTitle: 'AIライティングツール比較｜ChatGPT vs Claude vs Gemini【2026年版】',
    description: '主要なAIライティングツールを文章品質・機能・料金で比較',
    exampleContent: '各ツールの得意分野、料金プラン、実際の出力例など',
    exampleKeywords: ['AI', 'ライティング', 'ChatGPT', 'Claude', 'Gemini'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
  },
  {
    id: 'compare-4',
    title: 'ノーコードツール比較｜Bubble vs Webflow vs STUDIO',
    phase: '比較',
    category: '比較型',
    usage: 'ブログ向け',
    defaultKeyword: 'ノーコード ツール 比較',
    defaultTitle: 'ノーコードツール比較｜Bubble vs Webflow vs STUDIO【2026年版】',
    description: '主要なノーコードツールを機能・料金・学習コストで比較',
    exampleContent: '各ツールの特徴、作れるものの違い、日本語対応状況など',
    exampleKeywords: ['ノーコード', 'Bubble', 'Webflow', 'STUDIO', '比較'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
  },

  // 棚③：構造タイプ別（4個）- 記事構成パターン
  {
    id: 'structure-1',
    title: '【徹底解説】DX推進の進め方｜成功企業に学ぶ7つのステップ',
    phase: '認知',
    category: '解説型',
    usage: 'ブログ向け',
    defaultKeyword: 'DX推進 進め方 ステップ',
    defaultTitle: '【徹底解説】DX推進の進め方｜成功企業に学ぶ7つのステップ',
    description: 'DX推進を成功させるための具体的なステップを事例とともに解説',
    exampleContent: '現状分析、ロードマップ作成、組織体制、成功事例など',
    exampleKeywords: ['DX', 'デジタルトランスフォーメーション', '推進', '成功事例', '戦略'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 20000,
  },
  {
    id: 'structure-2',
    title: 'スタートアップ資金調達チェックリスト50項目',
    phase: '認知',
    category: '一覧型',
    usage: 'DL誘導向け',
    defaultKeyword: 'スタートアップ 資金調達 チェックリスト',
    defaultTitle: 'スタートアップ資金調達チェックリスト50項目【保存版】',
    description: '資金調達を成功させるために確認すべき50のポイントを一覧化',
    exampleContent: '事業計画、財務諸表、ピッチ資料、投資家対応など',
    exampleKeywords: ['スタートアップ', '資金調達', 'VC', '投資', 'チェックリスト'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 10000,
  },
  {
    id: 'structure-3',
    title: '2026年注目のSaaSトレンド20選｜業界別まとめ',
    phase: '認知',
    category: '一覧型',
    usage: 'ブログ向け',
    defaultKeyword: 'SaaS トレンド 2026',
    defaultTitle: '2026年注目のSaaSトレンド20選｜業界別まとめ【保存版】',
    description: '2026年に注目すべきSaaSのトレンドを業界別にまとめて紹介',
    exampleContent: 'AI活用、業界特化型SaaS、新興サービスなど',
    exampleKeywords: ['SaaS', 'トレンド', '2026年', 'クラウド', 'ビジネス'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
  },
  {
    id: 'structure-4',
    title: 'LP制作の手順｜コンバージョン率を上げる7ステップ',
    phase: '認知',
    category: '解説型',
    usage: 'ブログ向け',
    defaultKeyword: 'LP制作 手順 コンバージョン',
    defaultTitle: 'LP制作の手順｜コンバージョン率を上げる7ステップ【完全ガイド】',
    description: '効果的なLPを制作するための7つのステップを順を追って解説',
    exampleContent: '構成設計、コピーライティング、デザイン、A/Bテストなど',
    exampleKeywords: ['LP', 'ランディングページ', '制作', 'コンバージョン', 'CVR'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
  },

  // 棚④：鉄板テンプレ（4個）- CV・リード獲得向け
  {
    id: 'template-1',
    title: '【完全版】採用ブランディング戦略｜応募数を5倍にする方法',
    phase: 'CV',
    category: '解説型',
    usage: 'LP補助向け',
    defaultKeyword: '採用ブランディング 戦略',
    defaultTitle: '【完全版】採用ブランディング戦略｜応募数を5倍にする方法',
    description: '採用ブランディングを成功させ、応募数を増やすための戦略を解説',
    exampleContent: 'ブランド構築、発信チャネル、コンテンツ戦略、成功事例など',
    exampleKeywords: ['採用', 'ブランディング', '応募', '人事', '戦略'],
    targetAudience: 'hr',
    recommendedTone: 'professional',
    recommendedChars: 15000,
  },
  {
    id: 'template-2',
    title: 'コンテンツマーケティングの始め方｜成功するメディア運営の全手順',
    phase: 'CV',
    category: '比較型',
    usage: 'DL誘導向け',
    defaultKeyword: 'コンテンツマーケティング 始め方',
    defaultTitle: 'コンテンツマーケティングの始め方｜成功するメディア運営の全手順',
    description: 'コンテンツマーケティングの立ち上げから運営まで全手順を解説',
    exampleContent: '企画立案、コンテンツ制作、運用体制、KPI設定など',
    exampleKeywords: ['コンテンツマーケティング', 'オウンドメディア', '運営', '戦略', 'KPI'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
  },
  {
    id: 'template-3',
    title: 'ECサイトのCVR改善｜売上を2倍にする最適化手法',
    phase: 'CV',
    category: '比較型',
    usage: 'LP補助向け',
    defaultKeyword: 'ECサイト CVR改善',
    defaultTitle: 'ECサイトのCVR改善｜売上を2倍にする最適化手法【実践編】',
    description: 'ECサイトのCVRを改善し、売上を伸ばすための最適化手法を解説',
    exampleContent: 'UI/UX改善、カート離脱対策、決済最適化など',
    exampleKeywords: ['EC', 'CVR', 'コンバージョン', '売上', '最適化'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
  },
  {
    id: 'template-4',
    title: 'SNSマーケティング成功事例｜フォロワー10万人達成の軌跡',
    phase: 'CV',
    category: '一覧型',
    usage: 'ブログ向け',
    defaultKeyword: 'SNSマーケティング 成功事例',
    defaultTitle: 'SNSマーケティング成功事例｜フォロワー10万人達成の軌跡',
    description: '実際にSNSマーケティングで成功した事例と施策を詳しく紹介',
    exampleContent: '各SNSの特性、コンテンツ戦略、エンゲージメント向上施策など',
    exampleKeywords: ['SNS', 'マーケティング', '成功事例', 'フォロワー', 'Instagram'],
    targetAudience: 'marketer',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
  },
]

/**
 * テンプレートにv2バナー画像URLを追加
 * NanoBanana Pro v2で生成された専用画像を使用（未生成の場合は自動でフォールバック）
 */
function getImageUrl(template: ArticleTemplate): string {
  // テンプレートID専用のAPIを使用
  return `/api/seo/test/image/template/${template.id}`
}

// 画像URL付きのテンプレート一覧
const templatesWithImages: ArticleTemplate[] = articleTemplates.map((t) => ({
  ...t,
  imageUrl: getImageUrl(t),
}))

// 棚（Section）の定義
export const articleSections: ArticleSection[] = [
  {
    id: 'intro',
    title: 'まずはここから',
    description: '初心者向け・入門系の記事テンプレート',
    templates: templatesWithImages.filter(t => t.id.startsWith('intro-')),
  },
  {
    id: 'compare',
    title: '比較・検討向け',
    description: 'ツール比較・選び方の記事テンプレート',
    templates: templatesWithImages.filter(t => t.id.startsWith('compare-')),
  },
  {
    id: 'structure',
    title: '構造タイプ別',
    description: '記事の構造パターン別テンプレート',
    templates: templatesWithImages.filter(t => t.id.startsWith('structure-')),
  },
  {
    id: 'template',
    title: '鉄板テンプレ',
    description: 'CV・リード獲得に効果的なテンプレート',
    templates: templatesWithImages.filter(t => t.id.startsWith('template-')),
  },
]

// テンプレート一覧をエクスポート（バナー生成用）
export { templatesWithImages as articleTemplates }
