const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer-core');
const root=path.resolve(__dirname,process.env.AUDIT_PHASE||'before');fs.mkdirSync(root,{recursive:true});
const base=process.env.DOYA_QA_URL||'https://doya-ai.surisuta.jp';
const ids=['top','banner','seo','interview','persona','hr','kintai','doyalist','promane','doyaslide','cunning','sfa','shodan','aio','mensetsu','quote','aishodan','adimage'];
(async()=>{const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const results=[];let cursor=0;
await Promise.all(Array.from({length:3},async()=>{const page=await browser.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
while(cursor<ids.length){const id=ids[cursor++];errors=[];try {await page.setViewport({width:1440,height:1000});const response=await page.goto(base+(id==='top'?'/':'/'+id),{waitUntil:'networkidle2',timeout:60000});await page.evaluate(()=>Promise.race([document.fonts.ready,new Promise(r=>setTimeout(r,3000))]));await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);
await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=800){scrollTo(0,y);await new Promise(r=>setTimeout(r,40))}scrollTo(0,0)});await page.evaluate(()=>Promise.race([Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))),new Promise(r=>setTimeout(r,4000))]));
const data={id,status:response.status(),url:page.url(),errors,viewports:[],axe:[]};
await page.addScriptTag({path:require.resolve('axe-core')});
for(const width of [1440,1024,768,390,320]){await page.setViewport({width,height:1000});await new Promise(r=>setTimeout(r,120));const d=await page.evaluate(()=>{const root=document.querySelector('.doya-renewal');const visible=e=>e.checkVisibility()&&e.getBoundingClientRect().width&&e.getBoundingClientRect().height&&getComputedStyle(e).visibility!=='hidden';return {width:innerWidth,pageWidth:document.documentElement.scrollWidth,h1:[...document.querySelectorAll('h1')].map(e=>e.innerText),literalNewlines:root.innerText.includes('\\n'),clipped:[...root.querySelectorAll('h1,h2,h3,p,a,button,summary')].filter(visible).filter(e=>!e.closest('[data-mock-window]')&&!e.classList.contains('doya-skip-link')&&e.scrollWidth>e.clientWidth+3).map(e=>({tag:e.tagName,cls:e.className,text:e.innerText.slice(0,85),scroll:e.scrollWidth,width:e.clientWidth})),outside:[...root.querySelectorAll('h1,h2,h3,a,button')].filter(visible).filter(e=>!e.closest('[data-mock-window]')&&!e.classList.contains('doya-skip-link')).filter(e=>{const r=e.getBoundingClientRect();return r.left< -2||r.right>innerWidth+2}).map(e=>({text:e.innerText.slice(0,60),cls:e.className})),brokenImages:[...root.querySelectorAll('img')].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src),missingAnchors:[...root.querySelectorAll('a[href^="#"]')].filter(a=>!document.getElementById(a.hash.slice(1))).map(a=>a.getAttribute('href')),headerLinks:[...root.querySelectorAll('header a')].filter(visible).map(a=>a.innerText),sections:[...root.querySelectorAll('main>section')].map(s=>({h:s.querySelector('h2')?.innerText,cls:s.className,height:Math.round(s.getBoundingClientRect().height)}))};});data.viewports.push(d);
if(width===1440||width===320){const violations=await page.evaluate(async()=>{const a=await axe.run('.doya-renewal',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({html:n.html,target:n.target,summary:n.failureSummary})).slice(0,30)}))});data.axe.push(...violations.map(v=>({...v,width})));}
if(width===1440||width===390){await page.screenshot({path:path.join(root,`${id}-${width}-hero.png`)});if(['top','banner','aio','adimage','cunning','promane'].includes(id))await page.screenshot({path:path.join(root,`${id}-${width}-full.png`),fullPage:true});}}
data.links=await page.$$eval('.doya-renewal a',els=>[...new Set(els.map(e=>e.href))]);data.text=await page.$eval('.doya-renewal',e=>e.innerText);results.push(data);fs.writeFileSync(path.join(root,`${id}.json`),JSON.stringify(data,null,2));console.log(id,JSON.stringify({clipped:data.viewports.reduce((n,v)=>n+v.clipped.length,0),outside:data.viewports.reduce((n,v)=>n+v.outside.length,0),axe:data.axe.map(a=>a.id),errors}));}catch(e){results.push({id,error:e.message});console.log(id,e.message)}}await page.close()}));
fs.writeFileSync(path.join(root,'audit.json'),JSON.stringify({base,checkedAt:new Date().toISOString(),results},null,2));await browser.close();process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
