import { ArticleTemplate, ArticleCategory } from './types'

const templates: ArticleTemplate[] = [
  // --- 入門・解説 ---
  {
    id: 'guide-1',
    title: 'ChatGPTの使い方 完全ガイド',
    patternLabel: '完全ガイド',
    description: '初心者でもわかるように、基礎から活用術まで網羅的に解説する記事',
    category: 'guide',
    icon: '📖',
    defaultKeyword: 'ChatGPT 使い方 初心者',
    defaultTitle: 'ChatGPTの使い方｜初心者でも5分で始められる完全ガイド【2026年版】',
    exampleKeywords: ['ChatGPT', '使い方', '初心者', 'AI', 'プロンプト'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    articleType: 'explanation',
  },
  {
    id: 'guide-2',
    title: '副業の始め方｜月5万円ロードマップ',
    patternLabel: 'ロードマップ',
    description: 'ゴールまでの道筋をステップで示す、実践型ロードマップ記事',
    category: 'guide',
    icon: '💰',
    defaultKeyword: '副業 始め方 会社員',
    defaultTitle: '副業の始め方｜会社員でもできる月5万円の稼ぎ方【2026年版】',
    exampleKeywords: ['副業', '会社員', '稼ぎ方', '在宅ワーク', '収入'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'howto',
  },
  {
    id: 'guide-3',
    title: 'マーケティングとは？基礎から実践',
    patternLabel: '「〇〇とは」基礎解説',
    description: '「〇〇とは？」から始まり、基礎→実践まで段階的に解説する記事',
    category: 'guide',
    icon: '📊',
    defaultKeyword: 'マーケティング とは 基礎',
    defaultTitle: 'マーケティングとは？基礎から実践まで徹底解説【入門編】',
    exampleKeywords: ['マーケティング', '基礎', '入門', '戦略', '施策'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'explanation',
  },
  {
    id: 'guide-4',
    title: 'DX推進の進め方｜成功する7ステップ',
    patternLabel: '成功Nステップ',
    description: '成功に必要なステップを番号付きで整理し、順番に解説する記事',
    category: 'guide',
    icon: '🚀',
    defaultKeyword: 'DX推進 進め方 ステップ',
    defaultTitle: '【徹底解説】DX推進の進め方｜成功企業に学ぶ7つのステップ',
    exampleKeywords: ['DX', 'デジタルトランスフォーメーション', '推進', '成功事例'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 20000,
    articleType: 'explanation',
  },

  // --- 比較・ランキング ---
  {
    id: 'compare-1',
    title: 'プロジェクト管理ツール10選比較',
    patternLabel: 'N選 徹底比較',
    description: '複数の製品・サービスを一覧で比較し、おすすめを紹介する記事',
    category: 'compare',
    icon: '⚖️',
    defaultKeyword: 'プロジェクト管理ツール 比較 おすすめ',
    defaultTitle: 'プロジェクト管理ツール10選比較｜チーム規模別おすすめ【2026年版】',
    exampleKeywords: ['プロジェクト管理', 'ツール', '比較', 'Asana', 'Notion'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'comparison',
  },
  {
    id: 'compare-2',
    title: 'AIライティングツール比較',
    patternLabel: 'VS 対決比較',
    description: '2〜3つの製品を機能・料金・品質で直接対決させる比較記事',
    category: 'compare',
    icon: '🤖',
    defaultKeyword: 'AIライティングツール 比較',
    defaultTitle: 'AIライティングツール比較｜ChatGPT vs Claude vs Gemini【2026年版】',
    exampleKeywords: ['AI', 'ライティング', 'ChatGPT', 'Claude', 'Gemini'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'comparison',
  },
  {
    id: 'compare-3',
    title: 'クラウド会計ソフト比較',
    patternLabel: '機能×料金 比較表',
    description: '機能と料金を表形式で整理し、用途別のおすすめを示す比較記事',
    category: 'compare',
    icon: '🧮',
    defaultKeyword: 'クラウド会計ソフト 比較',
    defaultTitle: 'クラウド会計ソフト比較｜freee vs マネーフォワード vs 弥生【2026年版】',
    exampleKeywords: ['会計ソフト', 'freee', 'マネーフォワード', '弥生', '比較'],
    targetAudience: 'executive',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'comparison',
  },
  {
    id: 'compare-4',
    title: 'CRMツール比較｜導入ガイド',
    patternLabel: '比較＋導入ガイド',
    description: '比較だけでなく、導入手順や選び方のポイントまで解説する記事',
    category: 'compare',
    icon: '📋',
    defaultKeyword: 'CRM ツール 比較',
    defaultTitle: 'CRMツール比較｜Salesforce vs HubSpot vs Zoho【2026年版】',
    exampleKeywords: ['CRM', 'Salesforce', 'HubSpot', 'Zoho', '顧客管理'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'comparison',
  },

  // --- HowTo・実践 ---
  {
    id: 'howto-1',
    title: 'LP制作でCVRを上げる7ステップ',
    patternLabel: '改善ステップ',
    description: '現状の課題を特定し、改善ステップを順番に解説する実践記事',
    category: 'howto',
    icon: '🎯',
    defaultKeyword: 'LP制作 手順 コンバージョン',
    defaultTitle: 'LP制作の手順｜コンバージョン率を上げる7ステップ【完全ガイド】',
    exampleKeywords: ['LP', 'ランディングページ', '制作', 'コンバージョン', 'CVR'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'howto',
  },
  {
    id: 'howto-2',
    title: 'コンテンツマーケティングの始め方',
    patternLabel: '始め方マニュアル',
    description: 'ゼロから始める人向けに、立ち上げから運営まで全手順を解説する記事',
    category: 'howto',
    icon: '✍️',
    defaultKeyword: 'コンテンツマーケティング 始め方',
    defaultTitle: 'コンテンツマーケティングの始め方｜成功するメディア運営の全手順',
    exampleKeywords: ['コンテンツマーケティング', 'オウンドメディア', '運営', '戦略'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },
  {
    id: 'howto-3',
    title: '採用ブランディング戦略',
    patternLabel: '戦略設計 完全版',
    description: '戦略の設計から実行まで、フレームワーク付きで解説する記事',
    category: 'howto',
    icon: '👥',
    defaultKeyword: '採用ブランディング 戦略',
    defaultTitle: '【完全版】採用ブランディング戦略｜応募数を5倍にする方法',
    exampleKeywords: ['採用', 'ブランディング', '応募', '人事', '戦略'],
    targetAudience: 'hr',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },
  {
    id: 'howto-4',
    title: 'ECサイトのCVR改善実践ガイド',
    patternLabel: '最適化 実践ガイド',
    description: 'データに基づく最適化手法を、具体例付きで解説する実践記事',
    category: 'howto',
    icon: '🛒',
    defaultKeyword: 'ECサイト CVR改善',
    defaultTitle: 'ECサイトのCVR改善｜売上を2倍にする最適化手法【実践編】',
    exampleKeywords: ['EC', 'CVR', 'コンバージョン', '売上', '最適化'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'howto',
  },

  // --- 比較ランキング ---
  {
    id: 'ranking-1',
    title: 'SEOツールおすすめランキングTOP10',
    patternLabel: 'おすすめランキング TOP N',
    description: '評価基準を明確にし、ランキング形式でおすすめ順に紹介する記事',
    category: 'ranking',
    icon: '🏅',
    defaultKeyword: 'SEOツール おすすめ ランキング',
    defaultTitle: 'SEOツールおすすめランキングTOP10｜無料〜有料まで徹底比較【2026年版】',
    exampleKeywords: ['SEO', 'ツール', 'おすすめ', 'ランキング', '比較'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'ranking',
  },
  {
    id: 'ranking-2',
    title: '動画編集ソフト比較ランキング',
    patternLabel: '目的別ランキング',
    description: '初心者〜上級者など目的別にランキングを分けて紹介する比較記事',
    category: 'ranking',
    icon: '🎬',
    defaultKeyword: '動画編集ソフト 比較 おすすめ',
    defaultTitle: '動画編集ソフト比較ランキング｜目的別おすすめ12選【2026年版】',
    exampleKeywords: ['動画編集', 'ソフト', 'おすすめ', 'Premiere', 'DaVinci'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'ranking',
  },
  {
    id: 'ranking-3',
    title: 'ビジネスチャットツール比較',
    patternLabel: 'コスパ比較ランキング',
    description: '料金対機能のコスパ観点でランキング化し、最適解を提示する記事',
    category: 'ranking',
    icon: '💬',
    defaultKeyword: 'ビジネスチャット 比較 おすすめ',
    defaultTitle: 'ビジネスチャットツール比較｜コスパ最強はどれ？【2026年版】',
    exampleKeywords: ['ビジネスチャット', 'Slack', 'Teams', 'Chatwork', '比較'],
    targetAudience: 'executive',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'comparison',
  },
  {
    id: 'ranking-4',
    title: '転職サイト・エージェント比較',
    patternLabel: '体験者ランキング',
    description: '実際の利用者目線で、満足度・サポート力をランキングする記事',
    category: 'ranking',
    icon: '👔',
    defaultKeyword: '転職サイト おすすめ ランキング',
    defaultTitle: '転職サイト・エージェントおすすめランキング｜年代別TOP10【2026年版】',
    exampleKeywords: ['転職', 'サイト', 'エージェント', 'おすすめ', '比較'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 15000,
    articleType: 'ranking',
  },

  // --- ハウツー ---
  {
    id: 'tutorial-1',
    title: 'Notionの使い方｜業務効率化テク',
    patternLabel: 'ツール活用ハウツー',
    description: '特定ツールの使い方を、スクリーンショット付きで徹底解説する記事',
    category: 'tutorial',
    icon: '🛠️',
    defaultKeyword: 'Notion 使い方 業務効率化',
    defaultTitle: 'Notionの使い方完全ガイド｜業務効率が3倍になるテクニック集',
    exampleKeywords: ['Notion', '使い方', '効率化', 'テンプレート', 'タスク管理'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 10000,
    articleType: 'howto',
  },
  {
    id: 'tutorial-2',
    title: 'GA4の設定・分析方法',
    patternLabel: '設定マニュアル',
    description: '初期設定から分析レポート作成まで、手順を網羅するマニュアル記事',
    category: 'tutorial',
    icon: '📊',
    defaultKeyword: 'GA4 設定 使い方',
    defaultTitle: 'GA4の設定・使い方完全マニュアル｜初心者でも迷わない手順解説',
    exampleKeywords: ['GA4', 'Googleアナリティクス', '設定', '分析', 'レポート'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 15000,
    articleType: 'howto',
  },
  {
    id: 'tutorial-3',
    title: 'SEO内部対策チェックリスト',
    patternLabel: 'チェックリスト型',
    description: 'やるべきことをチェックリスト形式で整理し、漏れなく実行できる記事',
    category: 'tutorial',
    icon: '✅',
    defaultKeyword: 'SEO 内部対策 チェックリスト',
    defaultTitle: 'SEO内部対策チェックリスト50項目｜2026年最新版【保存必須】',
    exampleKeywords: ['SEO', '内部対策', 'チェックリスト', 'メタタグ', 'サイト速度'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 12000,
    articleType: 'howto',
  },
  {
    id: 'tutorial-4',
    title: '確定申告のやり方｜フリーランス向け',
    patternLabel: 'よくある失敗と対策',
    description: '初心者がつまずくポイントと対策をセットで解説する実践記事',
    category: 'tutorial',
    icon: '💡',
    defaultKeyword: '確定申告 やり方 フリーランス',
    defaultTitle: '確定申告のやり方｜フリーランスが知るべき節税テク【2026年版】',
    exampleKeywords: ['確定申告', 'フリーランス', '節税', '青色申告', '経費'],
    targetAudience: 'beginner',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'howto',
  },

  // --- トレンド ---
  {
    id: 'trend-1',
    title: '2026年注目SaaSトレンド20選',
    patternLabel: 'トレンドまとめ N選',
    description: '最新トレンドを業界別・カテゴリ別にまとめるランキング記事',
    category: 'trend',
    icon: '📈',
    defaultKeyword: 'SaaS トレンド 2026',
    defaultTitle: '2026年注目のSaaSトレンド20選｜業界別まとめ【保存版】',
    exampleKeywords: ['SaaS', 'トレンド', '2026年', 'クラウド', 'ビジネス'],
    targetAudience: 'marketer',
    recommendedTone: 'logical',
    recommendedChars: 12000,
    articleType: 'ranking',
  },
  {
    id: 'trend-2',
    title: 'AI活用の最新トレンドと事例',
    patternLabel: '最新動向レポート',
    description: '業界の最新動向を整理し、今後の予測と対応策をまとめるレポート記事',
    category: 'trend',
    icon: '🤖',
    defaultKeyword: 'AI活用 トレンド 2026',
    defaultTitle: 'AI活用の最新トレンド｜企業が今すぐ取り組むべき5つの領域【2026年版】',
    exampleKeywords: ['AI', '活用', 'トレンド', '生成AI', 'ChatGPT'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'explanation',
  },
  {
    id: 'trend-3',
    title: 'SNSマーケティング最新トレンド',
    patternLabel: 'プラットフォーム別トレンド',
    description: '各SNSプラットフォームの最新アルゴリズムや成功パターンを分析する記事',
    category: 'trend',
    icon: '📱',
    defaultKeyword: 'SNSマーケティング トレンド 2026',
    defaultTitle: 'SNSマーケティング最新トレンド｜X・Instagram・TikTok攻略法【2026年版】',
    exampleKeywords: ['SNS', 'マーケティング', 'トレンド', 'Instagram', 'TikTok'],
    targetAudience: 'marketer',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'explanation',
  },
  {
    id: 'trend-4',
    title: 'EC・D2Cブランドの成功戦略',
    patternLabel: '成功事例 + 未来予測',
    description: '成功事例と業界データから、今後の市場動向と勝ちパターンを予測する記事',
    category: 'trend',
    icon: '🛍️',
    defaultKeyword: 'D2C ブランド 成功事例 2026',
    defaultTitle: 'EC・D2Cブランドの成功戦略｜2026年に伸びるビジネスモデルとは',
    exampleKeywords: ['D2C', 'EC', 'ブランド', '成功事例', 'ビジネスモデル'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'case',
  },

  // --- 事例 ---
  {
    id: 'case-1',
    title: 'BtoB営業成功事例10選',
    patternLabel: '成功事例 N選',
    description: '実際の成功事例を複数集め、共通する戦略やポイントを分析する記事',
    category: 'case',
    icon: '🏆',
    defaultKeyword: 'BtoB営業 成功事例',
    defaultTitle: 'BtoB営業成功事例10選｜受注率を3倍にした戦略を公開',
    exampleKeywords: ['BtoB', '営業', '成功事例', '受注率', '戦略'],
    targetAudience: 'marketer',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'case',
  },
  {
    id: 'case-2',
    title: 'SNSマーケティング成功事例',
    patternLabel: '施策レポート',
    description: '具体的な施策とその結果をレポート形式でまとめる事例記事',
    category: 'case',
    icon: '📱',
    defaultKeyword: 'SNSマーケティング 成功事例',
    defaultTitle: 'SNSマーケティング成功事例｜フォロワー10万人達成の軌跡',
    exampleKeywords: ['SNS', 'マーケティング', '成功事例', 'Instagram', 'X'],
    targetAudience: 'marketer',
    recommendedTone: 'friendly',
    recommendedChars: 12000,
    articleType: 'case',
  },
  {
    id: 'case-3',
    title: 'DX推進成功事例｜業種別まとめ',
    patternLabel: '業種別事例集',
    description: '業種・規模別に成功事例を整理し、自社に当てはめられるようにする記事',
    category: 'case',
    icon: '🏢',
    defaultKeyword: 'DX 成功事例 業種別',
    defaultTitle: 'DX推進成功事例まとめ｜製造・小売・金融の業種別ベストプラクティス',
    exampleKeywords: ['DX', '成功事例', '製造業', '小売', '金融'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'case',
  },
  {
    id: 'case-4',
    title: 'データドリブン経営 完全ガイド',
    patternLabel: '手法解説ガイド',
    description: '専門的な手法や考え方を、導入ステップ付きで解説する記事',
    category: 'case',
    icon: '📊',
    defaultKeyword: 'データドリブン 経営 分析',
    defaultTitle: 'データドリブン経営完全ガイド｜意思決定を変える分析手法',
    exampleKeywords: ['データドリブン', '経営', '分析', 'KPI', 'BI'],
    targetAudience: 'executive',
    recommendedTone: 'professional',
    recommendedChars: 15000,
    articleType: 'explanation',
  },
]

export const categories: ArticleCategory[] = [
  {
    id: 'guide',
    label: '入門・解説',
    emoji: '📖',
    color: 'blue',
    templates: templates.filter((t) => t.category === 'guide'),
  },
  {
    id: 'compare',
    label: '比較',
    emoji: '⚖️',
    color: 'amber',
    templates: templates.filter((t) => t.category === 'compare'),
  },
  {
    id: 'ranking',
    label: '比較ランキング',
    emoji: '🏅',
    color: 'rose',
    templates: templates.filter((t) => t.category === 'ranking'),
  },
  {
    id: 'howto',
    label: 'HowTo・実践',
    emoji: '🎯',
    color: 'emerald',
    templates: templates.filter((t) => t.category === 'howto'),
  },
  {
    id: 'tutorial',
    label: 'ハウツー',
    emoji: '🛠️',
    color: 'cyan',
    templates: templates.filter((t) => t.category === 'tutorial'),
  },
  {
    id: 'trend',
    label: 'トレンド',
    emoji: '📈',
    color: 'orange',
    templates: templates.filter((t) => t.category === 'trend'),
  },
  {
    id: 'case',
    label: '事例',
    emoji: '🏆',
    color: 'purple',
    templates: templates.filter((t) => t.category === 'case'),
  },
]

export const allTemplates = templates

// 後方互換: generate-banners.ts / banners/route.ts が参照
export const articleTemplates = templates

// 後方互換: 旧 HorizontalScrollSection 用 (使われなくなったが念のため)
export const articleSections = categories.map((c) => ({
  id: c.id,
  title: c.label,
  description: '',
  templates: c.templates,
}))
