import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getInterviewXUser, requireAuth, checkOwnership, requireDatabase } from '@/lib/interviewx/access'

export async function GET(
  _req: NextRequest,
  { params }: { params: { id: string } }
) {
  const dbErr = requireDatabase()
  if (dbErr) return dbErr

  const { userId } = await getInterviewXUser()
  const authErr = requireAuth(userId)
  if (authErr) return authErr

  try {
    const project = await prisma.interviewXProject.findUnique({
      where: { id: params.id },
      select: {
        userId: true,
        title: true,
        companyName: true,
        brandColor: true,
        respondentName: true,
      },
    })
    if (!project) return NextResponse.json({ success: false, error: 'プロジェクトが見つかりません' }, { status: 404 })

    const ownerErr = checkOwnership(project, userId)
    if (ownerErr) return ownerErr

    const draft = await prisma.interviewXDraft.findFirst({
      where: { projectId: params.id },
      orderBy: { version: 'desc' },
    })
    if (!draft) return NextResponse.json({ success: false, error: 'ドラフトがありません' }, { status: 404 })

    const brandColor = project.brandColor || '#6366f1'

    // Markdownを簡易HTMLに変換
    let htmlContent = draft.content
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/「(.+?)」/g, '<span class="quote">「$1」</span>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>')

    htmlContent = `<p>${htmlContent}</p>`

    const fullHtml = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${draft.title || project.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Noto Sans JP', 'Hiragino Sans', sans-serif;
      color: #1e293b;
      line-height: 1.8;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 24px;
      background: #fff;
    }
    h1 {
      font-size: 28px;
      font-weight: 900;
      margin-bottom: 16px;
      color: ${brandColor};
      line-height: 1.4;
    }
    h2 {
      font-size: 22px;
      font-weight: 700;
      margin: 32px 0 12px;
      padding-bottom: 8px;
      border-bottom: 2px solid ${brandColor}40;
      color: #0f172a;
    }
    h3 {
      font-size: 18px;
      font-weight: 700;
      margin: 24px 0 8px;
      color: #334155;
    }
    p { margin: 12px 0; font-size: 16px; }
    .quote {
      color: ${brandColor};
      font-weight: 500;
    }
    ul { margin: 12px 0; padding-left: 24px; }
    li { margin: 4px 0; }
    strong { font-weight: 700; }
    em { font-style: italic; }
    .meta {
      margin-bottom: 32px;
      padding: 16px;
      background: #f8fafc;
      border-radius: 8px;
      font-size: 14px;
      color: #64748b;
    }
    .footer {
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #e2e8f0;
      font-size: 12px;
      color: #94a3b8;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="meta">
    ${project.companyName ? `<div><strong>${project.companyName}</strong></div>` : ''}
    ${project.respondentName ? `<div>回答者: ${project.respondentName}</div>` : ''}
    <div>文字数: ${draft.wordCount || 0}字 / 読了時間: 約${draft.readingTime || 0}分</div>
  </div>
  ${htmlContent}
  <div class="footer">
    Generated by ドヤインタビューAI-X
  </div>
</body>
</html>`

    return new NextResponse(fullHtml, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${encodeURIComponent(draft.title || project.title)}.html"`,
      },
    })
  } catch (e) {
    console.error('[InterviewX] export/html error:', e)
    return NextResponse.json({ success: false, error: 'HTMLエクスポートに失敗しました' }, { status: 500 })
  }
}
