from pathlib import Path
import json,hashlib,subprocess,datetime,ast,uuid
root=Path.cwd();b=Path('docs/audits/2026-10-06-all-services-recheck');overlay=b/'hr-department-read-repair-overlay';reg=b/'hr-department-read-regression-overlay/scripts/security-regression';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
assert subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()=='07ab5052af9b8bd29e58bc3564337df7ea77b956'
assert not subprocess.check_output(['git','diff','--name-only','HEAD','--','src','scripts','prisma'],text=True).strip()
review=json.loads((b/'hr-department-read-verification-review.json').read_text());assert review['status']=='candidate-verification-passed-awaiting-root-integration-and-full-gate' and all(sha(p)==h for p,h in review['sourceHashes'].items())
prior=Path((b/'hr-department-operation-current-gate.txt').read_text().strip());state=json.loads((prior/'state.json').read_text());assert state['status']=='passed' and len(state['gates'])==176
s=(prior/'supervise.py').read_text();tree=ast.parse(s);loop=next(n for n in tree.body if isinstance(n,ast.For) and ast.unparse(n.target)=='(name, args)');old=ast.literal_eval(loop.iter);assert len(old)==176
steps=[('hr-department-read-hierarchy11',['node',str(b/'verify-hr-department-hierarchy-boundaries.cjs')]),('hr-department-read-route8',['node',str(b/'verify-hr-department-read-candidate.cjs')]),('hr-department-read-transport15',['node',str(b/'verify-hr-department-paged-transport.cjs')]),('hr-department-read-realPG13',['python3',str(b/'hr-department-read-postgres-supervise.py')]),('hr-department-read-hook8',['node',str(b/'verify-hr-department-list-hook.cjs')]),('hr-department-read-consumer-mounted12',['node',str(b/'verify-hr-department-consumer-mounted.cjs')]),('hr-department-read-settings-mounted31',['node',str(b/'verify-hr-department-settings-paged-mounted.cjs')]),('hr-department-read-settings-native12',['node',str(b/'verify-hr-department-settings-paged-native.cjs')]),('hr-department-read-consumer-native9',['node',str(b/'verify-hr-department-consumer-native.cjs')]),('hr-department-read-types11',['node',str(b/'verify-hr-department-read-overlay-types.cjs')])]+[('hr-department-read-legacy-'+m,['node',str(b/'verify-hr-department-read-legacy.cjs'),m]) for m in ['related','access','validation','cache']]+[('hr-department-read-loader9',['node',str(b/'verify-hr-department-settings-paged-legacy-load.cjs')]),('hr-department-read-actualNext80',['env','DOYA_USE_INTEGRATED_NEXT=1','python3',str(b/'hr-department-read-next-supervise.py')])];assert len(steps)==16
production=sorted(str(p.relative_to(overlay)) for p in overlay.rglob('*') if p.is_file());assert len(production)==11
prepared={p:(overlay/p).read_bytes() for p in production};prepared.update({'scripts/security-regression/'+p.name:p.read_bytes() for p in reg.glob('*.cjs')})
# Retain original loader assertions while supplying the actual new paged client.
p=Path('scripts/security-regression/verify-hr-load-error-ui.cjs');t=p.read_text();assert "fetch: async (...args) => typeof response === 'function' ? response(...args) : response," in t
t=t.replace("  const env = {\n    fetch: async (...args) => typeof response === 'function' ? response(...args) : response,", "  const candidateFetch = async (...args) => typeof response === 'function' ? response(...args) : response\n  const { loadHrDepartmentList } = load('src/lib/hr/department-list-client.ts', {}, { fetch: candidateFetch, AbortController, TextDecoder, Uint8Array, setTimeout, clearTimeout })\n  const env = {\n    loadHrDepartmentList,\n    fetch: candidateFetch,")
t=t.replace("if (url === '/api/hr/departments') return Response.json({ success: true, organizationId: 'synthetic-org', flat: [] })", "if (url === '/api/hr/departments?format=pages') return Response.json({ success: true, format: 'hr-department-page-v1', organizationId: 'synthetic-org', revision: 'a'.repeat(64), total: 0, fragments: [], nextCursor: null })")
prepared[str(p)]=t.encode()
for p,data in prepared.items():Path(p).parent.mkdir(parents=True,exist_ok=True);Path(p).write_bytes(data)
lines=s.splitlines(keepends=True);s=''.join(lines[:loop.lineno-1])+'for name,args in '+repr(old+steps)+':\n'+''.join(lines[loop.lineno:]);s=s.replace("len(state['gates'])==176","len(state['gates'])==192").replace(str(b/'hr-department-operation-current-gate.txt'),str(b/'hr-department-read-current-gate.txt'))
extra=sorted({a[-1] for _,a in steps if a[-1].endswith(('.cjs','.py'))}|{str(b/'verify-hr-department-read-legacy.cjs'),str(b/'verify-hr-department-read-postgres.cjs'),str(b/'verify-hr-department-read-next.cjs')})
s=s.replace(' files=set()\n',' files=set()\n files.update(pathlib.Path(p) for p in '+repr(extra)+')\n files.update(x for x in pathlib.Path('+repr(str(overlay))+').rglob("*") if x.is_file())\n files.update(x for x in pathlib.Path('+repr(str(reg.parent.parent))+').rglob("*") if x.is_file())\n',1);ast.parse(s)
gate=b/('hr-department-read-release-'+str(uuid.uuid4()));gate.mkdir();(gate/'supervise.py').write_text(s);(b/'hr-department-read-current-gate.txt').write_text(str(gate)+'\n')
report={'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'rootApplied':True,'deployed':False,'productionFiles':production,'regressionFiles':sorted(set(prepared)-set(production)),'oldGate':str(prior),'newGate':str(gate),'original176RetainedExactlyInOrder':True,'expected':192,'added':steps,'sourceHashes':{p:sha(p) for p in prepared},'scope':'Local integration; all192 fresh gates, exact reviewed production publish and public verification remain required. Whole17services2074criteria189GET audit remains active.'};(b/'hr-department-read-gate-preparation.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'rootApplied':True,'productionFiles':11,'regressionFiles':len(report['regressionFiles']),'expected':192,'gate':str(gate)}))
