import pathlib,json,hashlib,subprocess,datetime,uuid,ast
root=pathlib.Path.cwd();base=pathlib.Path('docs/audits/2026-10-06-all-services-recheck');overlay=base/'hr-department-operation-repair-overlay';reg=base/'hr-department-operation-regression-overlay';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
head=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip();prior=json.loads((base/'hr-department-input-release-tracking.json').read_text());public=json.loads((base/'hr-department-input-public.json').read_text());assert head==prior['commit']==public['commit']=='757cbf1176077cdae38c956a409dcc565920521a';assert prior['observerStatus']=='passed' and public['passed'] and prior['publicVerificationExitCode']==0
assert not subprocess.check_output(['git','diff','--name-only','HEAD','--','src','scripts','reference'],text=True).strip();assert not subprocess.check_output(['git','ls-files','--others','--exclude-standard','--','src','scripts','reference'],text=True).strip();assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True).strip()
for name,count in [('hr-department-settings-durable-mounted-overlay.json',31),('hr-department-settings-durable-native-overlay.json',8),('hr-department-creation-mounted-overlay.json',24),('hr-department-settings-transport-overlay.json',9),('hr-department-operation-overlay-typecheck.json',True)]:
 d=json.loads((base/name).read_text());assert d['passed']==count,name;assert all(sha(pathlib.Path(p))==h for p,h in d.get('sourceHashes',{}).items()),name
for mode,count in [('related',33),('access',1),('validation',6),('cache',3)]:
 d=json.loads((base/('hr-department-operation-legacy-'+mode+'.json')).read_text());assert d['passed']==count and len(d['cases'])==count;assert all(sha(pathlib.Path(p))==h for p,h in d['sourceHashes'].items())
pg=json.loads((base/'hr-department-operation-postgres.json').read_text());assert pg['passed']==74;assert all(sha(overlay/p if (overlay/p).is_file() else pathlib.Path(p))==h for p,h in pg['sourceHashes'].items())
for name in ['hr-department-operation-postgres-supervisor.json','hr-department-operation-isolated-next-supervisor.json']:
 d=json.loads((base/name).read_text());assert d['status']=='passed' and d['evidenceValid'] and d['stopExitCode']==0 and d['postStopStatusExitCode']==3 and d['privateFolderRemoved']
nextProof=json.loads((base/'hr-department-operation-isolated-next-results.json').read_text());assert nextProof['passed']==68 and len(nextProof['cases'])==68
candidateApp=pathlib.Path(json.loads((base/'hr-department-operation-candidate-build.json').read_text())['app'])
for p,h in nextProof['sourceHashes'].items():
 selected=base/'hr-department-operation-isolated-next-supervise.py' if p.endswith('/hr-department-operation-next-supervise.py') else pathlib.Path(p) if p.startswith('docs/') else candidateApp/p
 assert sha(selected)==h,p
production=sorted(str(p.relative_to(overlay)) for p in overlay.rglob('*') if p.is_file());assert len(production)==6
regression=sorted(str(p.relative_to(reg)) for p in reg.rglob('*.cjs'));assert len(regression)==6
oldGate=pathlib.Path((base/'hr-department-input-current-gate.txt').read_text().strip());source=(oldGate/'supervise.py').read_text();tree=ast.parse(source);loop=next(n for n in tree.body if isinstance(n,ast.For) and ast.unparse(n.target)=='(name, args)');oldSteps=ast.literal_eval(loop.iter);assert len(oldSteps)==163
steps=[('hr-department-operation-realPG74',['python3',str(base/'hr-department-operation-postgres-supervise.py')]),('hr-department-settings-mounted31',['node',str(base/'verify-hr-department-settings-durable-mounted.cjs')]),('hr-department-creation-mounted24',['node',str(base/'verify-hr-department-creation-mounted.cjs')]),('hr-department-transport9',['node',str(base/'verify-hr-department-settings-transport.cjs')]),('hr-department-native8',['node',str(base/'verify-hr-department-settings-durable-native.cjs')]),('hr-department-operation-types6',['node',str(base/'verify-hr-department-operation-overlay-types.cjs')])]
steps += [('hr-department-operation-legacy-'+mode,['node',str(base/'verify-hr-department-operation-legacy.cjs'),mode]) for mode in ['related','access','validation','cache']]
steps += [('hr-department-settings-loader9',['node',str(base/'verify-hr-department-settings-legacy-load.cjs')]),('hr-department-operation-mandatory12',['node','scripts/security-regression/verify-hr-department-operation.cjs']),('hr-department-operation-actualNext68',['env','DOYA_USE_INTEGRATED_NEXT=1','python3',str(base/'hr-department-operation-next-supervise.py')])];assert len(steps)==13
lines=source.splitlines(keepends=True);source=''.join(lines[:loop.lineno-1])+'for name,args in '+repr(oldSteps+steps)+':\n'+''.join(lines[loop.lineno:]);source=source.replace("len(state['gates'])==163","len(state['gates'])==176");source=source.replace(str(base/'hr-department-input-current-gate.txt'),str(base/'hr-department-operation-current-gate.txt'))
additional=['verify-hr-department-operation-postgres.cjs','hr-department-operation-postgres-supervise.py','verify-hr-department-settings-durable-mounted.cjs','verify-hr-department-creation-mounted.cjs','verify-hr-department-settings-transport.cjs','verify-hr-department-settings-durable-native.cjs','verify-hr-department-operation-overlay-types.cjs','verify-hr-department-operation-legacy.cjs','verify-hr-department-settings-legacy-load.cjs','verify-hr-department-operation-next.cjs','hr-department-operation-next-supervise.py']
source=source.replace(' files=set()\n',' files=set()\n files.update(pathlib.Path('+repr(str(base))+')/name for name in '+repr(additional)+')\n files.update(x for x in pathlib.Path('+repr(str(overlay))+').rglob("*") if x.is_file())\n files.update(x for x in pathlib.Path('+repr(str(reg))+').rglob("*") if x.is_file())\n',1);ast.parse(source)
prepared={name:(overlay/name).read_bytes() for name in production};prepared.update({name:(reg/name).read_bytes() for name in regression});runner='scripts/security-regression/run.cjs';prepared[runner]=("for (const file of ['verify-hr-department-operation.cjs']) { const r = require('node:child_process').spawnSync(process.execPath, [require('node:path').join(__dirname, file)], {stdio:'inherit',timeout:60000}); if(r.error || r.status!==0) process.exit(r.status || 1); }\n"+pathlib.Path(runner).read_text()).encode()
for name,data in prepared.items():pathlib.Path(name).parent.mkdir(parents=True,exist_ok=True);pathlib.Path(name).write_bytes(data)
gate=base/('hr-department-operation-release-'+str(uuid.uuid4()));gate.mkdir();(gate/'supervise.py').write_text(source);(base/'hr-department-operation-current-gate.txt').write_text(str(gate)+'\n')
report={'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'rootApplied':True,'deployed':False,'head':head,'productionFiles':production,'regressionFiles':regression+[runner],'oldGate':str(oldGate),'newGate':str(gate),'original163RetainedExactlyInOrder':True,'expected':176,'added':steps,'scope':'Local integration only. Fresh full176, exact release and public verification remain required. No schema/customer/provider mutations.'};(base/'hr-department-operation-gate-preparation.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
