import pathlib,json,hashlib,datetime,subprocess,ast
base=pathlib.Path('docs/audits/2026-10-06-all-services-recheck');gate=pathlib.Path((base/'hr-department-read-current-gate.txt').read_text().strip());state=json.loads((gate/'state.json').read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
assert state['status']=='passed' and len(state['gates'])==192 and all(x['exitCode']==0 for x in state['gates']) and not state['changedSources'],'Fresh full192 must pass before release preparation'
manifest=json.loads((gate/'source-manifest.json').read_text());assert all(pathlib.Path(p).is_file() and sha(p)==h for p,h in manifest.items())
def steps(p):
 tree=ast.parse((p/'supervise.py').read_text());loop=next(n for n in tree.body if isinstance(n,ast.For) and ast.unparse(n.target)=='(name, args)');return ast.literal_eval(loop.iter)
prior=pathlib.Path((base/'hr-department-operation-current-gate.txt').read_text().strip());assert len(steps(prior))==176 and steps(gate)[:176]==steps(prior)
reports=[['hr-department-hierarchy-boundaries-overlay.json',11],['hr-department-read-candidate-results.json',8],['hr-department-paged-transport-overlay.json',15],['hr-department-read-postgres.json',13],['hr-department-list-hook-overlay.json',8],['hr-department-consumer-mounted-overlay.json',14],['hr-department-settings-paged-mounted-overlay.json',31],['hr-department-settings-paged-native-overlay.json',12],['hr-department-consumer-native-overlay.json',13],['hr-department-read-next-results.json',80]]+[['hr-department-read-legacy-'+m+'.json',n] for m,n in [('related',33),('access',1),('validation',6),('cache',3)]]
for name,count in reports:
 d=json.loads((base/name).read_text());assert d['passed']==count and d['expected']==count and len(d['cases'])==count and d['checkedAt']>=state['startedAt'],name
 assert d['sourceHashes'] and all(pathlib.Path(p).is_file() and sha(p)==h for p,h in d['sourceHashes'].items()),name
for name in ['hr-department-read-next-supervisor.json','hr-department-read-postgres-supervisor.json']:
 d=json.loads((base/name).read_text());assert d['status']=='passed' and d.get('evidenceValid',True) and d['stopExitCode']==0 and d['postStopStatusExitCode']==3 and d['privateFolderRemoved'] and d['startedAt']>=state['startedAt']
types=json.loads((base/'hr-department-read-overlay-typecheck.json').read_text());assert types['passed'] and not types['errors'] and types['expectedOverlayFiles']==11 and types['checkedAt']>=state['startedAt'];assert all(sha(p)==h for p,h in types['sourceHashes'].items())
loader=json.loads((base/'hr-department-settings-paged-legacy-load-overlay.json').read_text());assert loader['passed']==9 and loader['expected']==9 and len(loader['cases'])==9 and loader['checkedAt']>=state['startedAt'];assert str(base/'verify-hr-department-settings-paged-legacy-load.cjs') in manifest
prep=json.loads((base/'hr-department-read-gate-preparation.json').read_text());production=prep['productionFiles'];regression=prep['regressionFiles'];primary=production+regression;assert len(production)==11 and len(regression)==6
run=lambda *args:subprocess.check_output(['git',*args],text=True).strip();changed=set(run('diff','--name-only','HEAD').splitlines())|set(run('ls-files','--others','--exclude-standard').splitlines());assert {p for p in changed if p.startswith(('src/','scripts/','reference/'))}==set(primary)
for p in production:assert pathlib.Path(p).read_bytes()==(base/'hr-department-read-repair-overlay'/p).read_bytes()
for p in ['prisma/schema.prisma','package.json','package-lock.json']:assert pathlib.Path(p).read_bytes()==subprocess.check_output(['git','show','HEAD:'+p])
assets={};route=pathlib.Path('.next/server/app/api/hr/departments/route.js');assert route.is_file();assets[str(route)]=sha(route)
for folder,markers in [('settings',['/api/hr/departments?format=pages','hr-department-page-v1','hr-department-create-intent:v1:']),('employees/new',['/api/hr/departments?format=pages','部署一覧を再取得する','認証情報を確認しています。']),('employees/[id]/edit',['/api/hr/departments?format=pages','現在の所属（部署一覧で未確認）','未所属へ自動変更することはありません。','従業員情報を再取得する'])]:
 files=list((pathlib.Path('.next/static/chunks/app/hr')/folder).glob('*.js'));assert files,folder
 # Next may factor shared imports into shared chunks, so include the complete built JS graph.
 page='\n'.join(p.read_text() for p in files);shared=list(pathlib.Path('.next/static/chunks').glob('*.js'));text=page+'\n'+'\n'.join(p.read_text() for p in shared);assert all(m in text for m in markers),folder
 assets.update({str(p):sha(p) for p in files+shared})
scope='HR department read paging and nonrecursive hierarchy serialization; own-organization employee counts; full settings/new/edit load failure recovery, input preservation and authenticated form lifetimes.11 production files,6 mandatory fixture adaptations,3 existing full-page fixture adaptations; full192 retains original176 exactly plus16 read gates. No schema/dependency/provider/customer changes. Full17service2074criteria189GET audit remains active.'
review={'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'gate':str(gate),'reviewStatus':'full192-and-integratedNext80-passed-awaiting-exact-publish','productionFiles':production,'regressionFiles':regression,'requiredPrimaryFiles':primary,'sourceHashes':{p:sha(p) for p in primary},'compiledMarkerProof':{'checks':{'full192':True,'original176Preserved':True,'frozenSourcesUnchanged':True,'integratedNext80':True,'isolatedDatabasesStoppedAndRemoved':True,'allThreeClientPagesCompiled':True},'assets':assets},'scope':scope}
(base/'hr-department-read-release-review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n')
frozenChanges=changed&set(manifest);owned=json.loads((base/'hr-department-read-reviewed-frozen-sources.json').read_text());assert frozenChanges==set(owned['files']);assert all(sha(p)==h for p,h in owned['sourceHashes'].items())
audit=['integrate-hr-department-read.py','hr-department-read-current-gate.txt','hr-department-read-gate-preparation.json','hr-department-read-repair-plan.json','hr-department-read-verification-review.json','hr-department-read-candidate-build.py','hr-department-read-candidate-build.json','hr-department-deep-read-baseline.json','verify-hr-department-deep-read-baseline.cjs','hr-department-consumer-baseline.json','verify-hr-department-consumer-baseline.cjs','hr-department-read-next-supervisor.json','hr-department-read-postgres-supervisor.json','hr-department-read-overlay-typecheck.json','hr-department-settings-paged-legacy-load-overlay.json','prepare-hr-department-read-release.py','publish-hr-department-read.py','hr-department-read-release-observe.py','verify-hr-department-read-public.py','hr-department-read-release-review.json','hr-department-read-release-allowlist.json','all-service-get-api-checklist.csv','hr-department-followup-findings.md','hr-department-read-full-scope-inventory.json','hr-department-read-reviewed-frozen-sources.json','hr-employee-initial-load-native-baseline.json','verify-hr-employee-initial-load-native-baseline.cjs']+[r[0] for r in reports]
files=sorted(set(primary)|frozenChanges|{str(base/n) for n in audit}|{str(gate/n) for n in ['supervise.py','state.json','source-manifest.json']});allow={'checkedAt':review['checkedAt'],'releaseReady':True,'files':files,'requiredPrimaryFiles':primary,'reports':reports,'scope':scope};(base/'hr-department-read-release-allowlist.json').write_text(json.dumps(allow,ensure_ascii=False,indent=2)+'\n');assert all(pathlib.Path(p).is_file() for p in files);print(json.dumps({'readyForExactPublish':True,'files':len(files),'productionFiles':11,'fullGate':192,'actualNext':80}))
