import pathlib,json,hashlib,datetime,subprocess,ast
base=pathlib.Path('docs/audits/2026-10-06-all-services-recheck');gate=pathlib.Path((base/'hr-department-operation-current-gate.txt').read_text().strip());state=json.loads((gate/'state.json').read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
assert state['status']=='passed' and len(state['gates'])==176 and all(x['exitCode']==0 for x in state['gates']) and not state['changedSources']
manifest=json.loads((gate/'source-manifest.json').read_text());assert all(pathlib.Path(p).is_file() and sha(p)==h for p,h in manifest.items())
def steps(p):
 tree=ast.parse((p/'supervise.py').read_text());loop=next(n for n in tree.body if isinstance(n,ast.For) and ast.unparse(n.target)=='(name, args)');return ast.literal_eval(loop.iter)
prior=pathlib.Path((base/'hr-department-input-current-gate.txt').read_text().strip());assert len(steps(prior))==163 and steps(gate)[:163]==steps(prior)
reports=[['hr-department-operation-next-results.json',68],['hr-department-operation-postgres.json',74],['hr-department-settings-durable-mounted-overlay.json',31],['hr-department-creation-mounted-overlay.json',24],['hr-department-settings-transport-overlay.json',9],['hr-department-settings-durable-native-overlay.json',8]]+[['hr-department-operation-legacy-'+m+'.json',c] for m,c in [('related',33),('access',1),('validation',6),('cache',3)]]
for name,count in reports:
 d=json.loads((base/name).read_text());assert d['passed']==count and d['expected']==count and len(d['cases'])==count and d['checkedAt']>=state['startedAt'],name
 for p,h in d['sourceHashes'].items():
  selected=base/'hr-department-operation-repair-overlay'/p if (base/'hr-department-operation-repair-overlay'/p).is_file() else pathlib.Path(p)
  assert sha(selected)==h,(name,p)
for name in ['hr-department-operation-next-supervisor.json','hr-department-operation-postgres-supervisor.json']:
 d=json.loads((base/name).read_text());assert d['status']=='passed' and d['evidenceValid'] and d['stopExitCode']==0 and d['postStopStatusExitCode']==3 and d['privateFolderRemoved'] and d['startedAt']>=state['startedAt']
types=json.loads((base/'hr-department-operation-overlay-typecheck.json').read_text());assert types['passed'] and not types['errors'] and types['expectedOverlayFiles']==6 and types['checkedAt']>=state['startedAt'];assert all(sha(p)==h for p,h in types['sourceHashes'].items())
prep=json.loads((base/'hr-department-operation-gate-preparation.json').read_text());production=prep['productionFiles'];regression=prep['regressionFiles'];primary=production+regression;assert len(production)==6 and len(regression)==7
run=lambda *args:subprocess.check_output(['git',*args],text=True).strip();changed=set(run('diff','--name-only','HEAD').splitlines())|set(run('ls-files','--others','--exclude-standard').splitlines());assert {p for p in changed if p.startswith(('src/','scripts/','reference/'))}==set(primary)
for p in production:assert pathlib.Path(p).read_bytes()==(base/'hr-department-operation-repair-overlay'/p).read_bytes()
for p in ['prisma/schema.prisma','package.json','package-lock.json']:assert pathlib.Path(p).read_bytes()==subprocess.check_output(['git','show','HEAD:'+p])
entries=[pathlib.Path('.next/server/app/api/hr/departments/route.js'),pathlib.Path('.next/server/app/api/hr/department-operation/route.js')];assert all(p.is_file() for p in entries);assets={str(p):sha(p) for p in entries}
server=[p for p in pathlib.Path('.next/server').rglob('*.js') if 'hr-dept-create-v1:' in p.read_text()];assert server;assets.update({str(p):sha(p) for p in server})
client=list(pathlib.Path('.next/static/chunks/app/hr/settings').glob('*.js'));assert client;clientText='\n'.join(p.read_text() for p in client);assert all(marker in clientText for marker in ['hr-department-create-intent:v1:','作成結果を確認する','認証情報を確認しています。','招待リンクをコピーできませんでした。']);assets.update({str(p):sha(p) for p in client})
scope='Durable HR department creation receipt/recovery/cancellation; actor-scoped settings request/notification lifetime; accurate clipboard success. Source6 and regression7; full176 preserves original163, actualNext68, realPG74, mounted31/native8/hook24/transport9/types6. No schema/dependency/production customer/provider changes. Deep5000 department read and full17service2074criteria original188+newGET=189 audit remain incomplete.'
review={'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'gate':str(gate),'reviewStatus':'full176-and-integratedNext68-passed-awaiting-exact-publish','productionFiles':production,'regressionFiles':regression,'requiredPrimaryFiles':primary,'sourceHashes':{p:sha(p) for p in primary},'compiledMarkerProof':{'checks':{'full176':True,'original163Preserved':True,'frozenSourcesUnchanged':True,'integratedNext68':True,'isolatedDatabaseStoppedAndRemoved':True,'durableServerAndSettingsCompiled':True},'assets':assets},'scope':scope};(base/'hr-department-operation-release-review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n')
frozenChanges=changed&set(manifest);assert all(p in primary or p.startswith(str(base)+'/') for p in frozenChanges)
audit=['integrate-hr-department-operation.py','hr-department-operation-current-gate.txt','hr-department-operation-gate-preparation.json','hr-department-operation-repair-plan.json','hr-settings-actor-repair-plan.json','hr-department-settings-repair-plan.json','hr-department-settings-baseline.json','hr-department-settings-response-loss-baseline.json','hr-department-response-loss-postgres-baseline.json','hr-settings-actor-retention-native-baseline.json','hr-settings-clipboard-failure-baseline.json','hr-department-operation-isolated-next-results.json','hr-department-operation-isolated-next-supervisor.json','hr-department-operation-isolated-next-supervise.py','hr-department-operation-candidate-build.py','hr-department-operation-candidate-build.json','hr-department-operation-candidate-build-missing-logo-failure.json','hr-department-operation-candidate-build-font-network-failure.json','hr-department-operation-overlay-typecheck.json','hr-department-operation-postgres-supervisor.json','hr-department-operation-next-supervisor.json','hr-department-settings-legacy-load-overlay.json','prepare-hr-department-operation-release.py','publish-hr-department-operation.py','hr-department-operation-release-observe.py','verify-hr-department-operation-public.py','hr-department-operation-release-review.json','hr-department-operation-release-allowlist.json','all-service-get-api-checklist.csv','hr-department-followup-findings.md','hr-department-input-repair-plan.json','hr-department-input-release-tracking.json']+[x[0] for x in reports]
files=sorted(set(primary)|frozenChanges|{str(base/n) for n in audit}|{str(gate/n) for n in ['supervise.py','state.json','source-manifest.json']})
allow={'checkedAt':review['checkedAt'],'releaseReady':True,'files':files,'requiredPrimaryFiles':primary,'reports':reports,'scope':scope};(base/'hr-department-operation-release-allowlist.json').write_text(json.dumps(allow,ensure_ascii=False,indent=2)+'\n');assert all(pathlib.Path(p).is_file() for p in files);print(json.dumps({'readyForExactPublish':True,'files':len(files),'productionFiles':6,'fullGate':176,'actualNext':68}))
