import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { generateExportCode } from '@/lib/opening/gemini'
import { getTemplateById } from '@/lib/opening/templates'

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const animation = await prisma.openingAnimation.findUnique({
      where: { id: params.id },
    })

    if (!animation) {
      return NextResponse.json({ error: 'Animation not found' }, { status: 404 })
    }

    const config = animation.config as any
    const template = getTemplateById(animation.templateId)

    // Generate React code
    const reactCode = await generateExportCode({
      templateId: animation.templateId,
      templateName: template?.name || animation.templateId,
      colors: config.colors,
      texts: config.texts,
      timing: config.timing,
      showLogo: config.showLogo,
      showCTA: config.showCTA,
    })

    // Generate README
    const readme = `# Opening Animation

Generated by ドヤオープニングAI

## Installation

\`\`\`bash
npm install framer-motion
\`\`\`

## Usage

\`\`\`tsx
import OpeningAnimation from './OpeningAnimation'

function App() {
  const [showMain, setShowMain] = useState(false)

  return (
    <>
      {!showMain && <OpeningAnimation onComplete={() => setShowMain(true)} />}
      {showMain && <MainContent />}
    </>
  )
}
\`\`\`

## Props

| Prop | Type | Default | Description |
|------|------|---------|-------------|
| onComplete | () => void | - | アニメーション完了時のコールバック |
| skipable | boolean | true | クリックでスキップ可能か |
| duration | number | ${config.timing?.duration || 3.5} | 総再生時間（秒） |
`

    // Generate package.json
    const packageJson = JSON.stringify({
      name: 'opening-animation',
      version: '1.0.0',
      dependencies: {
        'framer-motion': '^10.17.0',
        'react': '^18.2.0',
        'react-dom': '^18.2.0',
      },
    }, null, 2)

    // Save code to DB
    await prisma.openingAnimation.update({
      where: { id: params.id },
      data: { reactCode },
    })

    return NextResponse.json({
      success: true,
      files: {
        'OpeningAnimation.tsx': reactCode,
        'README.md': readme,
        'package.json': packageJson,
      },
    })
  } catch (error: any) {
    console.error('Export error:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
