# -*- coding: utf-8 -*-
from pathlib import Path
import json
O=Path(__file__).parent
page='''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>どやまーけ｜全サービス ER設計図</title><style>
*{box-sizing:border-box}body{margin:0;color:#15243b;background:#f3f5f9;font:14px -apple-system,BlinkMacSystemFont,"Hiragino Sans",sans-serif}header{padding:25px 32px;background:#101e35;color:white}header small{color:#83c9ee;letter-spacing:3px}h1{font-size:26px;margin:9px 0}header p{color:#b6c5d9;margin:8px 0} .app{display:grid;grid-template-columns:265px 1fr;height:calc(100vh - 150px)}aside{background:white;border-right:1px solid #dbe2ed;padding:18px;overflow:auto}button,input{font:inherit}aside button{display:block;text-align:left;border:0;background:transparent;width:100%;padding:10px 9px;border-radius:6px;color:#344563;cursor:pointer}aside button.active{background:#dceafc;color:#0c4b91;font-weight:700}aside small{display:block;color:#718096;font-size:10px}input{width:100%;padding:9px;border:1px solid #cbd5e1;border-radius:6px;margin-bottom:10px}main{padding:22px;overflow:auto;min-width:0}h2{margin:0;font-size:20px}.toolbar{display:flex;gap:8px;align-items:center;margin:15px 0;flex-wrap:wrap}.toolbar button{padding:8px 12px;border:1px solid #bdcce0;background:white;border-radius:6px;cursor:pointer}.notice{color:#586b85;line-height:1.8;margin:10px 0}#canvas{height:60vh;min-height:420px;background:white;overflow:auto;border:1px solid #dbe2ed;border-radius:10px;padding:20px}#canvas svg{max-width:none!important;display:block;margin:0 auto}details{background:white;border:1px solid #dbe2ed;border-radius:8px;margin-top:15px;padding:14px;line-height:1.8}summary{cursor:pointer;font-weight:600}pre{overflow:auto;background:#f4f6fa;padding:12px;font-size:12px}#notes{white-space:pre-wrap;font-size:13px}table{border-collapse:collapse;width:100%;font-size:12px}td,th{padding:8px;border-bottom:1px solid #dbe2ed;text-align:left}.pill{display:inline-block;padding:4px 9px;background:#234369;border-radius:20px;font-size:12px;margin-right:8px}#status{font-size:12px;color:#65748a}@media(max-width:750px){.app{grid-template-columns:190px 1fr}header{padding:18px}main{padding:12px}}@media print{aside,.toolbar{display:none}.app{display:block;height:auto}#canvas{height:auto;overflow:visible}#canvas svg{width:100%!important;height:auto!important}main{overflow:visible}}
</style><header><small>DOYAMARKE / DATA ARCHITECTURE</small><h1>どやまーけ 全サービス ER設計図</h1><p>共通基盤から各サービスまで、実装に基づくデータ構造</p><span class="pill">公開対象 __PUBLIC_COUNT__サービス</span><span class="pill">__MODEL_COUNTS__</span><span class="pill">2026.10.06 ローカル実装</span></header><div class="app"><aside><input id="search" placeholder="サービス・モデルを検索"><nav id="nav"></nav></aside><main><h2 id="title"></h2><p class="notice">図は定義済みのリレーションのみ。1＝必須1件、0..1＝任意1件、0..N＝複数。主要列を表示し、全項目は下のデータ辞書に記載しています。</p><div class="toolbar"><button id="fit">画面に合わせる</button><button id="plus">拡大 ＋</button><button id="minus">縮小 −</button><button id="svg">SVG保存</button><button id="mmd">Mermaid保存</button><span id="status"></span></div><div id="canvas"></div><details><summary>データ辞書・制約（選択中の図）</summary><p>@@unique([a,b]) は組合せの一意制約です。各列が単独で一意という意味ではありません。FKはスキーマで定義された外部キー列にのみ表示しています。</p><div id="dictionary"></div></details><details><summary>__PUBLIC_COUNT__サービスと保存モデルの対応</summary><div id="services"></div></details><details open><summary>設計上の注意・対象範囲</summary><div id="notes"></div></details></main></div><script>__MERMAID__</script><script>
const DATA=__DATA__;window.DATA=DATA;
mermaid.initialize({startOnLoad:false,securityLevel:'strict',theme:'base',maxEdges:1000,maxTextSize:200000,themeVariables:{primaryColor:'#edf4ff',primaryBorderColor:'#6284b2',primaryTextColor:'#162a47',lineColor:'#6f829e',fontFamily:'Arial, sans-serif',fontSize:'14px'},er:{useMaxWidth:false}});
let current,scale=1,seq=0;const cache={};const el=id=>document.getElementById(id);const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function nav(q=''){el('nav').innerHTML='';DATA.charts.filter(c=>(c.title+' '+c.names.join(' ')).toLowerCase().includes(q.toLowerCase())).forEach(c=>{let b=document.createElement('button');b.dataset.id=c.id;b.className=c.id===current?.id?'active':'';b.innerHTML=escape(c.title)+'<small>'+c.kind+' · '+c.names.length+' models</small>';b.onclick=()=>show(c.id);el('nav').append(b)})}
function resize(fit=false){let svg=el('canvas').querySelector('svg');if(!svg)return;let b=svg.viewBox.baseVal;if(fit)scale=Math.min(1,(el('canvas').clientWidth-45)/b.width,(el('canvas').clientHeight-45)/b.height);svg.style.width=(b.width*scale)+'px';svg.style.height=(b.height*scale)+'px';el('status').textContent=Math.round(scale*100)+'% · '+current.names.length+'モデル'}
async function show(id){current=DATA.charts.find(c=>c.id===id);let c=current;el('title').textContent=c.title;el('canvas').textContent='ER図を描画しています…';nav(el('search').value);try{if(!cache[id])cache[id]=(await mermaid.render('er'+(++seq),c.code)).svg;if(current.id!==id)return;el('canvas').innerHTML=cache[id];resize(true);el('dictionary').innerHTML=c.names.map(n=>{let m=DATA.models[n];return '<h3>'+n+'</h3><p>DB: '+m.table+' / schema.prisma:'+m.line+'</p><pre>'+escape(m.body)+'</pre>'}).join('');}catch(e){el('canvas').textContent=e.message;throw e}}
window.show=show;window.renderAll=async()=>{for(const c of DATA.charts){if(!cache[c.id])cache[c.id]=(await mermaid.render('er'+(++seq),c.code)).svg;}return Object.fromEntries(Object.entries(cache))};
el('search').oninput=e=>nav(e.target.value);el('fit').onclick=()=>resize(true);el('plus').onclick=()=>{scale*=1.3;resize()};el('minus').onclick=()=>{scale/=1.3;resize()};function save(text,type,ext){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download='doyamarke-'+current.id+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}el('svg').onclick=()=>save(cache[current.id],'image/svg+xml','svg');el('mmd').onclick=()=>save(current.code,'text/plain','mmd');el('notes').textContent=DATA.notes+'\\n\\nコミット: '+DATA.manifest.commit+'\\n'+DATA.manifest.source;
el('services').innerHTML='<table><tr><th>サービス</th><th>ID</th><th>主な保存先</th></tr>'+DATA.services.filter(s=>s.public).map(s=>'<tr><td>'+s.name+'</td><td>'+s.id+'</td><td>'+Object.values(DATA.models).filter(m=>m.group===s.id).map(m=>m.name).join(', ')+(s.id==='banner'?' / Generation（成果物・利用ログ）':'')+'</td></tr>').join('')+'</table>';nav();show('overview');
</script></html>'''
page=page.replace('__MERMAID__',(O/'mermaid.js').read_text().replace('</script','<\\/script')).replace('__DATA__',(O/'data.json').read_text().replace('</','<\\/'))
data=json.loads((O/'data.json').read_text()); page=page.replace('__MODEL_COUNTS__',str(data['manifest']['models'])+'モデル / '+str(data['manifest']['relations'])+'リレーション'); page=page.replace('__PUBLIC_COUNT__',str(data['manifest']['public_services'])); (O/'index.html').write_text(page)
print('HTML bytes',len(page.encode()))
